#plot the data generated by the alignment

source("/Users/deepikaa/Desktop/data_desktop/Doc/align_tracks.R")
mnorm<-function(x) return((x-min(x,na.rm=T))/(max(x,na.rm=T)-min(x,na.rm=T)))
##########haploid
#sla1
#WT sla1
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/WT/sla1egfp/2017_06_12_823/tracks.Rdata"))->wtsla12017
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/WT/sla1egfp/2016_06_01_141_geneva/mw100/tracks.Rdata"))->wtsla1_141geneva
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/WT/sla1egfp/2016_06_01_141_geneva/mw100/tracks.Rdata"))->wtsla1_141geneva
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/WT/sla1egfp/wo_treat/tracks.Rdata"))->wtsla1_hd
#RVSmutants
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Rvsduplication/Sla1/2017_06_12_161d100_167d100_823_5a/tracks.Rdata"))->rvsdup_sla1
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Rvsduplication/Rvs_delsh3/2017_12_29/sh3dup_823_5a/tracks.Rdata"))->delsh3dup_sla1
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/rvs_delsh3/rvs167_delsh3_sla1_egfp/2015_04_02/tracks.Rdata"))->delsh3_sla1
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/delrvs167/delrvs_sla1_0531/wo_treatment/analysis_1_2p/tracks.Rdata"))->delrvs_sla1

#rvs
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/WT/Rvs167/2017_03_29_3131/tracks.Rdata"))->WTrvs_gen3131
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/rvs_delsh3/rvs167egfp_delsh3/2016_06_02_3154_delsh3_gfp_geneva/analysis2woFlalign/tracks.Rdata"))->delsh3_g_woflalign

get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Rvsduplication/Rvs167/2017_06_19/161_d100_167d3131_5b/tracks.Rdata")) -> rvs161d_167d
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Rvsduplication/Rvs_delsh3/2017_07_21/delsh3dup/motile_wt/motile_wt.Rdata")) ->delsh3_dup_sorted

##abp1 for happloid
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/delrvs167/delrvs_abpegfp_wotreat/x0122_80ms_25p488_dualview488_1x255/tracks.Rdata"))->delrvs_abp1
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/rvs_delsh3/rvs167egfp_delsh3/2016_06_02_3154_delsh3_gfp_geneva/analysis2woFlalign/tracks.Rdata"))->delsh3_g_woflalign


#generate a template transformation matrix to fool gen.data
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/DC/wt/Rvs167/110824_mytrasf.Rdata"))->transformation_template
transformation_template<-0*transformation_template

time(WTrvs_gen3131$ts)[which(WTrvs_gen3131$ts[,"mean_sFI"]==max(WTrvs_gen3131$ts[,"mean_sFI"],na.rm=TRUE))]->t0_rvs
time(rvs161d_167d$ts)[which(rvs161d_167d$ts[,"mean_sFI"]==max(rvs161d_167d$ts[,"mean_sFI"],na.rm=TRUE))]->t0_rvsdup
time(delsh3_g_woflalign$ts)[which(delsh3_g_woflalign$ts[,"mean_sFI"]==max(delsh3_g_woflalign$ts[,"mean_sFI"],na.rm=TRUE))]->t0_delsh3
time(delsh3_dup_sorted$ts)[which(delsh3_dup_sorted$ts[,"mean_sFI"]==max(delsh3_dup_sorted$ts[,"mean_sFI"],na.rm=TRUE))]->t0_delsh3dup


#output nice and usable data
## haploid

#sla1
#sla1_wt<-gen.data(WTsla1,sla1_transf, NA, NA, t0=my_t0, zero=0)
sla823<-gen.data(wtsla12017,transformation_template,n=NA,sn=NA)
sla1_141geneva<-gen.data(wtsla1_141geneva,transformation_template,n=NA,sn=NA)
sla1_hd<-gen.data(wtsla1_hd,transformation_template,n=NA,sn=NA)
#sla1<-gen.data(sla1_notrans,transformation_template,n=NA,sn=NA, zero=0, t0=t0_abp)

#mutant
rvsdup<-gen.data(rvsdup_sla1,transformation_template,n=NA,sn=NA)
delsh3dup<-gen.data(delsh3dup_sla1,transformation_template,n=NA,sn=NA)
delsh3<-gen.data(delsh3_sla1,transformation_template,n=NA,sn=NA)
sla141_rvsdel<-gen.data(delrvs_sla1,transformation_template,n=NA,sn=NA)

#rvs
rvs_wt<-gen.data(WTrvs_gen3131,transformation_template,n=53.2,sn=5.2, t0=t0_rvs)
rvs_dup<-gen.data(rvs161d_167d,transformation_template,n=82.7 ,sn=7.5, t0=t0_rvsdup)

delsh3_dup<-gen.data(delsh3_dup_sorted,transformation_template,n=43.6 ,sn=9.6, t0=t0_delsh3dup)
delsh3_g<-gen.data(delsh3_g_woflalign,transformation_template,n=30.1,sn=9.9, t0=t0_delsh3)


#time for sla1
#wt
#tsla823=sla823[,"t"]-sla823[1,"t"]
#tsla_141geneva=sla1_141geneva[,"t"]-sla1_141geneva[1,"t"]
#tsla_hd=sla1_hd[,"t"]-sla1_hd[1,"t"]

####mutant
#trvsdup=rvsdup[,"t"]-rvsdup[1,"t"]
#tdelsh3dup=delsh3dup[,"t"]-delsh3dup[1,"t"]
#tdelsh3=delsh3[,"t"]-delsh3[1,"t"]
#tsla141_rvsdel=sla141_rvsdel[,"t"]-sla141_rvsdel[1,"t"]

#set initial y position to 0
#rvs
x_rvs_dup<-mean(rvs_dup[1:25,"x"])
x_3131<-mean(rvs_wt[1:25,"x"])
x_delsh3_sorted<-mean(delsh3_dup[1:10,"x"])
x_delsh3_g<-mean(delsh3_g[1:25,"x"])

#sla1
xsla823<-mean(sla823[1:125,"x"])
xsla1_141geneva<-mean(sla1_141geneva[1:125,"x"])
xsla1_hd<-mean(sla1_hd[1:125,"x"])
xrvsdup<-mean(rvsdup[1:125,"x"])
xdelsh3dup<-mean(delsh3dup[1:125,"x"])
xdelsh3<-mean(delsh3[1:185,"x"])
#xsla823_inpdel<-mean(sla823_inpdel[1:25,"x"])
xsla141_rvsdel<-mean(sla141_rvsdel[1:165,"x"])

cols_blue<-brewer.pal(n=9, name="Blues")
cols_rdpu<-brewer.pal(n=9, name="RdPu")

##with delsh3-duplicated
pdf("all_haploid_2020.pdf")

#sla1
myplot(sla823[,"t"]-13.5,sla823[,"x"]-xsla823,sla823[,"t.err"],sla823[,"x.err"],line.col="#023858", xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-10,10),ylim=c(-25,200))
#myplot(tsla_141geneva-14.7,sla1_141geneva[,"x"]-xsla1_141geneva,sla1_141geneva[,"t.err"],sla1_141geneva[,"x.err"],line.col=cols_blue[8],hold_on=TRUE,line.lwd=3,deltat=0.25)
#myplot(tsla_hd-23.5,sla1_hd[,"x"]-xsla1_hd,sla1_hd[,"t.err"],sla1_hd[,"x.err"],line.col=cols_blue[7],hold_on=TRUE,line.lwd=3,deltat=0.25)

###mut
myplot(rvsdup[,"t"]-28.5,rvsdup[,"x"]-xrvsdup,rvsdup[,"t.err"],rvsdup[,"x.err"],line.col=cols_rdpu[4],hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(delsh3dup[,"t"]-15,delsh3dup[,"x"]-xdelsh3dup,delsh3dup[,"t.err"],delsh3dup[,"x.err"],line.col=cols_rdpu[8],hold_on=TRUE,line.lwd=3,deltat=0.25)

#myplot(tsla823_inpdel-5.5,sla823_inpdel[,"x"]-xsla1_823_inpdel,sla823_inpdel[,"t.err"],sla823_inpdel[,"x.err"],line.col=cols_rdpu[7],hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(delsh3[,"t"]-26.5,delsh3[,"x"]-xdelsh3,delsh3[,"t.err"],delsh3[,"x.err"],line.col= cols_rdpu[6],hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(sla141_rvsdel[,"t"]-34,sla141_rvsdel[,"x"]-xsla141_rvsdel,sla141_rvsdel[,"t.err"],sla141_rvsdel[,"x.err"],line.col=cols_rdpu[5],hold_on=TRUE,line.lwd=3,deltat=0.25)
title(main="sla1-GFP", sub="time aligned to movement")
legend("topleft",c("sla1 823","delsh3 dup","delsh3", "rvsdel"),lty=1,col=c("#023858", cols_rdpu[8], cols_rdpu[6], cols_rdpu[5]),bty='n', cex=0.75)




##rvs movement
myplot(rvs_dup[,"t"],rvs_dup[,"x"]-x_rvs_dup,rvs_dup[,"t.err"],rvs_dup[,"x.err"],line.col="#00FFFF", xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-10,10),ylim=c(-25,200))
#myplot(t_rvs551x529_d-1.9,rvs551x529_d[,"x"]-x_rvs551x529_d,rvs551x529_d[,"t.err"],rvs551x529_d[,"x.err"],line.col="#660033", hold_on=TRUE, line.lwd=3,deltat=0.25)

myplot(rvs_wt[,"t"],rvs_wt[,"x"]-x_3131,rvs_wt[,"t.err"],rvs_wt[,"x.err"],line.col="#669900", hold_on=TRUE, line.lwd=3,deltat=0.25)
myplot(delsh3_dup[,"t"],delsh3_dup[,"x"]-x_delsh3_sorted,delsh3_dup[,"t.err"],delsh3_dup[,"x.err"],line.col="#FF6600", hold_on=TRUE, line.lwd=3,deltat=0.25)
myplot(delsh3_g[,"t"],delsh3_g[,"x"]-x_delsh3_g,delsh3_g[,"t.err"],delsh3_g[,"x.err"],line.col="#996600", hold_on=TRUE, line.lwd=3,deltat=0.25)
title(main="Rvs167-GFP", sub="time aligned to rvs max")
legend("topleft",c("rvs dup","rvs wt","delsh3 dup","delsh3"),lty=1,col=c("#00FFFF", "#669900", "#FF6600", "#996600"),bty='n', cex=0.75)


#rvs intensity
myplot(rvs_dup[,"t"],rvs_dup[,"n"],rvs_dup[,"t.err"],rvs_dup[,"n.err"],line.col="#000000",xlab="time(s)",ylab="# molecules",xlim=c(-10,10), ylim=c(0,200))
myplot(rvs_wt[,"t"],rvs_wt[,"n"],rvs_wt[,"t.err"],rvs_wt[,"n.err"],line.col="#669900",hold_on=TRUE)
myplot(delsh3_dup[,"t"],delsh3_dup[,"n"],delsh3_dup[,"t.err"],delsh3_dup[,"n.err"],line.col="#FF6600",hold_on=TRUE)
myplot(delsh3_g[,"t"],delsh3_g[,"n"],delsh3_g[,"t.err"],delsh3_g[,"n.err"],line.col="#996600",hold_on=TRUE)

title(main="Rvs167-GFP", sub="time aligned to rvs max ")
legend("topleft",c("rvs dup","rvs wt","delsh3 dup","delsh3"),lty=1,col=c("#000000", "#669900", "#FF6600", "#996600" ),bty='n', cex=0.75)
dev.off()

