#plot the data generated by the alignment
library(RColorBrewer)
source("/Users/deepikaa/Desktop/data_desktop/Doc/align_tracks.R")
mnorm<-function(x) return((x-min(x,na.rm=T))/(max(x,na.rm=T)-min(x,na.rm=T)))
##########haploid
#sla1
#WT sla1
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/WT/sla1egfp/2017_06_12_823/tracks.Rdata"))->wtsla12017

#RVSmutants
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Rvsduplication/Sla1/2017_06_12_161d100_167d100_823_5a/tracks.Rdata"))->rvsdup_sla1
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Rvsduplication/Rvs_delsh3/2017_12_29/sh3dup_823_5a/tracks.Rdata"))->delsh3dup_sla1
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/rvs_delsh3/rvs167_delsh3_sla1_egfp/2015_04_02/tracks.Rdata"))->delsh3_sla1
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/delrvs167/2020_02_29/1802/percentile_1_5/fimax_true/tracks.Rdata"))->delrvs_sla1_new
##--> sla1 2020_01_19 (ie 2021)

#abp mcherry from mcherry_sla1co-tag
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_07_31/823_mch/tracks.Rdata"))->abpmch_notrans_1xRvs
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_02_18/823/tracks.Rdata"))->abpmch_notrans_1xRvs_sla1
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_07_26/2xRVS823_3706/tracks.Rdata"))->abpmch_notrans_2xRvs_sla1
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_07_27/1xbar_823_3292/tracks.Rdata"))->abpmch_notrans_1xBar_sla1
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_07_27/2xbar_823_3826/tracks.Rdata"))->abpmch_notrans_2xBar_sla1
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_02_06/1801/tracks.Rdata"))->abpmch_notrans_rvsdel_sla1

#trasnformations for sla1
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments/abpmch_Sla1823_mytrasf.Rdata"))->sla1823_transf
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments/old_alignments/abpmch_Sla1823_mytrasf.Rdata"))->sla1823_transf
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments_haploid/rvsdup_sla1_3706_mytrasf.Rdata"))->sla13706_transf
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments_haploid/rvsdelsh3_sla1_3292_mytrasf.Rdata"))->sla13292_transf
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments_haploid/rvsdelsh3_sla1_3826_tracks2_d_mytrasf.Rdata"))->sla13826_transf
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments/fimax_false_1801/abpmch_delrvs1801_mytrasf.Rdata"))->sla1801_transf

#generate a template transformation matrix to fool gen.data
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/DC/wt/Rvs167/110824_mytrasf.Rdata"))->transformation_template
transformation_template<-0*transformation_template

#abp1mCh times from sla1 co-tag
time(abpmch_notrans_1xRvs_sla1$ts)[which(abpmch_notrans_1xRvs_sla1$ts[,"mean_sFI"]==max(abpmch_notrans_1xRvs_sla1$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abpmch_1xRvs_sla1
time(abpmch_notrans_2xRvs_sla1$ts)[which(abpmch_notrans_2xRvs_sla1$ts[,"mean_sFI"]==max(abpmch_notrans_2xRvs_sla1$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abpmch_2xRvs_sla1
time(abpmch_notrans_1xBar_sla1$ts)[which(abpmch_notrans_1xBar_sla1$ts[,"mean_sFI"]==max(abpmch_notrans_1xBar_sla1$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abpmch_1xBar_sla1
time(abpmch_notrans_2xBar_sla1$ts)[which(abpmch_notrans_2xBar_sla1$ts[,"mean_sFI"]==max(abpmch_notrans_2xBar_sla1$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abpmch_2xBar_sla1
time(abpmch_notrans_rvsdel_sla1$ts)[which(abpmch_notrans_rvsdel_sla1$ts[,"mean_sFI"]==max(abpmch_notrans_rvsdel_sla1$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abpmch_rvsdel_sla1
print("time abpmch ok")


##################################################sla1 with transformation
#sla1_wt<-gen.data(WTsla1,sla1_transf, NA, NA, t0=my_t0, zero=0)
sla823<-gen.data(wtsla12017,sla1823_transf,n=NA,sn=NA,t0=t0_abpmch_1xRvs_sla1)

#mutant
rvsdup<-gen.data(rvsdup_sla1,sla13706_transf,n=NA,sn=NA,t0=t0_abpmch_2xRvs_sla1)
delsh3dup<-gen.data(delsh3dup_sla1,sla13826_transf,n=NA,sn=NA,t0=t0_abpmch_2xBar_sla1)
delsh3<-gen.data(delsh3_sla1,sla13292_transf,n=NA,sn=NA,t0=t0_abpmch_1xBar_sla1)
sla1_rvsdel<-gen.data(delrvs_sla1_new,sla1801_transf,n=NA,sn=NA,t0=t0_abpmch_rvsdel_sla1)
################################################################################

#abp1 mch SC tracking from sla1 co-tagged strains
#numbers from sla1 co-tag
abpmch_1x_sla1_no<-gen.data(abpmch_notrans_1xRvs_sla1,transformation_template,n=344.8,sn=27.8,rescale.n=1, t0=t0_abpmch_1xRvs_sla1)
abpmch_2x_sla1_no<-gen.data(abpmch_notrans_2xRvs_sla1,transformation_template,n=318.8 ,sn=28.1,rescale.n=1, t0=t0_abpmch_2xRvs_sla1)
abpmch_1xBAR_sla1_no<-gen.data(abpmch_notrans_1xBar_sla1,transformation_template,n=243.5,sn=24.6,rescale.n=1,t0=t0_abpmch_1xBar_sla1)
abpmch_2xBAR_sla1_no<-gen.data(abpmch_notrans_2xBar_sla1,transformation_template,n=296.2,sn=25,rescale.n=1,t0=t0_abpmch_2xBar_sla1)
#abpmch_rvsdel<-gen.data(abpmch_notrans_rvsdel_sla1,transformation_template,n=384.5,sn=35.9,rescale.n=1,t0=t0_abpmch_rvsdel) #mky3297
abpmch_rvsdel<-gen.data(abpmch_notrans_rvsdel_sla1,transformation_template,n=362.64,sn=39.36,rescale.n=1,t0=t0_abpmch_rvsdel_sla1)


#sla1
xsla823<-mean(sla823[1:125,"x"])
xrvsdup<-mean(rvsdup[1:125,"x"])
xdelsh3dup<-mean(delsh3dup[1:125,"x"])
xdelsh3<-mean(delsh3[1:185,"x"])
#xsla823_inpdel<-mean(sla823_inpdel[1:25,"x"])
xsla1_rvsdel<-mean(sla1_rvsdel[1:165,"x"])

#abp1 mCH
#x_abpmch<-mean(rabpmch_1x[1:25,"x"])
x_abpmch1x<-mean(abpmch_1x_sla1_no[1:25,"x"])
x_abpmch2x<-mean(abpmch_2x_sla1_no[1:25,"x"])
x_abpmch1xBar<-mean(abpmch_1xBAR_sla1_no[1:10,"x"])
x_abpmch2xBar<-mean(abpmch_2xBAR_sla1_no[1:25,"x"])
x_abpmchrvsdel<-mean(abpmch_rvsdel[1:25,"x"])

cols_blue<-brewer.pal(n=9, name="Blues")
cols_rdpu<-brewer.pal(n=9, name="RdPu")

##with delsh3-duplicated
pdf("all_haploid_2021_redone_july2021.pdf")
mnorm<-function(x) return((x-min(x,na.rm=T))/(max(x,na.rm=T)-min(x,na.rm=T)))

#b, with transformation matrix that includes all dc tracks for delsh3dup_sla1
#a, with 04, 25, 27,28, 30 removed
#apparently no difference??
#c with new delsh3dup abp1mch SC tracks.Rdata after cleanup, and redoing the DC alignment with this new tracks.Rdata
#d with abp1 nombers from 2020_01_19_haploid, set2
#e with new tracks.data from abpmch 2xBAR after removing tracks 11,14,28,31 from the tracks folder
#f with new 2xBAR abpmch, and also redone DC alignment
#g with newly analysed 1xBAR abpmch
myplot(sla823[,"t"],sla823[,"x"]-xsla823,sla823[,"t.err"],sla823[,"x.err"],line.col="#023858", xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-30,30),ylim=c(-25,200))
myplot(rvsdup[,"t"],rvsdup[,"x"]-xrvsdup,rvsdup[,"t.err"],rvsdup[,"x.err"],line.col=cols_rdpu[4],hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(delsh3dup[,"t"],delsh3dup[,"x"]-xdelsh3dup,delsh3dup[,"t.err"],delsh3dup[,"x.err"],line.col=cols_rdpu[8],hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(delsh3[,"t"],delsh3[,"x"]-xdelsh3,delsh3[,"t.err"],delsh3[,"x.err"],line.col= cols_rdpu[6],hold_on=TRUE,line.lwd=3,deltat=0.25)
#myplot(sla1_rvsdel[,"t"],sla1_rvsdel[,"x"]-xsla1_rvsdel,sla1_rvsdel[,"t.err"],sla1_rvsdel[,"x.err"],line.col=cols_rdpu[5],hold_on=TRUE,line.lwd=3,deltat=0.25)

title("sla1 movement")


myplot(abpmch_1x_sla1_no[,"t"],abpmch_1x_sla1_no[,"n"],abpmch_1x_sla1_no[,"t.err"],abpmch_1x_sla1_no[,"n.err"],line.col="#000000",line.lwd=3,deltat=0.25,xlim=c(-15,15),ylim=c(-25,650))
myplot(abpmch_2x_sla1_no[,"t"],abpmch_2x_sla1_no[,"n"],abpmch_2x_sla1_no[,"t.err"],abpmch_2x_sla1_no[,"n.err"],line.col="#CC0066",hold_on=TRUE,line.lwd=3,deltat=0.45)
myplot(abpmch_2xBAR_sla1_no[,"t"],abpmch_2xBAR_sla1_no[,"n"],abpmch_2xBAR_sla1_no[,"t.err"],abpmch_2xBAR_sla1_no[,"n.err"],line.col="#660099",hold_on=TRUE,line.lwd=3,deltat=0.45)
myplot(abpmch_1xBAR_sla1_no[,"t"],abpmch_1xBAR_sla1_no[,"n"],abpmch_1xBAR_sla1_no[,"t.err"],abpmch_1xBAR_sla1_no[,"n.err"],line.col="#66cc99",hold_on=TRUE,line.lwd=3,deltat=0.45)
myplot(abpmch_rvsdel[,"t"],abpmch_rvsdel[,"n"],abpmch_rvsdel[,"t.err"],abpmch_rvsdel[,"n.err"],line.col="#ccddee",hold_on=TRUE,line.lwd=3,deltat=0.45)
legend("topleft",c("abp1mch 1xRvs", "abp1mch 2xRvs","abp1mch 2xBAR", "abp1mch 1xBAR", "abp1mch rvsdel"),lty=1,col=c("#000000", "#CC0066", "#660099","#66cc99","#ccddee"),bty='n', cex=0.75)
title(main="abp mch sla1 co-tag set2")

#title("abp1 fl.int")
#legend("topleft",c("sla1 1x","sla1 2x ","sla1 2xBAR", "rvsdel"),lty=1,col=c("#023858", "#CC0066", "#660099", cols_rdpu[5]),bty='n', cex=0.75)


myplot(rvsdup[,"t"],mnorm(rvsdup[,"fi"]),rvsdup[,"t.err"],rvsdup[,"fi.err"],line.col="#CC0066",line.lwd=3,deltat=0.25,xlim=c(-30,30),ylim=c(-0.1,1))
myplot(delsh3dup[,"t"],mnorm(delsh3dup[,"fi"]),delsh3dup[,"t.err"],delsh3dup[,"fi.err"],line.col="#660099",hold_on=TRUE,line.lwd=3,deltat=0.45)
myplot(sla823[,"t"],mnorm(sla823[,"fi"]),sla823[,"t.err"],sla823[,"fi.err"],line.col="#000000",hold_on=TRUE,line.lwd=3,deltat=0.45)
title("sla1 fl.int")

myplot(abpmch_1x_sla1_no[,"t"],mnorm(abpmch_1x_sla1_no[,"fi"]),abpmch_1x_sla1_no[,"t.err"],abpmch_1x_sla1_no[,"fi.err"],line.col="#000000",line.lwd=3,deltat=0.25,xlim=c(-30,30),ylim=c(-0.1,1))
myplot(sla823[,"t"],mnorm(sla823[,"fi"]),sla823[,"t.err"],sla823[,"fi.err"],line.col="#023858",hold_on=TRUE,line.lwd=3,deltat=0.45)
#myplot(sla823[,"t"],sla823[,"x"]-xsla823,sla823[,"t.err"],sla823[,"x.err"],line.col="#023858",hold_on=TRUE,line.lwd=3,deltat=0.45)
title("wt 823 intensities")
legend("topleft",c("abp", "sla1"),lty=1,col=c("#000000", "#023858"),bty='n', cex=0.75)


myplot(abpmch_1x_sla1_no[,"t"],mnorm(abpmch_1x_sla1_no[,"fi"])*180,abpmch_1x_sla1_no[,"t.err"],abpmch_1x_sla1_no[,"fi.err"],line.col="#000000",line.lwd=3,deltat=0.25,xlim=c(-30,30),ylim=c(-10,200))
#myplot(sla823[,"t"],mnorm(sla823[,"fi"]),sla823[,"t.err"],sla823[,"fi.err"],line.col="#000066",hold_on=TRUE,line.lwd=3,deltat=0.45)
myplot(sla823[,"t"],sla823[,"x"]-xsla823,sla823[,"t.err"],sla823[,"x.err"],line.col="#023858",hold_on=TRUE,line.lwd=3,deltat=0.45)
title("wt 823, abp fl.int vs sla1 movment")
legend("topleft",c("abp", "sla1"),lty=1,col=c("#000000", "#023858"),bty='n', cex=0.75)


myplot(abpmch_2x_sla1_no[,"t"],mnorm(abpmch_2x_sla1_no[,"fi"]),abpmch_2x_sla1_no[,"t.err"],abpmch_2x_sla1_no[,"fi.err"],line.col="#CC0066",line.lwd=3,deltat=0.25,xlim=c(-30,30),ylim=c(-0.1,1))
myplot(rvsdup[,"t"],mnorm(rvsdup[,"fi"]),rvsdup[,"t.err"],rvsdup[,"fi.err"],line.col="#220066",hold_on=TRUE,line.lwd=3,deltat=0.45)
title("rvs dup fl.int")
legend("topleft",c("abp", "sla1"),lty=1,col=c("#CC0066", "#220066"),bty='n', cex=0.75)

myplot(abpmch_2x_sla1_no[,"t"],mnorm(abpmch_2x_sla1_no[,"fi"])*200,abpmch_2x_sla1_no[,"t.err"],abpmch_2x_sla1_no[,"fi.err"],line.col="#CC0066",line.lwd=3,deltat=0.25,xlim=c(-30,30),ylim=c(-0.1,200))
myplot(rvsdup[,"t"],rvsdup[,"x"]-xrvsdup,rvsdup[,"t.err"],rvsdup[,"x.err"],line.col="#220066",hold_on=TRUE,line.lwd=3,deltat=0.45)
title("2x rvs")
legend("topleft",c("abp", "sla1"),lty=1,col=c("#CC0066", "#220066"),bty='n', cex=0.75)


myplot(abpmch_2xBAR_sla1_no[,"t"],mnorm(abpmch_2xBAR_sla1_no[,"fi"]),abpmch_2xBAR_sla1_no[,"t.err"],abpmch_2xBAR_sla1_no[,"fi.err"],line.col="#660099",line.lwd=3,deltat=0.25,xlim=c(-30,30),ylim=c(-0.1,1))
myplot(delsh3dup[,"t"],mnorm(delsh3dup[,"fi"]),delsh3dup[,"t.err"],delsh3dup[,"fi.err"],line.col=cols_rdpu[8],hold_on=TRUE,line.lwd=3,deltat=0.25)
title("2x bar")
legend("topleft",c("abp", "sla1"),lty=1,col=c("#CC0066", "#220066"),bty='n', cex=0.75)

myplot(abpmch_2xBAR_sla1_no[,"t"],mnorm(abpmch_2xBAR_sla1_no[,"fi"])*200,abpmch_2xBAR_sla1_no[,"t.err"],abpmch_2xBAR_sla1_no[,"fi.err"],line.col="#660099",line.lwd=3,deltat=0.25,xlim=c(-30,30),ylim=c(-0.1,200))
myplot(delsh3dup[,"t"],delsh3dup[,"x"]-xdelsh3dup,delsh3dup[,"t.err"],delsh3dup[,"x.err"],line.col=cols_rdpu[8],hold_on=TRUE,line.lwd=3,deltat=0.25)



dev.off()
