#plot the data generated by the alignment

source("/Users/deepikaa/Desktop/data_desktop/Doc/align_tracks.R")
mnorm<-function(x) return((x-min(x,na.rm=T))/(max(x,na.rm=T)-min(x,na.rm=T)))
##########haploid
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/WT/Rvs167/2017_03_29_3131/tracks.Rdata"))->WTrvs_gen3131
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/rvs_delsh3/rvs167egfp_delsh3/2016_06_02_3154_delsh3_gfp_geneva/analysis2woFlalign/tracks.Rdata"))->delsh3_g_woflalign

get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Rvsduplication/Rvs167/2017_06_19/161_d100_167d3131_5b/tracks.Rdata")) -> rvs161d_167d
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Rvsduplication/Rvs_delsh3/2017_07_21/delsh3dup/motile_wt/motile_wt.Rdata")) ->delsh3_dup_sorted

##abp1 for happloid
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/delrvs167/delrvs_abpegfp_wotreat/x0122_80ms_25p488_dualview488_1x255/tracks.Rdata"))->delrvs_abp1
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/rvs_delsh3/rvs167egfp_delsh3/2016_06_02_3154_delsh3_gfp_geneva/analysis2woFlalign/tracks.Rdata"))->delsh3_g_woflalign


##########diploid
###duplication 
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/diploid/Rvs167/2017_07_07/2832x3132/tracks.Rdata"))->WTrvs_gen3131_diploid
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/diploid/Rvs167/2017_08_18/3132x100/tracks.Rdata"))->WTrvs_gen3131x100_diploid

get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/diploid/Rvs167/2017_07_07/4dx5b/tracks.Rdata"))->rvs161d_167d_diploid
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/diploid/Rvs167/2017_07_07/529x551/motile.Rdata"))->rvs551x529_diploid
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/diploid/Rvs167/2017_07_07/7ax3131/motile.Rdata"))->rvs_mismatch7x3131_diploid


#generate a template transformation matrix to fool gen.data
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/DC/wt/Rvs167/110824_mytrasf.Rdata"))->transformation_template
transformation_template<-0*transformation_template


#output nice and usable data
## haploid
## =..alignedmovement.pdf
rvs_dup<-gen.data(rvs161d_167d,transformation_template,n=82.7 ,sn=7.5)
rvs_gen3131<-gen.data(WTrvs_gen3131,transformation_template,n=53.2,sn=5.2)

#diploid

rvs_gen3131_d<-gen.data(WTrvs_gen3131_diploid,transformation_template,n=55.9,sn=4.6)
rvs3131x100_d<-gen.data(WTrvs_gen3131x100_diploid,transformation_template,n=NA ,sn=NA)

rvs_dup_d<-gen.data(rvs161d_167d_diploid,transformation_template,n=63.7 ,sn=5.5)
rvs551x529_d<-gen.data(rvs551x529_diploid,transformation_template,n=44.8 ,sn=4.7)
rvs7x3131_d<-gen.data(rvs_mismatch7x3131_diploid,transformation_template,n=31.1 ,sn=8.6)

#rvs_gen3131<-gen.data(WTrvs_gen3131,transformation_template,n=47.0,sn=8)

#delsh3
#delsh3_sorted=delsh3 duplicate
#data for "2"
#delsh3_sorted<-gen.data(delsh3_dup_sorted,transformation_template,n=58.6 ,sn=9.3)
#delsh3_g<-gen.data(delsh3_g_woflalign,transformation_template,n=70.1,sn=6.5)
##rvs_gen3131<-gen.data(WTrvs_gen3131,transformation_template,n=67.0,sn=7.1)
#rvs_gen3131<-gen.data(WTrvs_gen3131,transformation_template,n=53.2,sn=5.2)

delsh3_sorted<-gen.data(delsh3_dup_sorted,transformation_template,n=43.6 ,sn=9.6)
delsh3_g<-gen.data(delsh3_g_woflalign,transformation_template,n=30.1,sn=9.9)

#set first time point to 0 
#t1=sla1_nice[,"t"]-sla1_nice[1,"t"]
#print("ok")
t_rvs_dup=rvs_dup[,"t"]-rvs_dup[1,"t"]
t_3131=rvs_gen3131[,"t"]-rvs_gen3131[1,"t"]

t_rvs_dup_d=rvs_dup_d[,"t"]-rvs_dup_d[1,"t"]
t_3131_d=rvs_gen3131_d[,"t"]-rvs_gen3131_d[1,"t"]
t_rvs551x529_d=rvs551x529_d[,"t"]-rvs551x529_d[1,"t"]
t_rvs7x3131_d=rvs7x3131_d[,"t"]-rvs7x3131_d[1,"t"]
t_rvs3131x100_d=rvs3131x100_d[,"t"]-rvs3131x100_d[1,"t"]

t_delsh3_sorted=delsh3_sorted[,"t"]-delsh3_sorted[1,"t"]
t_delsh3_g=delsh3_g[,"t"]-delsh3_g[1,"t"]

#set initial y position to 0
x_rvs_dup<-mean(rvs_dup[1:25,"x"])
x_3131<-mean(rvs_gen3131[1:25,"x"])

x_rvs_dup_d<-mean(rvs_dup_d[1:25,"x"])
x_3131_d<-mean(rvs_gen3131_d[1:25,"x"])
x_rvs551x529_d<-mean(rvs551x529_d[1:25,"x"])
x_rvs7x3131_d<-mean(rvs7x3131_d[1:25,"x"])
x_rvs3131x100_d<-mean(rvs3131x100_d[1:25,"x"])

x_delsh3_sorted<-mean(delsh3_sorted[1:10,"x"])
x_delsh3_g<-mean(delsh3_g[1:25,"x"])
#plot them
########################################################################################################
# ####halpoid vs diploid
# #movement
##--------------------------------------------------------------------------------------------------------
#pdf("rvs_dup_haploid3.pdf")
#myplot(t_rvs_dup,rvs_dup[,"x"]-x_rvs_dup,rvs_dup[,"t.err"],rvs_dup[,"x.err"],line.col="#00FFFF",xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-1.5,8),ylim=c(-25,150))
#myplot(t_rvs_dup_d,rvs_dup_d[,"x"]-x_rvs_dup_d,rvs_dup_d[,"t.err"],rvs_dup_d[,"x.err"],line.col="#0033CC", hold_on=TRUE, line.lwd=3, deltat=0.25)
#myplot(t_3131-0.2,rvs_gen3131[,"x"]-x_3131,rvs_gen3131[,"t.err"],rvs_gen3131[,"x.err"],line.col="#669900", hold_on=TRUE, line.lwd=3,deltat=0.25)
#myplot(t_3131_d-1.2,rvs_gen3131_d[,"x"]-x_3131_d,rvs_gen3131_d[,"t.err"],rvs_gen3131_d[,"x.err"],line.col="#006633", hold_on=TRUE, line.lwd=3,deltat=0.25)

#title(main="Rvs167-GFP", sub="time aligned to movement/int peak")
#legend("topleft",c("Rvsdup-haploid","Rvsdup-diploid","WT-haploid", "WT-diploid"),lty=1,col=c("#00FFFF","#0033CC","#669900", "#006633"),bty='n', cex=0.75)
# 
# #nomolecule numbers
#myplot(t_rvs_dup,mnorm(rvs_dup[,"fi"]),rvs_dup[,"t.err"],rvs_dup[,"fi.err"],line.col="#00FFFF",xlab="time(s)",ylab="fl.int",xlim=c(-1.5,8), ylim=c(0,1))
#myplot(t_rvs_dup_d,mnorm(rvs_dup_d[,"fi"]),rvs_dup_d[,"t.err"],rvs_dup_d[,"fi.err"],line.col="#0033CC",hold_on=TRUE)
#myplot(t_3131-0.2,mnorm(rvs_gen3131[,"fi"]),rvs_gen3131[,"t.err"],rvs_gen3131[,"fi.err"],line.col="#669900",hold_on=TRUE)
#myplot(t_3131_d-1.2,mnorm(rvs_gen3131_d[,"fi"]),rvs_gen3131_d[,"t.err"],rvs_gen3131_d[,"fi.err"],line.col="#006633",hold_on=TRUE)

#title(main="Rvs167-GFP", sub="time aligned to movement/int peak")
#legend("topleft",c("Rvsdup-haploid","Rvsdup-diploid","WT-haploid", "WT-diploid"),lty=1,col=c("#00FFFF","#0033CC","#669900", "#006633"),bty='n', cex=0.75)
# 
# #molecule numbers
#myplot(t_rvs_dup,rvs_dup[,"n"],rvs_dup[,"t.err"],rvs_dup[,"n.err"],line.col="#00FFFF",xlab="time(s)",ylab="# molecules",xlim=c(-1.5,8), ylim=c(0,200))
#myplot(t_rvs_dup_d,rvs_dup_d[,"n"],rvs_dup_d[,"t.err"],rvs_dup_d[,"n.err"],line.col="#0033CC",hold_on=TRUE)
#myplot(t_3131-0.2,rvs_gen3131[,"n"],rvs_gen3131[,"t.err"],rvs_gen3131[,"n.err"],line.col="#669900",hold_on=TRUE)
#myplot(t_3131_d-1.2,rvs_gen3131_d[,"n"],rvs_gen3131_d[,"t.err"],rvs_gen3131_d[,"n.err"],line.col="#006633",hold_on=TRUE)
#myplot(t_delsh3_sorted-0.9,delsh3_sorted[,"n"],delsh3_sorted[,"t.err"],delsh3_sorted[,"n.err"],line.col="#FF6600",hold_on=TRUE)
#myplot(t_delsh3_g-2.2,delsh3_g[,"n"],delsh3_g[,"t.err"],delsh3_g[,"n.err"],line.col="#996600",hold_on=TRUE)

#title(main="Rvs167-GFP", sub="time aligned to movement/int peak")
#legend("topleft",c("Rvsdup-haploid","Rvs", "delsh3dup","delsh3"),lty=1,col=c("#00FFFF","#669900", "#FF6600","#996600"),bty='n', cex=0.75)
#dev.off()
##--------------------------------------------------------------------------------------------------------
########################################################################################################
#######only diploids
# pdf("rvs_diploid2.pdf")
# myplot(t_rvs_dup,rvs_dup[,"x"]-x_rvs_dup,rvs_dup[,"t.err"],rvs_dup[,"x.err"],line.col="#00FFFF",xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-2,8),ylim=c(-25,150))
# myplot(t_rvs_dup_d,rvs_dup_d[,"x"]-x_rvs_dup_d,rvs_dup_d[,"t.err"],rvs_dup_d[,"x.err"],line.col="#0033CC", hold_on=TRUE, line.lwd=3, deltat=0.25)
# myplot(t_3131,rvs_gen3131[,"x"]-x_3131,rvs_gen3131[,"t.err"],rvs_gen3131[,"x.err"],line.col="#669900", hold_on=TRUE, line.lwd=3,deltat=0.25)
# myplot(t_3131_d-1,rvs_gen3131_d[,"x"]-x_3131_d,rvs_gen3131_d[,"t.err"],rvs_gen3131_d[,"x.err"],line.col="#006633", hold_on=TRUE, line.lwd=3,deltat=0.25)
# myplot(t_rvs551x529_d-1.8,rvs551x529_d[,"x"]-x_rvs551x529_d,rvs551x529_d[,"t.err"],rvs551x529_d[,"x.err"],line.col="#660033", hold_on=TRUE, line.lwd=3,deltat=0.25)
# title(main="Rvs167-GFP", sub="time aligned to intensity peak")
# legend("topleft",c("Rvsdup-haploid","Rvsdup-diploid","WT-haploid", "WT-diploid", "551x529 diploid"),lty=1,col=c("#00FFFF","#0033CC","#669900", "#006633", "#660033"),bty='n', cex=0.75)
# 
# #molecule numbers
# #myplot(t_rvs_bbcd-0.7,mnorm(rvs_bbcd[,"fi"]),rvs_bbcd[,"t.err"],rvs_bbcd[,"fi.err"],line.col="#CC6600",hold_on=TRUE)
# 
# myplot(t_rvs_dup,mnorm(rvs_dup[,"fi"]),rvs_dup[,"t.err"],rvs_dup[,"fi.err"],line.col="#00FFFF",xlab="time(s)",ylab="# molecules",xlim=c(-2,8), ylim=c(0,1))
# myplot(t_rvs_dup_d,mnorm(rvs_dup_d[,"fi"]),rvs_dup_d[,"t.err"],rvs_dup_d[,"fi.err"],line.col="#0033CC",hold_on=TRUE)
# myplot(t_3131,mnorm(rvs_gen3131[,"fi"]),rvs_gen3131[,"t.err"],rvs_gen3131[,"fi.err"],line.col="#669900",hold_on=TRUE)
# myplot(t_3131_d-1,mnorm(rvs_gen3131_d[,"fi"]),rvs_gen3131_d[,"t.err"],rvs_gen3131_d[,"fi.err"],line.col="#006633",hold_on=TRUE)
# myplot(t_rvs551x529_d-1.8,mnorm(rvs551x529_d[,"fi"]),rvs551x529_d[,"t.err"],rvs551x529_d[,"fi.err"],line.col="#660033",hold_on=TRUE)
# title(main="Rvs167-GFP", sub="time aligned to intensity peak")
# legend("topleft",c("Rvsdup-haploid","Rvsdup-diploid","WT-haploid", "WT-diploid", "551x529 diploid"),lty=1,col=c("#00FFFF","#0033CC","#669900", "#006633", "#660033"),bty='n', cex=0.75)
#dev.off()
########################################################################################################
# #######only diploids, incl 7x3131
#pdf("rvs_onlydiploid_incl7x3131_3131x100_3.pdf")
#myplot(t_rvs_dup_d,rvs_dup_d[,"x"]-x_rvs_dup_d,rvs_dup_d[,"t.err"],rvs_dup_d[,"x.err"],line.col="#000000",xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-2,8),ylim=c(-25,150))
#myplot(t_3131_d-1.2,rvs_gen3131_d[,"x"]-x_3131_d,rvs_gen3131_d[,"t.err"],rvs_gen3131_d[,"x.err"],line.col="#006633", hold_on=TRUE, line.lwd=3,deltat=0.25)
#myplot(t_rvs551x529_d-1.8,rvs551x529_d[,"x"]-x_rvs551x529_d,rvs551x529_d[,"t.err"],rvs551x529_d[,"x.err"],line.col="#660033", hold_on=TRUE, line.lwd=3,deltat=0.25)
#myplot(t_rvs7x3131_d,rvs7x3131_d[,"x"]-x_rvs7x3131_d,rvs7x3131_d[,"t.err"],rvs7x3131_d[,"x.err"],line.col="#CC00FF", hold_on=TRUE, line.lwd=3,deltat=0.25)
#myplot(t_rvs3131x100_d,rvs3131x100_d[,"x"]-x_rvs3131x100_d,rvs3131x100_d[,"t.err"],rvs3131x100_d[,"x.err"],line.col="#FF3399", hold_on=TRUE, line.lwd=3,deltat=0.25)

#myplot(t_3131_d-1.2,rvs_gen3131_d[,"x"]-x_3131_d,rvs_gen3131_d[,"t.err"],rvs_gen3131_d[,"x.err"],line.col="#006633", xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-2,8),ylim=c(-25,150))
#myplot(t_rvs3131x100_d,rvs3131x100_d[,"x"]-x_rvs3131x100_d,rvs3131x100_d[,"t.err"],rvs3131x100_d[,"x.err"],line.col="#FF3399", hold_on=TRUE, line.lwd=3,deltat=0.25)
#myplot(t_3131-0.2,rvs_gen3131[,"x"]-x_3131,rvs_gen3131[,"t.err"],rvs_gen3131[,"x.err"],line.col="#669900", hold_on=TRUE, line.lwd=3,deltat=0.25)

#title(main="Rvs167-GFP", sub="time aligned to intensity peak")
#legend("topleft",c("Rvsdup-diploid", "WT-diploid", "551x529 diploid motile", "7x3131 diploid motile", "3131x100 diploid"),lty=1,col=c("#0033CC", "#006633", "#660033", "#CC00FF", "#FF3399"),bty='n', cex=0.75)
# 
# #molecule numbers
#myplot(t_rvs_dup_d,mnorm(rvs_dup_d[,"fi"]),rvs_dup_d[,"t.err"],rvs_dup_d[,"fi.err"],line.col="#0033CC",xlab="time(s)",ylab="# molecules",xlim=c(-2,8), ylim=c(0,1))
#myplot(t_3131_d-1.2,mnorm(rvs_gen3131_d[,"fi"]),rvs_gen3131_d[,"t.err"],rvs_gen3131_d[,"fi.err"],line.col="#006633",hold_on=TRUE)
#myplot(t_rvs551x529_d-1.8,mnorm(rvs551x529_d[,"fi"]),rvs551x529_d[,"t.err"],rvs551x529_d[,"fi.err"],line.col="#660033",hold_on=TRUE)
#myplot(t_rvs7x3131_d,mnorm(rvs7x3131_d[,"fi"]),rvs7x3131_d[,"t.err"],rvs7x3131_d[,"fi.err"],line.col="#CC00FF",hold_on=TRUE)
#myplot(t_rvs3131x100_d,mnorm(rvs3131x100_d[,"fi"]),rvs3131x100_d[,"t.err"],rvs3131x100_d[,"fi.err"],line.col="#FF3399",hold_on=TRUE)

#myplot(t_3131_d-1.2,mnorm(rvs_gen3131_d[,"fi"]),rvs_gen3131_d[,"t.err"],rvs_gen3131_d[,"fi.err"],line.col="#006633",xlab="time(s)",ylab="# molecules",xlim=c(-2,8), ylim=c(0,1))
#myplot(t_rvs3131x100_d,mnorm(rvs3131x100_d[,"fi"]),rvs3131x100_d[,"t.err"],rvs3131x100_d[,"fi.err"],line.col="#FF3399",hold_on=TRUE)
#myplot(t_3131-0.2,mnorm(rvs_gen3131[,"fi"]),rvs_gen3131[,"t.err"],rvs_gen3131[,"fi.err"],line.col="#669900",hold_on=TRUE)

# 
#title(main="Rvs167-GFP", sub="time aligned to intensity peak")
#legend("topleft",c("Rvsdup-diploid", "WT-diploid", "551x529 diploid motile", "7x3131 diploid motile", "3131x100 diploid"),lty=1,col=c("#0033CC", "#006633", "#660033", "#CC00FF", "#FF3399"),bty='n', cex=0.75)
#dev.off()

########################################################################################################
#with molecule numbers
#pdf("rvs_diploid_molecnum3.pdf")
#myplot(t_rvs_dup_d,rvs_dup_d[,"x"]-x_rvs_dup_d,rvs_dup_d[,"t.err"],rvs_dup_d[,"x.err"],line.col="#0033CC",xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-2,8),ylim=c(-25,150))
#myplot(t_3131_d-1.2,rvs_gen3131_d[,"x"]-x_3131_d,rvs_gen3131_d[,"t.err"],rvs_gen3131_d[,"x.err"],line.col="#006633", hold_on=TRUE, line.lwd=3,deltat=0.25)
#myplot(t_rvs551x529_d-1.9,rvs551x529_d[,"x"]-x_rvs551x529_d,rvs551x529_d[,"t.err"],rvs551x529_d[,"x.err"],line.col="#660033", hold_on=TRUE, line.lwd=3,deltat=0.25)
#myplot(t_3131-0.2,rvs_gen3131[,"x"]-x_3131,rvs_gen3131[,"t.err"],rvs_gen3131[,"x.err"],line.col="#669900", hold_on=TRUE, line.lwd=3,deltat=0.25)
#
#
#title(main="Rvs167-GFP", sub="time aligned to intensity peak")
# legend("topleft",c("Rvs161/167dup-diploid", "WT-diploid", "551x529 diploid motile", "WT-haploid"),lty=1,col=c("#0033CC", "#006633", "#660033", "#669900"),bty='n', cex=0.75)
#legend("topleft",c("4x Rvs diploid", "2x Rvs diploid", "1x Rvs diploid", "1x Rvs haploid"),lty=1,col=c("#0033CC", "#006633", "#660033", "#669900"),bty='n', cex=0.75)

# #molecule numbers
# #
#myplot(t_rvs_dup_d,rvs_dup_d[,"n"],rvs_dup_d[,"t.err"],rvs_dup_d[,"n.err"],line.col="#0033CC",xlab="time(s)",ylab="# molecules",xlim=c(-2,8), ylim=c(0,150))
#myplot(t_3131_d-1.2,rvs_gen3131_d[,"n"],rvs_gen3131_d[,"t.err"],rvs_gen3131_d[,"n.err"],line.col="#006633",hold_on=TRUE)
#myplot(t_rvs551x529_d-1.9,rvs551x529_d[,"n"],rvs551x529_d[,"t.err"],rvs551x529_d[,"n.err"],line.col="#660033",hold_on=TRUE)
#myplot(t_3131-0.2,rvs_gen3131[,"n"],rvs_gen3131[,"t.err"],rvs_gen3131[,"n.err"],line.col="#669900",hold_on=TRUE)
# # myplot(t_rvs7x3131_d,rvs7x3131_d[,"n"],rvs7x3131_d[,"t.err"],rvs7x3131_d[,"n.err"],line.col="#CC00FF",hold_on=TRUE)
#
#title(main="Rvs167-GFP", sub="time aligned to intensity peak")
# legend("topleft",c("Rvs161/167dup-diploid", "WT-diploid", "551x529 diploid motile", "WT-haploid"),lty=1,col=c("#0033CC", "#006633", "#660033", "#669900"),bty='n', cex=0.75)
#legend("topleft",c("4x Rvs diploid", "2x Rvs diploid", "1x Rvs diploid", "1x Rvs haploid"),lty=1,col=c("#0033CC", "#006633", "#660033", "#669900"),bty='n', cex=0.75)

# 
#dev.off()
########################################################################################################
##with delsh3-duplicated
pdf("rvs_all_haploid.pdf")
myplot(t_rvs_dup_d,rvs_dup_d[,"x"]-x_rvs_dup_d,rvs_dup_d[,"t.err"],rvs_dup_d[,"x.err"],line.col="#000000",xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-2,8),ylim=c(-25,150))
myplot(t_rvs_dup,rvs_dup[,"x"]-x_rvs_dup,rvs_dup[,"t.err"],rvs_dup[,"x.err"],line.col="#00FFFF", hold_on=TRUE, line.lwd=3,deltat=0.25)
#myplot(t_rvs551x529_d-1.9,rvs551x529_d[,"x"]-x_rvs551x529_d,rvs551x529_d[,"t.err"],rvs551x529_d[,"x.err"],line.col="#660033", hold_on=TRUE, line.lwd=3,deltat=0.25)

myplot(t_3131,rvs_gen3131[,"x"]-x_3131,rvs_gen3131[,"t.err"],rvs_gen3131[,"x.err"],line.col="#669900", hold_on=TRUE, line.lwd=3,deltat=0.25)
myplot(t_delsh3_sorted,delsh3_sorted[,"x"]-x_delsh3_sorted,delsh3_sorted[,"t.err"],delsh3_sorted[,"x.err"],line.col="#FF6600", hold_on=TRUE, line.lwd=3,deltat=0.25)
myplot(t_delsh3_g,delsh3_g[,"x"]-x_delsh3_g,delsh3_g[,"t.err"],delsh3_g[,"x.err"],line.col="#996600", hold_on=TRUE, line.lwd=3,deltat=0.25)

#title(main="Rvs167-GFP", sub="time aligned to inward movment")
#legend("topleft",c("Rvs167/161 dup diploid: 4x Rvs","2832x3131: 2x Rvs","551x529: 1x Rvs","Rvs167/161 dup haploid",  "WT Rvs-Gen3131", "Rvs167delsh3 dup", "Rvsdelsh3"),lty=1,col=c("#0033CC", "#006633", "#660033", "#00FFFF","#669900", "#FF6600","#996600" ),bty='n', cex=0.75)


myplot(t_rvs_dup,rvs_dup[,"n"],rvs_dup[,"t.err"],rvs_dup[,"n.err"],line.col="#000000",xlab="time(s)",ylab="# molecules",xlim=c(-1.5,8), ylim=c(0,200))
myplot(t_rvs_dup_d,rvs_dup_d[,"n"],rvs_dup_d[,"t.err"],rvs_dup_d[,"n.err"],line.col="#0033CC",hold_on=TRUE)
#myplot(t_rvs551x529_d-1.8,rvs551x529_d[,"n"],rvs551x529_d[,"t.err"],rvs551x529_d[,"n.err"],line.col="#660033",hold_on=TRUE)

myplot(t_3131,rvs_gen3131[,"n"],rvs_gen3131[,"t.err"],rvs_gen3131[,"n.err"],line.col="#669900",hold_on=TRUE)
myplot(t_delsh3_sorted,delsh3_sorted[,"n"],delsh3_sorted[,"t.err"],delsh3_sorted[,"n.err"],line.col="#FF6600",hold_on=TRUE)
myplot(t_delsh3_g,delsh3_g[,"n"],delsh3_g[,"t.err"],delsh3_g[,"n.err"],line.col="#996600",hold_on=TRUE)

title(main="Rvs167-GFP", sub="time aligned to inward movment")
legend("topleft",c("Rvs167/161 dup diploid: 4x Rvs","2832x3131: 2x Rvs","551x529: 1x Rvs","Rvs167/161 dup haploid",  "WT Rvs-Gen3131", "Rvs167delsh3 dup", "Rvsdelsh3"),lty=1,col=c("#0033CC", "#006633", "#660033", "#00FFFF","#669900", "#FF6600","#996600" ),bty='n', cex=0.75)
dev.off()

########################################################################################################
pdf("rvs_delsh3_vs559_3.pdf")
myplot(t_rvs_dup_d,rvs_dup_d[,"x"]-x_rvs_dup_d,rvs_dup_d[,"t.err"],rvs_dup_d[,"x.err"],line.col="#FFFFFF",xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-2,8),ylim=c(-25,150))
myplot(t_rvs551x529_d-1.9,rvs551x529_d[,"x"]-x_rvs551x529_d,rvs551x529_d[,"t.err"],rvs551x529_d[,"x.err"],line.col="#660033", hold_on=TRUE, line.lwd=3,deltat=0.25)
#myplot(t_3131_d-1.2,rvs_gen3131_d[,"x"]-x_3131_d,rvs_gen3131_d[,"t.err"],rvs_gen3131_d[,"x.err"],line.col="#006633", hold_on=TRUE, line.lwd=3,deltat=0.25)
#myplot(t_rvs_dup-0.4,rvs_dup[,"x"]-x_rvs_dup,rvs_dup[,"t.err"],rvs_dup[,"x.err"],line.col="#00FFFF", hold_on=TRUE, line.lwd=3,deltat=0.25)
#myplot(t_3131-0.2,rvs_gen3131[,"x"]-x_3131,rvs_gen3131[,"t.err"],rvs_gen3131[,"x.err"],line.col="#669900", hold_on=TRUE, line.lwd=3,deltat=0.25)
#myplot(t_delsh3_sorted-0.9,delsh3_sorted[,"x"]-x_delsh3_sorted,delsh3_sorted[,"t.err"],delsh3_sorted[,"x.err"],line.col="#FF6600", hold_on=TRUE, line.lwd=3,deltat=0.25)
myplot(t_delsh3_g-2.2,delsh3_g[,"x"]-x_delsh3_g,delsh3_g[,"t.err"],delsh3_g[,"x.err"],line.col="#996600", hold_on=TRUE, line.lwd=3,deltat=0.25)
title(main="Rvs167-GFP", sub="time aligned to inward movment")
legend("topleft",c("Rvs167/161 dup diploid: 4x Rvs","2832x3131: 2x Rvs","551x529: 1x Rvs","Rvs167/161 dup haploid",  "WT Rvs-Gen3131", "Rvs167delsh3 dup", "Rvsdelsh3"),lty=1,col=c("#0033CC", "#006633", "#660033", "#00FFFF","#669900", "#FF6600","#996600" ),bty='n', cex=0.75)

myplot(t_rvs_dup-0.4,mnorm(rvs_dup[,"fi"]),rvs_dup[,"t.err"],rvs_dup[,"fi.err"],line.col="#FFFFFF",xlab="time(s)",ylab="# molecules",xlim=c(-1.5,8), ylim=c(0,1))
#myplot(t_rvs_dup_d,mnorm(rvs_dup_d[,"fi"]),rvs_dup_d[,"t.err"],rvs_dup_d[,"fi.err"],line.col="#0033CC",hold_on=TRUE)
myplot(t_rvs551x529_d-1.8,mnorm(rvs551x529_d[,"fi"]),rvs551x529_d[,"t.err"],rvs551x529_d[,"fi.err"],line.col="#660033",hold_on=TRUE)
#myplot(t_3131_d-1.2,mnorm(rvs_gen3131_d[,"fi"]),rvs_gen3131_d[,"t.err"],rvs_gen3131_d[,"fi.err"],line.col="#006633",hold_on=TRUE)

#myplot(t_3131-0.2,mnorm(rvs_gen3131[,"fi"]),rvs_gen3131[,"t.err"],rvs_gen3131[,"fi.err"],line.col="#669900",hold_on=TRUE)
#myplot(t_delsh3_sorted-0.9,mnorm(delsh3_sorted[,"fi"]),delsh3_sorted[,"t.err"],delsh3_sorted[,"fi.err"],line.col="#FF6600",hold_on=TRUE)
myplot(t_delsh3_g-2.2,mnorm(delsh3_g[,"fi"]),delsh3_g[,"t.err"],delsh3_g[,"fi.err"],line.col="#996600",hold_on=TRUE)

title(main="Rvs167-GFP", sub="time aligned to inward movment")
legend("topleft",c("Rvs167/161 dup diploid: 4x Rvs","2832x3131: 2x Rvs","551x529: 1x Rvs","Rvs167/161 dup haploid",  "WT Rvs-Gen3131", "Rvs167delsh3 dup", "Rvsdelsh3"),lty=1,col=c("#0033CC", "#006633", "#660033", "#00FFFF","#669900", "#FF6600","#996600" ),bty='n', cex=0.75)

dev.off()
########################################################################################################
# pdf("rvs_allwomole2.pdf")
# myplot(t_rvs_dup_d,rvs_dup_d[,"x"]-x_rvs_dup_d,rvs_dup_d[,"t.err"],rvs_dup_d[,"x.err"],line.col="#0033CC",xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-2,8),ylim=c(-25,150))
# myplot(t_rvs551x529_d-1.9,rvs551x529_d[,"x"]-x_rvs551x529_d,rvs551x529_d[,"t.err"],rvs551x529_d[,"x.err"],line.col="#660033", hold_on=TRUE, line.lwd=3,deltat=0.25)
# myplot(t_3131_d-1.2,rvs_gen3131_d[,"x"]-x_3131_d,rvs_gen3131_d[,"t.err"],rvs_gen3131_d[,"x.err"],line.col="#006633", hold_on=TRUE, line.lwd=3,deltat=0.25)
# myplot(t_rvs_dup-0.4,rvs_dup[,"x"]-x_rvs_dup,rvs_dup[,"t.err"],rvs_dup[,"x.err"],line.col="#00FFFF", hold_on=TRUE, line.lwd=3,deltat=0.25)
# myplot(t_3131-0.2,rvs_gen3131[,"x"]-x_3131,rvs_gen3131[,"t.err"],rvs_gen3131[,"x.err"],line.col="#669900", hold_on=TRUE, line.lwd=3,deltat=0.25)
# myplot(t_delsh3_sorted-0.9,delsh3_sorted[,"x"]-x_delsh3_sorted,delsh3_sorted[,"t.err"],delsh3_sorted[,"x.err"],line.col="#FF6600", hold_on=TRUE, line.lwd=3,deltat=0.25)
# myplot(t_delsh3_g-2.2,delsh3_g[,"x"]-x_delsh3_g,delsh3_g[,"t.err"],delsh3_g[,"x.err"],line.col="#996600", hold_on=TRUE, line.lwd=3,deltat=0.25)
# title(main="Rvs167-GFP", sub="time aligned to inward movment")
# legend("topleft",c("Rvs167/161 dup diploid: 4x Rvs","2832x3131: 2x Rvs","551x529: 1x Rvs","Rvs167/161 dup haploid",  "WT Rvs-Gen3131", "Rvs167delsh3 dup", "Rvsdelsh3"),lty=1,col=c("#0033CC", "#006633", "#660033", "#00FFFF","#669900", "#FF6600","#996600" ),bty='n', cex=0.75)
# 
# myplot(t_rvs_dup-0.4,mnorm(rvs_dup[,"fi"]),rvs_dup[,"t.err"],rvs_dup[,"fi.err"],line.col="#00FFFF",xlab="time(s)",ylab="# molecules",xlim=c(-1.5,8), ylim=c(0,1))
# myplot(t_rvs_dup_d,mnorm(rvs_dup_d[,"fi"]),rvs_dup_d[,"t.err"],rvs_dup_d[,"fi.err"],line.col="#0033CC",hold_on=TRUE)
# myplot(t_rvs551x529_d-1.8,mnorm(rvs551x529_d[,"fi"]),rvs551x529_d[,"t.err"],rvs551x529_d[,"fi.err"],line.col="#660033",hold_on=TRUE)
# myplot(t_3131_d-1.2,mnorm(rvs_gen3131_d[,"fi"]),rvs_gen3131_d[,"t.err"],rvs_gen3131_d[,"fi.err"],line.col="#006633",hold_on=TRUE)
# 
# myplot(t_3131-0.2,mnorm(rvs_gen3131[,"fi"]),rvs_gen3131[,"t.err"],rvs_gen3131[,"fi.err"],line.col="#669900",hold_on=TRUE)
# myplot(t_delsh3_sorted-0.9,mnorm(delsh3_sorted[,"fi"]),delsh3_sorted[,"t.err"],delsh3_sorted[,"fi.err"],line.col="#FF6600",hold_on=TRUE)
# myplot(t_delsh3_g-2.2,mnorm(delsh3_g[,"fi"]),delsh3_g[,"t.err"],delsh3_g[,"fi.err"],line.col="#996600",hold_on=TRUE)
# 
# title(main="Rvs167-GFP", sub="time aligned to inward movment")
# legend("topleft",c("Rvs167/161 dup diploid: 4x Rvs","2832x3131: 2x Rvs","551x529: 1x Rvs","Rvs167/161 dup haploid",  "WT Rvs-Gen3131", "Rvs167delsh3 dup", "Rvsdelsh3"),lty=1,col=c("#0033CC", "#006633", "#660033", "#00FFFF","#669900", "#FF6600","#996600" ),bty='n', cex=0.75)


#pdf("rvs_haploiddup_vsdelsh3dup3.pdf")
#myplot(t_rvs_dup_d,rvs_dup_d[,"x"]-x_rvs_dup_d,rvs_dup_d[,"t.err"],rvs_dup_d[,"x.err"],line.col="#0033CC",xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-2,8),ylim=c(-25,150))
##myplot(t_rvs551x529_d-1.9,rvs551x529_d[,"x"]-x_rvs551x529_d,rvs551x529_d[,"t.err"],rvs551x529_d[,"x.err"],line.col="#660033", hold_on=TRUE, line.lwd=3,deltat=0.25)
#myplot(t_3131_d-1.2,rvs_gen3131_d[,"x"]-x_3131_d,rvs_gen3131_d[,"t.err"],rvs_gen3131_d[,"x.err"],line.col="#006633", hold_on=TRUE, line.lwd=3,deltat=0.25)
#myplot(t_rvs_dup-0.4,rvs_dup[,"x"]-x_rvs_dup,rvs_dup[,"t.err"],rvs_dup[,"x.err"],line.col="#00FFFF", hold_on=TRUE, line.lwd=3,deltat=0.25)
#myplot(t_3131-0.2,rvs_gen3131[,"x"]-x_3131,rvs_gen3131[,"t.err"],rvs_gen3131[,"x.err"],line.col="#669900", hold_on=TRUE, line.lwd=3,deltat=0.25)
#myplot(t_delsh3_sorted-0.9,delsh3_sorted[,"x"]-x_delsh3_sorted,delsh3_sorted[,"t.err"],delsh3_sorted[,"x.err"],line.col="#FF6600", hold_on=TRUE, line.lwd=3,deltat=0.25)
#myplot(t_delsh3_g-2.2,delsh3_g[,"x"]-x_delsh3_g,delsh3_g[,"t.err"],delsh3_g[,"x.err"],line.col="#996600", hold_on=TRUE, line.lwd=3,deltat=0.25)
#title(main="Rvs167-GFP", sub="time aligned to inward movment")
#legend("topleft",c("Rvs167/161 dup diploid: 4x Rvs","2832x3131: 2x Rvs","551x529: 1x Rvs","Rvs167/161 dup haploid",  "WT Rvs-Gen3131", "Rvs167delsh3 dup", "Rvsdelsh3"),lty=1,col=c("#0033CC", "#006633", "#660033", "#00FFFF","#669900", "#FF6600","#996600" ),bty='n', cex=0.75)
##########
# myplot(t_rvs_dup-0.4,mnorm(rvs_dup[,"fi"]),rvs_dup[,"t.err"],rvs_dup[,"fi.err"],line.col="#00FFFF",xlab="time(s)",ylab="# molecules",xlim=c(-1.5,8), ylim=c(0,1))
# myplot(t_rvs_dup_d,mnorm(rvs_dup_d[,"fi"]),rvs_dup_d[,"t.err"],rvs_dup_d[,"fi.err"],line.col="#0033CC",hold_on=TRUE)
# #myplot(t_rvs551x529_d-1.8,mnorm(rvs551x529_d[,"fi"]),rvs551x529_d[,"t.err"],rvs551x529_d[,"fi.err"],line.col="#660033",hold_on=TRUE)
# #myplot(t_3131_d-1.2,mnorm(rvs_gen3131_d[,"fi"]),rvs_gen3131_d[,"t.err"],rvs_gen3131_d[,"fi.err"],line.col="#006633",hold_on=TRUE)
# 
# myplot(t_3131-0.2,mnorm(rvs_gen3131[,"fi"]),rvs_gen3131[,"t.err"],rvs_gen3131[,"fi.err"],line.col="#669900",hold_on=TRUE)
# myplot(t_delsh3_sorted-0.9,mnorm(delsh3_sorted[,"fi"]),delsh3_sorted[,"t.err"],delsh3_sorted[,"fi.err"],line.col="#FF6600",hold_on=TRUE)
# #myplot(t_delsh3_g-2.2,mnorm(delsh3_g[,"fi"]),delsh3_g[,"t.err"],delsh3_g[,"fi.err"],line.col="#996600",hold_on=TRUE)
############
#myplot(t_3131+0.6,rvs_gen3131[,"n"],rvs_gen3131[,"t.err"],rvs_gen3131[,"n.err"],line.col="#009933",hold_on=TRUE)
#
#myplot(t_rvs_dup_d,rvs_dup_d[,"n"],rvs_dup_d[,"t.err"],rvs_dup_d[,"n.err"],line.col="#0033CC",xlab="time(s)",ylab="# molecules",xlim=c(-2,8), ylim=c(0,250))
#myplot(t_3131_d-1.2,rvs_gen3131_d[,"n"],rvs_gen3131_d[,"t.err"],rvs_gen3131_d[,"n.err"],line.col="#006633",hold_on=TRUE)
#myplot(t_rvs551x529_d-1.9,rvs551x529_d[,"n"],rvs551x529_d[,"t.err"],rvs551x529_d[,"n.err"],line.col="#660033",hold_on=TRUE)
#myplot(t_3131-0.2,rvs_gen3131[,"n"],rvs_gen3131[,"t.err"],rvs_gen3131[,"n.err"],line.col="#669900",hold_on=TRUE)
#myplot(t_delsh3_sorted-0.9,delsh3_sorted[,"n"],delsh3_sorted[,"t.err"],delsh3_sorted[,"n.err"],line.col="#FF6600",hold_on=TRUE)
#myplot(t_rvs_dup-0.4,rvs_dup[,"n"],rvs_dup[,"t.err"],rvs_dup[,"n.err"],line.col="#00FFFF",hold_on=TRUE)

# myplot(t_rvs7x3131_d,rvs7x3131_d[,"n"],rvs7x3131_d[,"t.err"],rvs7x3131_d[,"n.err"],line.col="#CC00FF",hold_on=TRUE)

#title(main="Rvs167-GFP", sub="time aligned to inward movment")
#legend("topleft",c("Rvs167/161 dup diploid: 4x Rvs","2832x3131: 2x Rvs","551x529: 1x Rvs","Rvs167/161 dup haploid",  "WT Rvs-Gen3131", "Rvs167delsh3 dup", "Rvsdelsh3"),lty=1,col=c("#0033CC", "#006633", "#660033", "#00FFFF","#669900", "#FF6600","#996600" ),bty='n', cex=0.75)

#dev.off()
########################################################################################################
##with delsh3-duplicated
pdf("rvs_delsh3_duplicate_alignedRvspeak.pdf")
myplot(t_rvs_dup_d,rvs_dup_d[,"x"]-x_rvs_dup_d,rvs_dup_d[,"t.err"],rvs_dup_d[,"x.err"],line.col="#FFFFFF",xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-2,8),ylim=c(-25,150))
myplot(t_rvs_dup,rvs_dup[,"x"]-x_rvs_dup,rvs_dup[,"t.err"],rvs_dup[,"x.err"],line.col="#00FFFF", hold_on=TRUE, line.lwd=3,deltat=0.25)
myplot(t_3131-0.3,rvs_gen3131[,"x"]-x_3131,rvs_gen3131[,"t.err"],rvs_gen3131[,"x.err"],line.col="#669900", hold_on=TRUE, line.lwd=3,deltat=0.25)
myplot(t_delsh3_sorted-1.2,delsh3_sorted[,"x"]-x_delsh3_sorted,delsh3_sorted[,"t.err"],delsh3_sorted[,"x.err"],line.col="#FF6600", hold_on=TRUE, line.lwd=3,deltat=0.25)
title(main="Rvs167-GFP", sub="time aligned to inward movment")
legend("topleft",c("Rvs167/161 dup diploid", "Rvs167/161 dup", "WT Rvs-Gen3131", "Rvs167delsh3 dup"),lty=1,col=c("#0033CC", "#00FFFF", "#669900", "#FF9900"),bty='n', cex=0.75)

myplot(t_rvs_dup,rvs_dup[,"n"],rvs_dup[,"t.err"],rvs_dup[,"n.err"],line.col="#00FFFF",xlab="time(s)",ylab="# molecules",xlim=c(-1.5,8), ylim=c(0,200))
myplot(t_rvs_dup_d,rvs_dup_d[,"n"],rvs_dup_d[,"t.err"],rvs_dup_d[,"n.err"],line.col="#FFFFFF",hold_on=TRUE)
myplot(t_3131-0.3,rvs_gen3131[,"n"],rvs_gen3131[,"t.err"],rvs_gen3131[,"n.err"],line.col="#669900",hold_on=TRUE)
myplot(t_delsh3_sorted-1.2,delsh3_sorted[,"n"],delsh3_sorted[,"t.err"],delsh3_sorted[,"n.err"],line.col="#FF6600",hold_on=TRUE)
title(main="Rvs167-GFP", sub="time aligned to inward movment")
legend("topleft",c("Rvs167/161 dup diploid", "Rvs167/161 dup", "WT Rvs-Gen3131", "Rvs167delsh3 dup"),lty=1,col=c("#0033CC", "#00FFFF", "#669900", "#FF9900"),bty='n', cex=0.75)

dev.off()