##Sla1 and sla1_delrvs movement with and without sorbitol
#plot the data generated by the alignment
############################################################################################################
###########################load data
source("/Users/deepikaa/Desktop/data_desktop/Doc/align_tracks.R")

library(Hmisc)
##Wt data
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/WT/sla1egfp/2016_06_01_141_geneva/mw120/tracks.Rdata"))->WTsla1
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/WT/Inp52gfp/2017_03_13/tracks.Rdata"))->WTinp52
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/WT/Rvs167/2016_06_02_2832_geneva/tracks.Rdata")) -> WTrvs
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/WT/Abp1/2017_04_10_123/tracks.Rdata")) -> WTabp1

##delsh3
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/rvs_delsh3/rvs167_delsh3_sla1_egfp/2015_04_02/tracks.Rdata"))-> delsh3_sla1
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/rvs_delsh3/delsh3_abp_egfp/2014_12_01/tracks.Rdata"))->delsh3_abp
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/rvs_delsh3/rvs167egfp_delsh3/2016_06_02_3154_delsh3_gfp_geneva/analysis2woFlalign/tracks.Rdata"))->delsh3_g_woflalign

get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/rvs_delsh3/rvs167egfp_delsh3/2014_07_14_rvs167egfp_delsh3_highmag/se2/first_analysis/tracks.Rdata"))->delsh3_g_woflalign
############################################################################################################
###########################get rotation matrix from DC alignments
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/DC/wt/sla10822/aligment_DMabpDC/alignment_GenSla1_wGenabp/sla1wt_141gen_abpegfp_mytrasf.Rdata"))->sla1_transf
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/DC/wt/inp52GFP_abpmCH/abp_inp52swt_abpegfp_mytrasf.Rdata"))->inp52_trasf
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/DC/wt/Rvs167/2017_04_06_3131/test_mytrasf.Rdata"))->rvs_trasf

#delsh3
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/DC/delsh3/2016_06_01_delsh3_sla1GFP_abpMch_geneva/sla1_delsh3_26_07_2017_mytrasf.Rdata"))->delsh3_sla1_transf
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/DC/delsh3/2016_06_01_delsh3_sla1GFP_abpMch_geneva/sla1_delsh3_26_07_2017_aligned_toAbpdelsh3_mytrasf.Rdata"))->delsh3_sla1_transf
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/DC/delsh3/2016_06_01_delsh3_sla1GFP_abpMch_geneva/sla1_delsh3_2018_mytrasf.Rdata"))->delsh3_sla1_transf


#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/DC/delsh3/delsh3_rvsegfp_abpmcherry_T1/alignment_2017_07_26/delsh3_gfp_todelsh3abp_mytrasf.Rdata"))->delsh3_transf
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/DC/delsh3/delsh3_rvsegfp_abpmcherry_T1/alignment_2017_07_26/delsh3_gfp_todelsh3abp2018_newdelsh3_mytrasf.Rdata"))->delsh3_transf


#Rvs2 col aligned to AP Abp 1
##fake transformation matrix to use get.data on Abp data
transformation_template<-0*sla1_transf

##get time0 as the abp fl.int peak
time(WTabp1$ts)[which(WTabp1$ts[,"mean_sFI"]==max(WTabp1$ts[,"mean_sFI"],na.rm=TRUE))]->my_t0
time(delsh3_abp$ts)[which(delsh3_abp$ts[,"mean_sFI"]==max(delsh3_abp$ts[,"mean_sFI"],na.rm=TRUE))]->my_t0_delsh3
time(delsh3_g_woflalign$ts)[which(delsh3_g_woflalign$ts[,"mean_sFI"]==max(delsh3_g_woflalign$ts[,"mean_sFI"],na.rm=TRUE))]->my_t0_delsh3_rvs

##output nice and usable data using gen.data
#sla1 is shifted in time by the abp max intensity, no shift in y
#gen.data<-function(data,data_trasf,n,sn,rescale.n=1,zero=0,t0=0,propagate.err=TRUE,pixel_size=100)
sla1_wt<-gen.data(WTsla1,sla1_transf, NA, NA, t0=my_t0, zero=0)
inp52_wt<-gen.data(WTinp52,inp52_trasf,NA, NA, t0=my_t0, zero=0)
rvs_wt<-gen.data(WTrvs,rvs_trasf,NA, NA, t0=my_t0, zero=0)
abp1<-gen.data(WTabp1,transformation_template,NA, NA, t0=my_t0, zero=0)

sla1_delsh3<-gen.data(delsh3_sla1,delsh3_sla1_transf,NA, NA, t0=my_t0_delsh3, zero=0)
delsh3_g<-gen.data(delsh3_g_woflalign,delsh3_transf,n=NA,sn=NA, t0=my_t0_delsh3, zero=0)
abp_delsh3<-gen.data(delsh3_abp,transformation_template,NA, NA, t0=my_t0_delsh3, zero=0)


##########################################


##set y0 as the non-moving sla1 region

x1<-mean(sla1_wt[1:100,"x"])
x_delsh3<-median(sla1_delsh3[1:110,"x"])

#plot them
pdf("aligned_newabp2018_removedboth_newdelsh4.pdf")

myplot(abp1[,"t"],abp1[,"x"]-x1,abp1[,"t.err"],abp1[,"x.err"],line.col="#FF3399",xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-10,10),ylim=c(-50,200))
myplot(sla1_wt[,"t"], sla1_wt[,"x"]-x1,sla1_wt[,"t.err"],sla1_wt[,"x.err"],line.col="#083956",hold_on=TRUE, line.lwd=3,deltat=0.25)
myplot(rvs_wt[,"t"],rvs_wt[,"x"]-x1,rvs_wt[,"t.err"],rvs_wt[,"x.err"],line.col="#6633FF", hold_on=TRUE, line.lwd=3,deltat=0.25)
#myplot(inp52_wt[,"t"],inp52_wt[,"x"]-x1,inp52_wt[,"t.err"],inp52_wt[,"x.err"],line.col="#376c1b", hold_on=TRUE, line.lwd=3,deltat=0.25)

myplot(sla1_delsh3[,"t"],sla1_delsh3[,"x"]-x_delsh3,sla1_delsh3[,"t.err"],sla1_delsh3[,"x.err"],line.col="#993300", hold_on=TRUE, line.lwd=3,deltat=0.25)
myplot(delsh3_g[,"t"],delsh3_g[,"x"]-x_delsh3,delsh3_g[,"t.err"],delsh3_g[,"x.err"],line.col="#FF9900", hold_on=TRUE, line.lwd=3,deltat=0.25)
myplot(abp_delsh3[,"t"],abp_delsh3[,"x"]-x_delsh3,abp_delsh3[,"t.err"],abp_delsh3[,"x.err"],line.col="#FF0033", hold_on=TRUE, line.lwd=3,deltat=0.25)

legend("topleft",c("WTabp", "WTsla1", "WTrvs167", "delsh3-Sla1", "delsh3-GFP", "delsh3-Abp"),lty=1,col=c('#002E00',"#00DD00", "#6633FF", "#993300","#FF9900", "#FF0033"), bty='n', cex=0.75)
title(main="WT data with abp-GFP alignments", sub="t0 WT=WT abp max, t0 delsh3= delsh3 abp max")





#myplot(inp52_wt2[,"t"],inp52_wt2[,"x"]-x0,inp52_wt2[,"t.err"],inp52_wt2[,"x.err"],line.col="#66CC00", hold_on=TRUE, line.lwd=3,deltat=0.25)

#myplot(abp2[,"t"], abp2[,"x"]-x1,abp2[,"t.err"],abp2[,"x.err"],line.col="#3300FF",hold_on=TRUE, line.lwd=3,deltat=0.25)

#myplot(sla2_wt[,"t"], sla2_wt[,"x"]-x0,sla2_wt[,"t.err"],sla2_wt[,"x.err"],line.col="#FF6600",hold_on=TRUE, line.lwd=3,deltat=0.25)
#myplot(sla1_wtap[,"t"], sla1_wtap[,"x"]-x2,sla1_wtap[,"t.err"],sla1_wtap[,"x.err"],line.col="#003366",hold_on=TRUE, line.lwd=3,deltat=0.25)
#myplot(rvs_wtap[,"t"], rvs_wtap[,"x"]-x0,rvs_wtap[,"t.err"],rvs_wtap[,"x.err"],line.col="#376c1b",hold_on=TRUE, line.lwd=3,deltat=0.25)

#myplot(abp1_ap[,"t"], abp1_ap[,"x"]-x2,abp1_ap[,"t.err"],abp1_ap[,"x.err"],line.col="#FF9999",hold_on=TRUE, line.lwd=3,deltat=0.25)

#legend("topleft",c("WT abp1","WT abp2", "WT sla1","WT inp52", "WT rvs", "WT sla2 AP","WT sla1 AP", "WT abp AP"),lty=1,col=c('#002E00',"#3300FF", "#00DD00", "#376c1b", "#6633FF", "#FF6600", "#CCFF99", "#FF9999"),bty='n', cex=0.75)
#legend("topleft",c("WT abp1", "WT sla1","WT sla1 AP", "WT abp AP"),lty=1,col=c('#002E00',"#00DD00","#003366","#FF9999"), bty='n', cex=0.75)


mnorm<-function(x) return((x-min(x,na.rm=T))/(max(x,na.rm=T)-min(x,na.rm=T)))
# #fluorescene intensities sla1
myplot(abp1[,"t"],mnorm(abp1[,"fi"]),abp1[,"t.err"],abp1[,"fi.err"],line.col="#FF3399",xlab="Time (s)",ylab="Fl.Intensity (a.u)",line.lwd=3,deltat=0.25,xlim=c(-25,15),ylim=c(0,1.1))
myplot(sla1_wt[,"t"],mnorm(sla1_wt[,"fi"]),sla1_wt[,"t.err"],sla1_wt[,"fi.err"],line.col="#083956",hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(inp52_wt[,"t"],mnorm(inp52_wt[,"fi"]),inp52_wt[,"t.err"],inp52_wt[,"fi.err"],line.col="#376c1b",hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(rvs_wt[,"t"],mnorm(rvs_wt[,"fi"]),rvs_wt[,"t.err"],rvs_wt[,"fi.err"],line.col="#6633FF",hold_on=TRUE,line.lwd=3,deltat=0.25)

myplot(sla1_delsh3[,"t"],mnorm(sla1_delsh3[,"fi"]),sla1_delsh3[,"t.err"],sla1_delsh3[,"fi.err"],line.col="#993300",hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(delsh3_g[,"t"],mnorm(delsh3_g[,"fi"]),delsh3_g[,"t.err"],delsh3_g[,"fi.err"],line.col="#FF9900",hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(abp_delsh3[,"t"],mnorm(abp_delsh3[,"fi"]),abp_delsh3[,"t.err"],abp_delsh3[,"fi.err"],line.col="#FF0033",hold_on=TRUE,line.lwd=3,deltat=0.25)

legend("topleft",c("WTabp", "WTsla1", "WTrvs167", "delsh3-Sla1", "delsh3-GFP", "delsh3-Abp"),lty=1,col=c('#002E00',"#00DD00", "#6633FF", "#993300","#FF9900", "#FF0033"), bty='n', cex=0.75)
title(main="WT data with abp-GFP alignments", sub="t0 WT=WT abp max, t0 delsh3= delsh3 abp max")

##separate
myplot(abp1[,"t"],mnorm(abp1[,"fi"]),abp1[,"t.err"],abp1[,"fi.err"],line.col="#FF3399",xlab="Time (s)",ylab="Fl.Intensity (a.u)",line.lwd=3,deltat=0.25,xlim=c(-25,15),ylim=c(0,1.1))
#myplot(sla1_wt[,"t"],mnorm(sla1_wt[,"fi"]),sla1_wt[,"t.err"],sla1_wt[,"fi.err"],line.col="#083956",hold_on=TRUE,line.lwd=3,deltat=0.25)
#myplot(inp52_wt[,"t"],mnorm(inp52_wt[,"fi"]),inp52_wt[,"t.err"],inp52_wt[,"fi.err"],line.col="#376c1b",hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(rvs_wt[,"t"],mnorm(rvs_wt[,"fi"]),rvs_wt[,"t.err"],rvs_wt[,"fi.err"],line.col="#6633FF",hold_on=TRUE,line.lwd=3,deltat=0.25)

#myplot(sla1_delsh3[,"t"]+2.2,mnorm(sla1_delsh3[,"fi"]),sla1_delsh3[,"t.err"],sla1_delsh3[,"fi.err"],line.col="#993300",hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(delsh3_g[,"t"],mnorm(delsh3_g[,"fi"]),delsh3_g[,"t.err"],delsh3_g[,"fi.err"],line.col="#FF9900",hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(abp_delsh3[,"t"],mnorm(abp_delsh3[,"fi"]),abp_delsh3[,"t.err"],abp_delsh3[,"fi.err"],line.col="#FF0033",hold_on=TRUE,line.lwd=3,deltat=0.25)
legend("topleft",c("WTabp", "WTsla1", "WTrvs167", "delsh3-Sla1", "delsh3-GFP", "delsh3-Abp"),lty=1,col=c('#002E00',"#00DD00", "#6633FF", "#993300","#FF9900", "#FF0033"), bty='n', cex=0.75)
title(main="WT data with abp-GFP alignments", sub="t0 WT=WT abp max, t0 delsh3= delsh3 abp max")

##separate
myplot(abp1[,"t"],mnorm(abp1[,"fi"]),abp1[,"t.err"],abp1[,"fi.err"],line.col="#FF3399",xlab="Time (s)",ylab="Fl.Intensity (a.u)",line.lwd=3,deltat=0.25,xlim=c(-25,15),ylim=c(0,1.1))
myplot(sla1_wt[,"t"],mnorm(sla1_wt[,"fi"]),sla1_wt[,"t.err"],sla1_wt[,"fi.err"],line.col="#083956",hold_on=TRUE,line.lwd=3,deltat=0.25)
#myplot(inp52_wt[,"t"],mnorm(inp52_wt[,"fi"]),inp52_wt[,"t.err"],inp52_wt[,"fi.err"],line.col="#376c1b",hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(rvs_wt[,"t"],mnorm(rvs_wt[,"fi"]),rvs_wt[,"t.err"],rvs_wt[,"fi.err"],line.col="#6633FF",hold_on=TRUE,line.lwd=3,deltat=0.25)


myplot(delsh3_g[,"t"],mnorm(delsh3_g[,"fi"]),delsh3_g[,"t.err"],delsh3_g[,"fi.err"],line.col="#FF9900",xlab="Time (s)",ylab="Fl.Intensity (a.u)",line.lwd=3,deltat=0.25,xlim=c(-25,15),ylim=c(0,1.1))
myplot(abp_delsh3[,"t"],mnorm(abp_delsh3[,"fi"]),abp_delsh3[,"t.err"],abp_delsh3[,"fi.err"],line.col="#FF0033",hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(sla1_delsh3[,"t"],mnorm(sla1_delsh3[,"fi"]),sla1_delsh3[,"t.err"],sla1_delsh3[,"fi.err"],line.col="#993300",hold_on=TRUE,line.lwd=3,deltat=0.25)
legend("topleft",c("WTabp", "WTsla1", "WTrvs167", "delsh3-Sla1", "delsh3-GFP", "delsh3-Abp"),lty=1,col=c('#002E00',"#00DD00", "#6633FF", "#993300","#FF9900", "#FF0033"), bty='n', cex=0.75)
title(main="WT data with abp-GFP alignments", sub="t0 WT=WT abp max, t0 delsh3= delsh3 abp max")

myplot(abp1[,"t"],mnorm(abp1[,"fi"]),abp1[,"t.err"],abp1[,"fi.err"],line.col="#FF3399",xlab="Time (s)",ylab="Fl.Intensity (a.u)",line.lwd=3,deltat=0.25,xlim=c(-25,15),ylim=c(0,1.1))
myplot(abp_delsh3[,"t"],mnorm(abp_delsh3[,"fi"]),abp_delsh3[,"t.err"],abp_delsh3[,"fi.err"],line.col="#FF0033",hold_on=TRUE,line.lwd=3,deltat=0.25)

myplot(abp1[,"t"],mnorm(abp1[,"fi"]),abp1[,"t.err"],abp1[,"fi.err"],line.col="#FFFFFF",xlab="Time (s)",ylab="Fl.Intensity (a.u)",line.lwd=3,deltat=0.25,xlim=c(-25,15),ylim=c(0,1.1))
myplot(rvs_wt[,"t"],mnorm(rvs_wt[,"fi"]),rvs_wt[,"t.err"],rvs_wt[,"fi.err"],line.col="#6633FF",hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(delsh3_g[,"t"],mnorm(delsh3_g[,"fi"]),delsh3_g[,"t.err"],delsh3_g[,"fi.err"],line.col="#FF9900",hold_on=TRUE,line.lwd=3,deltat=0.25)

myplot(abp1[,"t"],abp1[,"x"]-x1,abp1[,"t.err"],abp1[,"x.err"],line.col="#FFFFFF",xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-25,15),ylim=c(-50,200),las=1, tck=0.01, bty="n", cex.axis=1.5)
myplot(rvs_wt[,"t"],rvs_wt[,"x"]-x1,rvs_wt[,"t.err"],rvs_wt[,"x.err"],line.col="#6633FF", hold_on=TRUE, line.lwd=3,deltat=0.25)
myplot(sla1_wt[,"t"], sla1_wt[,"x"]-x1,sla1_wt[,"t.err"],sla1_wt[,"x.err"],line.col="#083956",hold_on=TRUE, line.lwd=3,deltat=0.25)

myplot(sla1_delsh3[,"t"],sla1_delsh3[,"x"]-x_delsh3,sla1_delsh3[,"t.err"],sla1_delsh3[,"x.err"],line.col="#993300", hold_on=TRUE, line.lwd=3,deltat=0.25)

myplot(delsh3_g[,"t"],delsh3_g[,"x"]-x_delsh3,delsh3_g[,"t.err"],delsh3_g[,"x.err"],line.col="#FF9900", hold_on=TRUE, line.lwd=3,deltat=0.25)

minor.tick(nx=10, ny=10, tick.ratio=1)
grid(nx = NULL, ny = NULL, col = "lightgray", lty = "dotted",
     lwd = par("lwd"), equilogs = TRUE)
abline(h = seq(0, 150, 10), v=-25:10, col="gray", lty=1)

dev.off()

