#plot the data generated by the alignment

source("/Users/deepikaa/Desktop/data_desktop/Doc/align_tracks.R")
##WT

get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/WT/sla1egfp/wo_treat/tracks.Rdata"))->sla1wt_notrans
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/WT/sla1egfp/t"))->sla1wt_notrans
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/WT/sla1egfp/2016_06_01_141_geneva/mw100/tracks.Rdata"))->sla1_141_notrans
#sla1 used for inp comparison
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/WT/sla1egfp/2017_06_12_823/tracks.Rdata"))->sla1_823_notrans

##deletion sla1
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/delVps1/newstrain/x141_3D/2015_06_28/tracks.Rdata"))-> sla1_delvps_notrans
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/delinp51/823_SC/2017_03_07/tracks.Rdata"))->sla1_delinp51_notrans
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/delinp52/2017_12_29/52del_823_8d/tracks.Rdata"))->sla1_delinp52_notrans

#rvs used for vps, inp comparison
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/WT/Rvs167/2014_03_26_rvs_egfp_w_wo_latA/set1/before_latA/analysis1/data.Rdata"))->WTrvs_notrans
#rvs from inp deletion dataset
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/WT/Rvs167/2016_06_02_2832_geneva/tracks.Rdata"))->WTrvs2832_notrans
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/WT/Rvs167/2017_03_29_3131/tracks.Rdata"))->WTrvs3131_notrans

##deletion Rvs
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/delVps1/newstrain/x3132_1col/2015_06_30/tracks.Rdata"))->rvs_delvps_notrans
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/delinp52/2017_10_17/inp52_del_3132_9a/tracks_stereotypic.Rdata"))->rvs_delinp52_notrans
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/delinp51/3131/2017_03_29/7x3131_1A/tracks.Rdata"))->rvs_delinp51_notrans
#secondRvs
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/delinp51/3131/2017_03_22/set2/tracks.Rdata"))->inp51_del_rvs

#delsh3
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/rvs_delsh3/rvs167egfp_delsh3/2014_07_14_rvs167egfp_delsh3_highmag/se2/first_analysis/tracks.Rdata"))->rvs_delsh3

#abp from alignment of sla1 SC to sla1-abp DC _ W2.data
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/DC/wt/sla10822/0822_wo_treat/rev_align/fimax_false/wt_sla1_REV3_bothFALSE_W2.Rdata"))->abp_notrans_wt
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/DC/wt/sla10822/0822_wo_treat/rev_align/fimax_false/wt_sla1_REV_bothfalse_W2.Rdata"))->abp141_notrans_wt
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/DC/wt/sla10822/0822_wo_treat/rev_align/fimax_false/wt_sla1_823_REV_bothfalse_W2.Rdata"))->abp823_notrans_wt

get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/DC/wt/Rvs167/2014_03_08_rvs167egfp_abp1mcherry/beforelat/abp_gfp_revalign/wt_rvsREV_allfalse_W2.Rdata"))->abp_rvs_notrans_wt
###rvs2832 for inp
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/DC/wt/Rvs167/2014_03_08_rvs167egfp_abp1mcherry/beforelat/abp_gfp_revalign/wt_rvsREV2832_allfalse_W2.Rdata"))->abp_rvs2832_notrans_wt
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/DC/wt/Rvs167/2014_03_08_rvs167egfp_abp1mcherry/beforelat/abp_gfp_revalign/wt_rvsREV3131_allfalse_W2.Rdata"))->abp_rvs3131_notrans_wt

#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/DC/delvps/2019_10_30/3347_delvps823/vpsdel_sla1REV_W2.Rdata"))->abp823_notrans_delvps
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/DC/delvps/2019_10_30/3347_delvps823/vpsdel_sla1REV_allFALSE_all_new_W2.Rdata"))->abp823_notrans_delvps
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/DC/delvps/2019_12_20/vpsdel_RvsREV_allFALSE_W2.Rdata"))->abp3132_notrans_delvps

get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/DC/inp51_del/2017_09_01/inp51_del/inp51del_RvsREV_W2.Rdata"))->abp3132_notrans_delinp51

get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/DC/inp52_del/2019_10_31/3827_inp52del_823/inp52del_slaREV_allfalse_W2.Rdata"))->abp823_notrans_delinp52
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/DC/inp52_del/2019_10_31/3903_inp52del_3132/inp52del_RvsREV_track2_W2.Rdata"))->abp3132_notrans_delinp51



#generate a template transformation matrix to fool gen.data
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/DC/wt/Rvs167/110824_mytrasf.Rdata"))->transformation_template
transformation_template<-0*transformation_template

#abp for the rvs
#set t0 as the max intensity of each abp
## get t0 from max abp1 intensities for each trace 

abp_notrans_wt[which(abp_notrans_wt[,"mean_sFI"]==max(abp_notrans_wt[,"mean_sFI"],na.rm=TRUE)),"mean_t"]->t0_abp_wt
abp141_notrans_wt[which(abp141_notrans_wt[,"mean_sFI"]==max(abp141_notrans_wt[,"mean_sFI"],na.rm=TRUE)),"mean_t"]->t0_abp141_wt
abp823_notrans_wt[which(abp823_notrans_wt[,"mean_sFI"]==max(abp823_notrans_wt[,"mean_sFI"],na.rm=TRUE)),"mean_t"]->t0_abp823_wt

abp_rvs_notrans_wt[which(abp_rvs_notrans_wt[,"mean_sFI"]==max(abp_rvs_notrans_wt[,"mean_sFI"],na.rm=TRUE)),"mean_t"]->t0_abp_rvs_wt
abp_rvs2832_notrans_wt[which(abp_rvs2832_notrans_wt[,"mean_sFI"]==max(abp_rvs2832_notrans_wt[,"mean_sFI"],na.rm=TRUE)),"mean_t"]->t0_abp_rvs2832
abp_rvs3131_notrans_wt[which(abp_rvs3131_notrans_wt[,"mean_sFI"]==max(abp_rvs3131_notrans_wt[,"mean_sFI"],na.rm=TRUE)),"mean_t"]->t0_abp_rvs3131

abp823_notrans_delvps[which(abp823_notrans_delvps[,"mean_sFI"]==max(abp823_notrans_delvps[,"mean_sFI"],na.rm=TRUE)),"mean_t"]->t0_abp823_delvps
abp3132_notrans_delvps[which(abp3132_notrans_delvps[,"mean_sFI"]==max(abp3132_notrans_delvps[,"mean_sFI"],na.rm=TRUE)),"mean_t"]->t0_abp3132_delvps

#abp823_notrans_delinp51[which(abp823_notrans_delinp51[,"mean_sFI"]==max(abp823_notrans_delinp51[,"mean_sFI"],na.rm=TRUE)),"mean_t"]->t0_abp823_delinp51
abp3132_notrans_delinp51[which(abp3132_notrans_delinp51[,"mean_sFI"]==max(abp3132_notrans_delinp51[,"mean_sFI"],na.rm=TRUE)),"mean_t"]->t0_abp3132_delinp51

abp823_notrans_delinp52[which(abp823_notrans_delinp52[,"mean_sFI"]==max(abp823_notrans_delinp52[,"mean_sFI"],na.rm=TRUE)),"mean_t"]->t0_abp823_delinp52
#abp3132_notrans_delinp52[which(abp3132_notrans_delinp52[,"mean_sFI"]==max(abp3132_notrans_delinp52[,"mean_sFI"],na.rm=TRUE)),"mean_t"]->t0_abp3132_delinp52

#output nice and usable data

############ WITHOUT DC TRANSORMATION#############
#####sla1#####
#wt 
#sla1<-gen.data(sla1_wt,transformation_template,n=NA,sn=NA)
#sla1_141<-gen.data(sla1_notrans141,transformation_template,n=NA,sn=NA)
#sla1_823<-gen.data(sla1_notrans823,transformation_template,n=NA,sn=NA)

#sla1_deletion
#sla1_delvps<-gen.data(delvps_sla1,transformation_template,n=NA,sn=NA) 
#sla823_inpdel51<-gen.data(delinp51_sla1,transformation_template,n=NA,sn=NA)
#sla823_inpdel52<-gen.data(delinp52_sla1,transformation_template,n=NA,sn=NA)

#rvs_deletion
#delvps_rvs<-gen.data(rvs_delvps,transformation_template,n=NA,sn=NA)
#rvs_del51<-gen.data(inp51_del_rvs,transformation_template,n=54.7,sn=5)
#rvs_del52<-gen.data(inp52_del_rvs,transformation_template,n=55.8,sn=7.1)

#mutants
#delsh3<-gen.data(rvs_delsh3,transformation_template,n=NA,sn=NA) 

######RVS####
#rvs<-gen.data(WTrvs,transformation_template,n=NA,sn=NA)
#rvs_wt2832<-gen.data(WTrvs2832,transformation_template,n=54.9,sn=5.4)
#rvs_wt3131<-gen.data(WTrvs3131,transformation_template,n=50.2 ,sn=8.1)

#delsh3<-gen.data(rvs_delsh3,transformation_template,n=NA,sn=NA) 
#delvps_rvs<-gen.data(rvs_delvps,transformation_template,n=NA,sn=NA)

############ WITH DC TRANSORMATION#############
sla1<-gen.data(sla1wt_notrans,transformation_template,n=NA,sn=NA, zero=0, t0=t0_abp_wt)
#sla1_823<-gen.data(sla1_823_notrans,transformation_template,n=NA,sn=NA, zero=0, t0=t0_abp823_wt)
sla1_823<-gen.data(sla1_823_notrans,transformation_template,n=NA,sn=NA, zero=0, t0=t0_abp823_wt)
sla1_141<-gen.data(sla1_141_notrans,transformation_template,n=NA,sn=NA, zero=0, t0=t0_abp141_wt)

rvs<-gen.data(WTrvs_notrans,transformation_template,n=NA,sn=NA, zero = 0, t0=t0_abp_rvs_wt)
rvs2832<-gen.data(WTrvs2832_notrans,transformation_template,n=NA,sn=NA, zero = 0, t0=t0_abp_rvs2832)
rvs3131<-gen.data(WTrvs3131_notrans,transformation_template,n=NA,sn=NA, zero = 0, t0=t0_abp_rvs3131)

sla1_delvps<-gen.data(sla1_delvps_notrans,transformation_template,n=NA,sn=NA, zero=0, t0=t0_abp823_delvps) 
rvs_delvps<-gen.data(rvs_delvps_notrans,transformation_template,n=NA,sn=NA, zero=0, t0=t0_abp3132_delvps)

sla1_delinp51<-gen.data(sla1_delinp51_notrans,transformation_template,n=NA,sn=NA, zero=0, t0=t0_abp823_delinp52) 
sla1_delinp52<-gen.data(sla1_delinp52_notrans,transformation_template,n=NA,sn=NA, zero=0, t0=t0_abp823_delinp52)
#!! dont have a t0 for sla1_delinp51

rvs_delinp51<-gen.data(rvs_delinp51_notrans,transformation_template,n=NA,sn=NA, zero=0, t0=t0_abp3132_delinp51)
rvs_delinp52<-gen.data(rvs_delinp52_notrans,transformation_template,n=NA,sn=NA, zero=0, t0=t0_abp3132_delinp51)


abp_wt<-gen.data(abp_notrans_wt,NULL,n=NA,sn=NA,rescale.n=1, t0=t0_abp_wt)
abp823_wt<-gen.data(abp823_notrans_wt,NULL,n=NA,sn=NA,rescale.n=1, t0=t0_abp823_wt)
abp141_wt<-gen.data(abp141_notrans_wt,NULL,n=NA,sn=NA,rescale.n=1, t0=t0_abp141_wt)

abp_sla1_delvps<-gen.data(abp823_notrans_delvps,NULL,n=NA,sn=NA,rescale.n=1, t0=t0_abp823_delvps)
abp_sla1_delinp52<-gen.data(abp823_notrans_delinp52,NULL,n=NA,sn=NA,rescale.n=1, t0=t0_abp823_delinp52)

abp_rvs<-gen.data(abp_rvs_notrans_wt,NULL,n=NA,sn=NA,rescale.n=1, t0=t0_abp_rvs_wt)
abp_rvs2832<-gen.data(abp_rvs2832_notrans_wt,NULL,n=NA,sn=NA,rescale.n=1, t0=t0_abp_rvs2832)
abp_rvs3131<-gen.data(abp_rvs3131_notrans_wt,NULL,n=NA,sn=NA,rescale.n=1, t0=t0_abp_rvs3131)
abp_rvs_delvps<-gen.data(abp3132_notrans_delvps,NULL,n=NA,sn=NA,rescale.n=1, t0=t0_abp3132_delvps)
abp_rvs_delinp51<-gen.data(abp3132_notrans_delinp51,NULL,n=NA,sn=NA,rescale.n=1, t0=t0_abp3132_delinp51)

#t_sla1=sla1[,"t"]-sla1[1,"t"]
t_sla1_823=sla1_823[,"t"]-sla1_823[1,"t"]
#t_sla1_delvps=delvps_sla1[,"t"]-delvps_sla1[1,"t"]
#t_delvps=delvps[,"t"]-delvps[1,"t"]
t_sla1_del51=sla1_delinp51[,"t"]-sla1_delinp51[1,"t"]
t_sla1_del52=sla1_delinp52[,"t"]-sla1_delinp52[1,"t"]

#t_rvs=rvs[,"t"]-rvs[1,"t"]
#t_2832=rvs_wt2832[,"t"]-rvs_wt2832[1,"t"]
t_3131=rvs3131[,"t"]-rvs3131[1,"t"]

#t_delvps=delvps_rvs[,"t"]-delvps_rvs[1,"t"]
t_del51=rvs_delinp51[,"t"]-rvs_delinp51[1,"t"]
t_del52=rvs_delinp52[,"t"]-rvs_delinp52[1,"t"]

#set initial y position to 0

#xsla823<-mean(sla1_823[1:25,"x"])
xsla1<-mean(sla1[1:25,"x"])
xsla141<-mean(sla1_141[1:25,"x"])
xsla823<-mean(sla1_823[1:25,"x"])

xsla_vpsdel<-mean(sla1_delvps[1:25,"x"])
xsla_inpdel51<-mean(sla1_delinp51[1:25,"x"])
xsla_inpdel52<-mean(sla1_delinp52[1:25,"x"])

x_rvs<-mean(rvs[1:25,"x"])
x_rvs2832<-mean(rvs2832[1:25,"x"])
x_rvs3131<-mean(rvs3131[1:25,"x"])
x_rvsdel51<-mean(rvs_delinp51[1:25,"x"])
x_rvsdel52<-mean(rvs_delinp52[1:25,"x"])
x_rvsdelvps<-mean(rvs_delvps[1:25,"x"])

mnorm<-function(x) return((x-min(x,na.rm=T))/(max(x,na.rm=T)-min(x,na.rm=T)))

#plot them
pdf("check_mutantDC_wt_allfalse_rvsdelvps_wtrvs6x.pdf")
#5 includes a sla1 intensity plot
#####check sla1 alignment
##sla1 all w/ abp intensities
myplot(sla1[,"t"],sla1[,"x"]-xsla1,sla1[,"t.err"],sla1[,"x.err"],line.col="#660000",xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-30,10),ylim=c(-10,200))
myplot(abp_wt[,"t"],mnorm(abp_wt[,"fi"])*200,abp_wt[,"t.err"],abp_wt[,"fi.err"],line.col="#6600FF",hold_on=TRUE,line.lwd=3,deltat=0.25)
legend("topleft",c("WT-sla1-hd", "abp-w2_int"),lty=1,col=c("#660000", "#6600FF"),bty='n', cex=0.75)
title("sla1 vs abp wt")

myplot(sla1_141[,"t"],sla1_141[,"x"]-xsla141,sla1_141[,"t.err"],sla1_141[,"x.err"],line.col="#00CC00",xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-30,10),ylim=c(-10,200))
myplot(abp141_wt[,"t"],mnorm(abp141_wt[,"fi"])*200,abp141_wt[,"t.err"],abp141_wt[,"fi.err"],line.col="#6600CC",hold_on=TRUE,line.lwd=3,deltat=0.25)
legend("topleft",c("WT-sla1-141", "abp141-w2_int"),lty=1,col=c("#00CC00", "#6600CC"),bty='n', cex=0.75)
title("sla1_141 vs abp 141") 

myplot(sla1_823[,"t"],sla1_823[,"x"]-xsla823,sla1_823[,"t.err"],sla1_823[,"x.err"],line.col="#00CC00",xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-30,10),ylim=c(-10,200))
myplot(abp823_wt[,"t"],mnorm(abp823_wt[,"fi"])*200,abp823_wt[,"t.err"],abp823_wt[,"fi.err"],line.col="#6600CC",hold_on=TRUE,line.lwd=3,deltat=0.25)
legend("topleft",c("WT-sla1-823", "abp823"),lty=1,col=c("#00CC00", "#6600CC"),bty='n', cex=0.75)
title("sla1 823 vs abp 823")

######

#######delvps plots
myplot(sla1[,"t"],sla1[,"x"]-xsla1,sla1[,"t.err"],sla1[,"x.err"],line.col="#660000",xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-30,10),ylim=c(-10,200))
myplot(sla1_delvps[,"t"],sla1_delvps[,"x"]-xsla_vpsdel,sla1_delvps[,"t.err"],sla1_delvps[,"x.err"],line.col="#086600",hold_on=TRUE,line.lwd=3,deltat=0.25)
legend("topleft",c("WT-sla1", "delvps sla1"),lty=1,col=c("#660000", "#086600"),bty='n', cex=0.75)

title("sla1")

myplot(abp_sla1_delvps[,"t"],mnorm(abp_sla1_delvps[,"fi"])*200,abp_sla1_delvps[,"t.err"],abp_sla1_delvps[,"fi.err"],line.col="#086600",xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-30,10),ylim=c(-10,200))
myplot(abp_wt[,"t"],mnorm(abp_wt[,"fi"])*200,abp_wt[,"t.err"],abp_wt[,"fi.err"],line.col="#660000",hold_on=TRUE,line.lwd=3,deltat=0.25)
#myplot(sla1_141[,"t"],sla1_141[,"x"]-xsla141,sla1_141[,"t.err"],sla1_141[,"x.err"],line.col="#CC0000",hold_on=TRUE,line.lwd=3,deltat=0.25)
#myplot(sla1_823[,"t"],sla1_823[,"x"]-xsla823,sla1_823[,"t.err"],sla1_823[,"x.err"],line.col="#FF6666",hold_on=TRUE,line.lwd=3,deltat=0.25)
legend("topleft",c("abp1 sla1 delvps", "abp1 wt"),lty=1,col=c("#086600","#660000"),bty='n', cex=0.75)

myplot(rvs[,"t"],rvs[,"x"]-x_rvs,rvs[,"t.err"],rvs[,"x.err"],line.col="#660000",xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-30,10),ylim=c(-10,200))
myplot(rvs_delvps[,"t"],rvs_delvps[,"x"]-x_rvsdelvps,rvs_delvps[,"t.err"],rvs_delvps[,"x.err"],line.col="#086600",hold_on=TRUE,line.lwd=3,deltat=0.25)
legend("topleft",c("rvs", "rvs delvps"),lty=1,col=c("#660000","#086600"),bty='n', cex=0.75)

myplot(abp_rvs[,"t"],mnorm(abp_rvs[,"fi"])*200,abp_rvs[,"t.err"],abp_rvs[,"fi.err"],line.col="#660000",xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-10,10),ylim=c(-10,200))
myplot(abp_rvs_delvps[,"t"],mnorm(abp_rvs_delvps[,"fi"])*200,abp_rvs_delvps[,"t.err"],abp_rvs_delvps[,"fi.err"],line.col="#086600",hold_on=TRUE,line.lwd=3,deltat=0.25)
legend("topleft",c("abp1_rvs", "abp1 delvps"),lty=1,col=c("#660000","#086600"),bty='n', cex=0.75)


myplot(rvs[,"t"],rvs[,"x"]-x_rvs,rvs[,"t.err"],rvs[,"x.err"],line.col="#006608",xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-30,10),ylim=c(-10,200))
#myplot(rvs2832[,"t"],rvs2832[,"x"]-x_rvs2832,rvs2832[,"t.err"],rvs2832[,"x.err"],line.col="#CC66CC",hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(rvs3131[,"t"],rvs3131[,"x"]-x_rvs3131,rvs3131[,"t.err"],rvs3131[,"x.err"],line.col="#CC6666",hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(rvs_delinp51[,"t"],rvs_delinp51[,"x"]-x_rvsdel51,rvs_delinp51[,"t.err"],rvs_delinp51[,"x.err"],line.col="#FF6600",hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(rvs_delinp52[,"t"]+1,rvs_delinp52[,"x"]-x_rvsdel52,rvs_delinp52[,"t.err"],rvs_delinp52[,"x.err"],line.col="#FFCC00",hold_on=TRUE,line.lwd=3,deltat=0.25)

legend("topleft",c("WT rvs", "rvs3131", "rvsdelinp51"),lty=1,col=c("#660000", "#006600", "#FF6600"),bty='n', cex=0.75)

#abp1 fl.int vps del

myplot(abp_wt[,"t"],mnorm(abp_wt[,"fi"]),abp_wt[,"t.err"],abp_wt[,"fi.err"],line.col="#FFFFFF",xlab="Time (s)",ylab="Fl.Intensity (a.u)",line.lwd=3,deltat=0.45,xlim=c(-10,10),ylim=c(0,1.1))
#myplot(abp_sla1_delvps[,"t"],mnorm(abp_sla1_delvps[,"fi"]),abp_sla1_delvps[,"t.err"],abp_sla1_delvps[,"fi.err"],line.col="#086600",hold_on=TRUE,line.lwd=3,deltat=0.25)

#myplot(abp_rvs_delvps[,"t"],mnorm(abp_rvs_delvps[,"fi"]),abp_rvs_delvps[,"t.err"],abp_rvs_delvps[,"fi.err"],line.col="#006688",hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(abp_rvs[,"t"],mnorm(abp_rvs[,"fi"]),abp_rvs[,"t.err"],abp_rvs[,"fi.err"],line.col="#006608",hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(abp_rvs2832[,"t"],mnorm(abp_rvs2832[,"fi"]),abp_rvs2832[,"t.err"],abp_rvs2832[,"fi.err"],line.col="#CC66CC",hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(abp_rvs3131[,"t"],mnorm(abp_rvs3131[,"fi"]),abp_rvs3131[,"t.err"],abp_rvs3131[,"fi.err"],line.col="#CC6666",hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(abp_rvs_delinp51[,"t"],mnorm(abp_rvs_delinp51[,"fi"]),abp_rvs_delinp51[,"t.err"],abp_rvs_delinp51[,"fi.err"],line.col="#FF6600",hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(abp_sla1_delinp52[,"t"],mnorm(abp_sla1_delinp52[,"fi"]),abp_sla1_delinp52[,"t.err"],abp_sla1_delinp52[,"fi.err"],line.col="#FFCC00",hold_on=TRUE,line.lwd=3,deltat=0.25)

legend("topleft",c("abp_rvs", "abp1_2832", "abp1_3132", "abp1_delinp51", "abp1_delinp52"),lty=1,col=c("#006608","#CC66CC", "#CC6666", "#CC66FF", "#FFCC00"),bty='n', cex=0.75)
title(main="abp1fl. intensity", sub="x axis 0 at abp_w2 max.")


##############################rvs plots
myplot(rvs3131[,"t"]-0.4,mnorm(rvs3131[,"fi"]),rvs3131[,"t.err"],rvs3131[,"fi.err"],line.col="#000000",xlab="Time (s)",ylab="Fl.Intensity (a.u)",line.lwd=3,deltat=0.45,xlim=c(-5,5),ylim=c(0,1.1))
myplot(rvs_delinp51[,"t"]+0.3,mnorm(rvs_delinp51[,"fi"]),rvs_delinp51[,"t.err"],rvs_delinp51[,"fi.err"],line.col="#FF6600",hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(rvs_delinp52[,"t"]-26,mnorm(rvs_delinp52[,"fi"]),rvs_delinp52[,"t.err"],rvs_delinp52[,"fi.err"],line.col="#FFCC00",hold_on=TRUE,line.lwd=3,deltat=0.25)
legend("topleft",c("WT-rvs", "delinp52-rvs","delinp51-rvs"),lty=1,col=c("#000000","#FFCC00", "#FF6600"),bty='n', cex=0.75)
title(main="rvs. intensity", sub="x axis 0 shifted to max. manually")


myplot(t_3131,mnorm(rvs3131[,"fi"]),rvs3131[,"t.err"],rvs3131[,"fi.err"],line.col="#000000",xlab="Time (s)",ylab="Fl.Intensity (a.u)",line.lwd=3,deltat=0.45,xlim=c(-2,7),ylim=c(0,1.1))
myplot(t_del51,mnorm(rvs_delinp51[,"fi"]),rvs_delinp51[,"t.err"],rvs_delinp51[,"fi.err"],line.col="#FF6600",hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(t_del52,mnorm(rvs_delinp52[,"fi"]),rvs_delinp52[,"t.err"],rvs_delinp52[,"fi.err"],line.col="#FFCC00",hold_on=TRUE,line.lwd=3,deltat=0.25)
legend("topleft",c("WT-rvs", "delinp52-rvs","delinp51-rvs"),lty=1,col=c("#000000","#FFCC00", "#FF6600"),bty='n', cex=0.75)
title(main="rvs. intensity", sub="x axis 0 at starting position")


##rvs movement vs intensity
myplot(rvs3131[,"t"]-0.4,mnorm(rvs3131[,"fi"]),rvs3131[,"t.err"],rvs3131[,"fi.err"],line.col="#ffffff",xlab="Time (s)",ylab="Fl.Intensity (a.u)",line.lwd=3,deltat=0.45,xlim=c(-5,5),ylim=c(-10,150))
myplot(rvs_delinp51[,"t"],mnorm(rvs_delinp51[,"fi"])*100,rvs_delinp51[,"t.err"],rvs_delinp51[,"fi.err"],line.col="#FF6600",hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(rvs_delinp51[,"t"],rvs_delinp51[,"x"]-x_rvsdel51,rvs_delinp51[,"t.err"],rvs_delinp51[,"x.err"],line.col="#FF6666",hold_on=TRUE,line.lwd=3,deltat=0.25)

myplot(rvs_delinp52[,"t"]-26,mnorm(rvs_delinp52[,"fi"])*100,rvs_delinp52[,"t.err"],rvs_delinp52[,"fi.err"],line.col="#FFCC00",hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(rvs_delinp52[,"t"]-26,rvs_delinp52[,"x"]-x_rvsdel52,rvs_delinp52[,"t.err"],rvs_delinp52[,"x.err"],line.col="#FFdd99",hold_on=TRUE,line.lwd=3,deltat=0.25)
legend("topleft",c("WT-rvs", "delinp52-rvs","delinp51-rvs"),lty=1,col=c("#000000","#FFCC00", "#FF6600"),bty='n', cex=0.75)

##############################sla1 plots
myplot(sla1_823[,"t"],mnorm(sla1_823[,"fi"]),sla1_823[,"t.err"],sla1_823[,"fi.err"],line.col="#000000",xlab="Time (s)",ylab="Fl.Intensity (a.u)",line.lwd=3,deltat=0.45,xlim=c(-15,15),ylim=c(0,1.1))
myplot(sla1_delinp52[,"t"],mnorm(sla1_delinp52[,"fi"]),sla1_delinp52[,"t.err"],sla1_delinp52[,"fi.err"],line.col="#FFCC00",hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(sla1_delinp51[,"t"],mnorm(sla1_delinp51[,"fi"]),sla1_delinp51[,"t.err"],sla1_delinp51[,"fi.err"],line.col="#FF6600",hold_on=TRUE,line.lwd=3,deltat=0.25)
legend("topleft",c("WT-sla1", "delinp52-sla1","delinp51-sla1"),lty=1,col=c("#000000","#FFCC00", "#FF6600"),bty='n', cex=0.75)
title("sla1 all intensities aligned to maximum intensity manually ")

myplot(t_sla1_823,mnorm(sla1_823[,"fi"]),sla1_823[,"t.err"],sla1_823[,"fi.err"],line.col="#000000",xlab="Time (s)",ylab="Fl.Intensity (a.u)",line.lwd=3,deltat=0.45,xlim=c(-5,30),ylim=c(0,1.1))
myplot(t_sla1_del52,mnorm(sla1_delinp52[,"fi"]),sla1_delinp52[,"t.err"],sla1_delinp52[,"fi.err"],line.col="#FFCC00",hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(t_sla1_del51,mnorm(sla1_delinp51[,"fi"]),sla1_delinp51[,"t.err"],sla1_delinp51[,"fi.err"],line.col="#FF6600",hold_on=TRUE,line.lwd=3,deltat=0.25)
legend("topleft",c("WT-sla1", "delinp52-sla1","delinp51-sla1"),lty=1,col=c("#000000","#FFCC00", "#FF6600"),bty='n', cex=0.75)
title("sla1 all intensities aligned to starting position ")

myplot(sla1_delinp52[,"t"],sla1_delinp52[,"x"]-xsla_inpdel52,sla1_delinp52[,"t.err"],sla1_delinp52[,"x.err"],line.col="#FFCC00",xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-30,10),ylim=c(-10,200))
myplot(sla1_delinp51[,"t"],sla1_delinp51[,"x"]-xsla_inpdel51,sla1_delinp51[,"t.err"],sla1_delinp51[,"x.err"],line.col="#FF6600",hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(sla1_823[,"t"],sla1_823[,"x"]-xsla823,sla1_823[,"t.err"],sla1_823[,"x.err"],line.col="#000000",hold_on=TRUE,line.lwd=3,deltat=0.25)
legend("topleft",c("WT-sla1", "delinp52-sla1","delinp51-sla1"),lty=1,col=c("#000000","#FFCC00", "#FF6600"),bty='n', cex=0.75)
title("sla1 movements ")


###only inp deletion sla1 and abp1
myplot(sla1_delinp52[,"t"],sla1_delinp52[,"x"]-xsla_inpdel52,sla1_delinp52[,"t.err"],sla1_delinp52[,"x.err"],line.col="#660000",xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-30,10),ylim=c(-10,200))
myplot(abp_sla1_delinp52[,"t"],mnorm(abp_sla1_delinp52[,"fi"])*200,abp_sla1_delinp52[,"t.err"],abp_sla1_delinp52[,"fi.err"],line.col="#FFCC00",hold_on=TRUE,line.lwd=3,deltat=0.25)

#myplot(sla1_823[,"t"],sla1_823[,"x"]-xsla823,sla1_823[,"t.err"],sla1_823[,"x.err"],line.col="#FF6666",hold_on=TRUE,line.lwd=3,deltat=0.25)
legend("topleft",c("WT-sla1", "delinp52-sla1"),lty=1,col=c("#660000", "#FFCC00"),bty='n', cex=0.75)
title(main="sla1 inp52del")


## full alignments
myplot(sla1_delinp52[,"t"],sla1_delinp52[,"x"]-xsla_inpdel52,sla1_delinp52[,"t.err"],sla1_delinp52[,"x.err"],line.col="#660000",xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-30,10),ylim=c(-10,200))
myplot(rvs_delinp52[,"t"]-26,rvs_delinp52[,"x"]-x_rvsdel52,rvs_delinp52[,"t.err"],rvs_delinp52[,"x.err"],line.col="#FFdd99",hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(abp_sla1_delinp52[,"t"],mnorm(abp_sla1_delinp52[,"fi"])*200,abp_sla1_delinp52[,"t.err"],abp_sla1_delinp52[,"fi.err"],line.col="#FFCC00",hold_on=TRUE,line.lwd=3,deltat=0.25)
title(main="alignment of inp52")

###############################compare inp and wt
myplot(abp_wt[,"t"],mnorm(abp_wt[,"fi"]),abp_wt[,"t.err"],abp_wt[,"fi.err"],line.col="#660000",xlab="Time (s)",ylab="Fl.Intensity (a.u)",line.lwd=3,deltat=0.45,xlim=c(-30,10),ylim=c(0,1.1))
myplot(abp141_wt[,"t"],mnorm(abp141_wt[,"fi"]),abp141_wt[,"t.err"],abp141_wt[,"fi.err"],line.col="#CC0000",hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(abp_sla1_delinp52[,"t"],mnorm(abp_sla1_delinp52[,"fi"]),abp_sla1_delinp52[,"t.err"],abp_sla1_delinp52[,"fi.err"],line.col="#FFCC00",hold_on=TRUE,line.lwd=3,deltat=0.25)

legend("topleft",c("WT-abp1", "wt abp141", "abp_sla1 inp52del"),lty=1,col=c("#660000", "#006600", "#FFCC00"),bty='n', cex=0.75)
title(main="sla1 sorted", sub="x axis 0 at abp_w2 max.")

#myplot(t1,rvs[,"x"]-x1,rvs[,"t.err"],rvs[,"x.err"],line.col="#7d6cc0",xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(0,30),ylim=c(-25,250))
##myplot(t6+2.5,delvps[,"x"]-x6,delvps[,"t.err"],delvps[,"x.err"],line.col="#90c276",hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(sla1_823[,"t"],sla1_823[,"x"]-xsla823,sla1_823[,"t.err"],sla1_823[,"x.err"],line.col="#660000",xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-30,10),ylim=c(-10,200))
myplot(abp823_wt[,"t"],mnorm(abp823_wt[,"fi"])*200,abp823_wt[,"t.err"],abp823_wt[,"fi.err"],line.col="#FF6666",hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(abp141_wt[,"t"],mnorm(abp141_wt[,"fi"])*200,abp141_wt[,"t.err"],abp141_wt[,"fi.err"],line.col="#CC0000",hold_on=TRUE,line.lwd=3,deltat=0.25)

legend("topleft",c("WT-sla1", "delVps1-sla1"),lty=1,col=c("#660000", "#006600"),bty='n', cex=0.75)
title(main="sla1 sorted", sub="x axis 0 at abp_w2 max.")



dev.off()
