#plot the data generated by the alignment
library(RColorBrewer)
source("/Users/deepikaa/Desktop/data_desktop/Doc/align_tracks.R")
mnorm<-function(x) return((x-min(x,na.rm=T))/(max(x,na.rm=T)-min(x,na.rm=T)))
##########haploid
#sla1
#WT sla1
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/WT/sla1egfp/2017_06_12_823/tracks.Rdata"))->wtsla12017
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/WT/sla1egfp/2016_06_01_141_geneva/mw100/tracks.Rdata"))->wtsla1_141geneva
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/WT/sla1egfp/2016_06_01_141_geneva/mw100/tracks.Rdata"))->wtsla1_141geneva
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/WT/sla1egfp/wo_treat/tracks.Rdata"))->wtsla1_hd
#RVSmutants
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Rvsduplication/Sla1/2017_06_12_161d100_167d100_823_5a/tracks.Rdata"))->rvsdup_sla1
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Rvsduplication/Rvs_delsh3/2017_12_29/sh3dup_823_5a/tracks.Rdata"))->delsh3dup_sla1
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/rvs_delsh3/rvs167_delsh3_sla1_egfp/2015_04_02/tracks.Rdata"))->delsh3_sla1
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/delrvs167/delrvs_sla1_0531/wo_treatment/analysis_1_2p/tracks.Rdata"))->delrvs_sla1

#rvs
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/WT/Rvs167/2017_03_29_3131/tracks.Rdata"))->WTrvs_gen3131
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/rvs_delsh3/rvs167egfp_delsh3/2016_06_02_3154_delsh3_gfp_geneva/analysis2woFlalign/tracks.Rdata"))->delsh3_g_woflalign

get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Rvsduplication/Rvs167/2017_06_19/161_d100_167d3131_5b/tracks.Rdata")) -> rvs161d_167d
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Rvsduplication/Rvs_delsh3/2017_07_21/delsh3dup/motile_wt/motile_wt.Rdata")) ->delsh3_dup_sorted

##abp1 for happloid without co-tags
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/delrvs167/delrvs_abpegfp_wotreat/x0122_80ms_25p488_dualview488_1x255/tracks.Rdata"))->delrvs_notrans_abp1gfp
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/rvs_delsh3/delsh3_abp_egfp/2016_06_02_delsh3_abp_gfp_geneva/thirdanalyisis/tracks.Rdata"))->delsh3_notrans_abp1gfp
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/WT/Abp1/2017_04_10_123/tracks.Rdata"))->wt_notrans_abp1gfp

#abp from alignment of Sla1 SC to Rvs-abp DC _ W2.data
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/DC/wt/sla10822/0822_wo_treat/rev_align/wt_sla1_823_REV_bothfalse_W2.Rdata"))->abp_notrans_Rvs1x_w2
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/DC/rvsduplicat/2020_05_16/3706/2xRVS_823_revalign_W2.Rdata"))->abp_notrans_Rvs2x_w2
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/DC/delsh3/2016_06_01_delsh3_sla1GFP_abpMch_geneva/rvsdelsh3_sla1gfp_geneva_W2.Rdata"))->abp_notrans_1xBAR_w2
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/DC/rvsduplicat/2019_10_31/3826_2xbar823/2xBAR_823_revalign_W2.Rdata"))->abp_notrans_2xBAR_w2


#abp mcherry from mcherry_sla1co-tag
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_07_31/823_mch/tracks.Rdata"))->abpmch_notrans_1xRvs
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_07_26/2xRVS823_3706/tracks.Rdata"))->abpmch_notrans_2xRvs
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_07_27/1xbar_823_3292/tracks.Rdata"))->abpmch_notrans_1xBar
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_07_27/2xbar_823_3826/tracks.Rdata"))->abpmch_notrans_2xBar
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_02_06/1801/tracks.Rdata"))->abpmch_notrans_rvsdel

#abp mcherry from mcherry_rvsco-tag
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_02_06/3132/tracks.Rdata"))->abpmch_notrans_1xRvs_rvs
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_08_11/3710/tracks.Rdata"))->abpmch_notrans_2xRvs_rvs
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_08_11/3286/tracks.Rdata"))->abpmch_notrans_1xBar_rvs
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_08_11/3714/tracks.Rdata"))->abpmch_notrans_2xBar_rvs


#generate a template transformation matrix to fool gen.data
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/DC/wt/Rvs167/110824_mytrasf.Rdata"))->transformation_template
transformation_template<-0*transformation_template

time(WTrvs_gen3131$ts)[which(WTrvs_gen3131$ts[,"mean_sFI"]==max(WTrvs_gen3131$ts[,"mean_sFI"],na.rm=TRUE))]->t0_rvs
time(rvs161d_167d$ts)[which(rvs161d_167d$ts[,"mean_sFI"]==max(rvs161d_167d$ts[,"mean_sFI"],na.rm=TRUE))]->t0_rvsdup
time(delsh3_g_woflalign$ts)[which(delsh3_g_woflalign$ts[,"mean_sFI"]==max(delsh3_g_woflalign$ts[,"mean_sFI"],na.rm=TRUE))]->t0_delsh3
time(delsh3_dup_sorted$ts)[which(delsh3_dup_sorted$ts[,"mean_sFI"]==max(delsh3_dup_sorted$ts[,"mean_sFI"],na.rm=TRUE))]->t0_delsh3dup

#maxima for abp1-gfps

time(delrvs_notrans_abp1gfp$ts)[which(delrvs_notrans_abp1gfp$ts[,"mean_sFI"]==max(delrvs_notrans_abp1gfp$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abp_delrvsgfp
time(delsh3_notrans_abp1gfp$ts)[which(delsh3_notrans_abp1gfp$ts[,"mean_sFI"]==max(delsh3_notrans_abp1gfp$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abp_delsh3gfp
time(wt_notrans_abp1gfp$ts)[which(wt_notrans_abp1gfp$ts[,"mean_sFI"]==max(wt_notrans_abp1gfp$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abp_wtgfp

#abp1 .W2 times
abp_notrans_Rvs1x_w2[which(abp_notrans_Rvs1x_w2[,"mean_sFI"]==max(abp_notrans_Rvs1x_w2[,"mean_sFI"],na.rm=TRUE)),"mean_t"]->t0_abp_Rvs1x
abp_notrans_Rvs2x_w2[which(abp_notrans_Rvs2x_w2[,"mean_sFI"]==max(abp_notrans_Rvs2x_w2[,"mean_sFI"],na.rm=TRUE)),"mean_t"]->t0_abp_Rvs2x
abp_notrans_2xBAR_w2[which(abp_notrans_2xBAR_w2[,"mean_sFI"]==max(abp_notrans_2xBAR_w2[,"mean_sFI"],na.rm=TRUE)),"mean_t"]->t0_abp_2xBAR
abp_notrans_1xBAR_w2[which(abp_notrans_1xBAR_w2[,"mean_sFI"]==max(abp_notrans_1xBAR_w2[,"mean_sFI"],na.rm=TRUE)),"mean_t"]->t0_abp_1xBAR

#abp1mCh times from sla1 co-tag
time(abpmch_notrans_1xRvs$ts)[which(abpmch_notrans_1xRvs$ts[,"mean_sFI"]==max(abpmch_notrans_1xRvs$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abpmch_1xRvs
time(abpmch_notrans_2xRvs$ts)[which(abpmch_notrans_2xRvs$ts[,"mean_sFI"]==max(abpmch_notrans_2xRvs$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abpmch_2xRvs
time(abpmch_notrans_1xBar$ts)[which(abpmch_notrans_1xBar$ts[,"mean_sFI"]==max(abpmch_notrans_1xBar$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abpmch_1xBar
time(abpmch_notrans_2xBar$ts)[which(abpmch_notrans_2xBar$ts[,"mean_sFI"]==max(abpmch_notrans_2xBar$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abpmch_2xBar
time(abpmch_notrans_rvsdel$ts)[which(abpmch_notrans_rvsdel$ts[,"mean_sFI"]==max(abpmch_notrans_rvsdel$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abpmch_rvsdel
print("time abpmch ok")

#abp1mch times from rvs co-tag
time(abpmch_notrans_1xRvs_rvs$ts)[which(abpmch_notrans_1xRvs_rvs$ts[,"mean_sFI"]==max(abpmch_notrans_1xRvs_rvs$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abpmch_1xRvs_rvs
time(abpmch_notrans_2xRvs_rvs$ts)[which(abpmch_notrans_2xRvs_rvs$ts[,"mean_sFI"]==max(abpmch_notrans_2xRvs_rvs$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abpmch_2xRvs_rvs
time(abpmch_notrans_1xBar_rvs$ts)[which(abpmch_notrans_1xBar_rvs$ts[,"mean_sFI"]==max(abpmch_notrans_1xBar_rvs$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abpmch_1xBar_rvs
time(abpmch_notrans_2xBar_rvs$ts)[which(abpmch_notrans_2xBar_rvs$ts[,"mean_sFI"]==max(abpmch_notrans_2xBar_rvs$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abpmch_2xBar_rvs

print("time abpmch rvs ok")


#output nice and usable data
## haploid

#sla1
#sla1_wt<-gen.data(WTsla1,sla1_transf, NA, NA, t0=my_t0, zero=0)
sla823<-gen.data(wtsla12017,transformation_template,n=NA,sn=NA)
sla1_141geneva<-gen.data(wtsla1_141geneva,transformation_template,n=NA,sn=NA)
sla1_hd<-gen.data(wtsla1_hd,transformation_template,n=NA,sn=NA)
#sla1<-gen.data(sla1_notrans,transformation_template,n=NA,sn=NA, zero=0, t0=t0_abp)
print("gen sla1ok")

#mutant
rvsdup<-gen.data(rvsdup_sla1,transformation_template,n=NA,sn=NA)
delsh3dup<-gen.data(delsh3dup_sla1,transformation_template,n=NA,sn=NA)
delsh3<-gen.data(delsh3_sla1,transformation_template,n=NA,sn=NA)
sla141_rvsdel<-gen.data(delrvs_sla1,transformation_template,n=NA,sn=NA)

#rvs
rvs_wt<-gen.data(WTrvs_gen3131,transformation_template,n=53.2,sn=5.2, t0=t0_rvs)
rvs_dup<-gen.data(rvs161d_167d,transformation_template,n=82.7 ,sn=7.5, t0=t0_rvsdup)

delsh3_dup<-gen.data(delsh3_dup_sorted,transformation_template,n=43.6 ,sn=9.6, t0=t0_delsh3dup)
delsh3_g<-gen.data(delsh3_g_woflalign,transformation_template,n=30.1,sn=9.9, t0=t0_delsh3)

#abp1_w2 data??
abp_sla1_1x_w2<-gen.data(abp_notrans_Rvs1x_w2,NULL,n=260.7,sn=21.3,rescale.n=1, t0=t0_abp_Rvs1x)
abp_sla1_2x_w2<-gen.data(abp_notrans_Rvs2x_w2,NULL,n=260.7,sn=21.3,rescale.n=1, t0=t0_abp_Rvs2x)
abp_sla1_1xBAR_w2<-gen.data(abp_notrans_1xBAR_w2,NULL,n=223.6,sn=19.2,rescale.n=1,t0=t0_abp_1xBAR)
abp_sla1_2xBAR_w2<-gen.data(abp_notrans_2xBAR_w2,NULL,n=245.8,sn=18.4,rescale.n=1,t0=t0_abp_2xBAR)
print("gen abp okok")


#abp1_gfp data, numbers from single tag quantification

abpgfp_delrvs<-gen.data(delrvs_notrans_abp1gfp,transformation_template,n=235.3,sn=16.3,t0=t0_abp_delrvsgfp)
abpgfp_delsh3<-gen.data(delsh3_notrans_abp1gfp,transformation_template,n=172.6,sn=12.9,t0=t0_abp_delsh3gfp)
abpgfp_wt<-gen.data(wt_notrans_abp1gfp,transformation_template,n=253.1,sn=19.9,t0=t0_abp_wtgfp)

print("gen abpgfp ok")


#abp1 mch SC tracking from sla1 co-tagged strains
#numbers from sla1 co-tag
abpmch_1x_sla1_no<-gen.data(abpmch_notrans_1xRvs,transformation_template,n=360.4,sn=37.7,rescale.n=1, t0=t0_abpmch_1xRvs)
abpmch_2x_sla1_no<-gen.data(abpmch_notrans_2xRvs,transformation_template,n=329.4 ,sn=41.0,rescale.n=1, t0=t0_abpmch_2xRvs)
abpmch_1xBAR_sla1_no<-gen.data(abpmch_notrans_1xBar,transformation_template,n=341.9,sn=37.6,rescale.n=1,t0=t0_abpmch_1xBar)
abpmch_2xBAR_sla1_no<-gen.data(abpmch_notrans_2xBar,transformation_template,n=277.9,sn=33.8,rescale.n=1,t0=t0_abpmch_2xBar)
#abpmch_rvsdel<-gen.data(abpmch_notrans_rvsdel,transformation_template,n=384.5,sn=35.9,rescale.n=1,t0=t0_abpmch_rvsdel) mky3297
abpmch_rvsdel<-gen.data(abpmch_notrans_rvsdel,transformation_template,n=372.4,sn=50.6,rescale.n=1,t0=t0_abpmch_rvsdel)


#numbers from rvs co-tag, profiles from sla1 co-tag
abpmch_1x<-gen.data(abpmch_notrans_1xRvs,transformation_template,n=285.2,sn=27.1,rescale.n=1, t0=t0_abpmch_1xRvs)
abpmch_2x<-gen.data(abpmch_notrans_2xRvs,transformation_template,n=265.8 ,sn=19.9,rescale.n=1, t0=t0_abpmch_2xRvs)
abpmch_1xBAR<-gen.data(abpmch_notrans_1xBar,transformation_template,n=223.6,sn=19.2,rescale.n=1,t0=t0_abpmch_1xBar)
abpmch_2xBAR<-gen.data(abpmch_notrans_2xBar,transformation_template,n=245.8,sn=18.4,rescale.n=1,t0=t0_abpmch_2xBar)
#abpmch_rvsdel<-gen.data(abpmch_notrans_rvsdel,transformation_template,n=384.5,sn=35.9,rescale.n=1,t0=t0_abpmch_rvsdel) mky3297

#numbers from rvs co-tag, profiles from rvs co-tag
abpmch_1x_rvs<-gen.data(abpmch_notrans_1xRvs_rvs,transformation_template,n=285.2,sn=27.1,rescale.n=1, t0=t0_abpmch_1xRvs_rvs)
abpmch_2x_rvs<-gen.data(abpmch_notrans_2xRvs_rvs,transformation_template,n=265.8 ,sn=19.9,rescale.n=1, t0=t0_abpmch_2xRvs_rvs)
abpmch_1xBAR_rvs<-gen.data(abpmch_notrans_1xBar_rvs,transformation_template,n=223.6,sn=19.2,rescale.n=1,t0=t0_abpmch_1xBar_rvs)
abpmch_2xBAR_rvs<-gen.data(abpmch_notrans_2xBar_rvs,transformation_template,n=245.8,sn=18.4,rescale.n=1,t0=t0_abpmch_2xBar_rvs)


print("gen abpmch okok")
#time for sla1
#wt
#tsla823=sla823[,"t"]-sla823[1,"t"]
#tsla_141geneva=sla1_141geneva[,"t"]-sla1_141geneva[1,"t"]
#tsla_hd=sla1_hd[,"t"]-sla1_hd[1,"t"]

####mutant
#trvsdup=rvsdup[,"t"]-rvsdup[1,"t"]
#tdelsh3dup=delsh3dup[,"t"]-delsh3dup[1,"t"]
#tdelsh3=delsh3[,"t"]-delsh3[1,"t"]
#tsla141_rvsdel=sla141_rvsdel[,"t"]-sla141_rvsdel[1,"t"]

#set initial y position to 0
#rvs
x_rvs_dup<-mean(rvs_dup[1:25,"x"])
x_3131<-mean(rvs_wt[1:25,"x"])
x_delsh3_sorted<-mean(delsh3_dup[1:10,"x"])
x_delsh3_g<-mean(delsh3_g[1:25,"x"])

#sla1
xsla823<-mean(sla823[1:125,"x"])
xsla1_141geneva<-mean(sla1_141geneva[1:125,"x"])
xsla1_hd<-mean(sla1_hd[1:125,"x"])
xrvsdup<-mean(rvsdup[1:125,"x"])
xdelsh3dup<-mean(delsh3dup[1:125,"x"])
xdelsh3<-mean(delsh3[1:185,"x"])
#xsla823_inpdel<-mean(sla823_inpdel[1:25,"x"])
xsla141_rvsdel<-mean(sla141_rvsdel[1:165,"x"])
print("xsla1ok")

#abp_GFP
x_abpgfp_delrvs<-mean(abpgfp_delrvs[1:25,"x"])
x_abpgfp_delsh3<-mean(abpgfp_delsh3[1:25,"x"])
x_abpgfp_wt<-mean(abpgfp_wt[1:10,"x"])

#abp1 mCH
#x_abpmch<-mean(rabpmch_1x[1:25,"x"])
x_abpmch1x<-mean(abpmch_1x[1:25,"x"])
x_abpmch2x<-mean(abpmch_2x[1:25,"x"])
x_abpmch1xBar<-mean(abpmch_1xBAR[1:10,"x"])
x_abpmch2xBar<-mean(abpmch_2xBAR[1:25,"x"])
x_abpmchrvsdel<-mean(abpmch_rvsdel[1:25,"x"])

x_abpmch1x_rvs<-mean(abpmch_1x_rvs[1:25,"x"])
x_abpmch2x_rvs<-mean(abpmch_2x_rvs[1:25,"x"])
x_abpmch1xBar_rvs<-mean(abpmch_1xBAR_rvs[1:10,"x"])
x_abpmch2xBar_rvs<-mean(abpmch_2xBAR_rvs[1:25,"x"])
print("xapbpmchok")


cols_blue<-brewer.pal(n=9, name="Blues")
cols_rdpu<-brewer.pal(n=9, name="RdPu")

##with delsh3-duplicated
pdf("all_haploid_2020_16.pdf")
#_3: old 1xBAR analysis_p1_2, abp1 numbers w/ sla1 co-tag
#_4: new 1xBAR with percentile=2, abp1 numbers w/ sla1 co-tag
#_5: new 1xBAR w/ percentil=2, abp1 numbers w/ rvs co-tag
#_6: new 2xRVS w/ percnetile =2, abp1 numbers w/ rvs co-tag
#_7: new 2xBAR w/ percentile=2, abp1 numbers w/ rvs co-tag
#_8: new 2xBAR w/ percentile=2, abp1 numbers w/ rvs co-tag, re-aligned without 2,16,31,40,41
#_9:8+ includes rvsdel
#10: includes abpmcherry from rvs co-tag strains
#11: includes abpgfp
#12: realigned rvsdel_abpgfp after sorting tracks
#13: includes wt 823 rev aligned
#14: numbers for rvsdel from mky3297, rvsdel sla1 co-tag
#15: numbers for rvsdel from mky1801, rvsdel sla1 co-tag

#sla1
myplot(sla823[,"t"]-13.5,sla823[,"x"]-xsla823,sla823[,"t.err"],sla823[,"x.err"],line.col="#023858", xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-10,10),ylim=c(-25,200))
#myplot(tsla_141geneva-14.7,sla1_141geneva[,"x"]-xsla1_141geneva,sla1_141geneva[,"t.err"],sla1_141geneva[,"x.err"],line.col=cols_blue[8],hold_on=TRUE,line.lwd=3,deltat=0.25)
#myplot(tsla_hd-23.5,sla1_hd[,"x"]-xsla1_hd,sla1_hd[,"t.err"],sla1_hd[,"x.err"],line.col=cols_blue[7],hold_on=TRUE,line.lwd=3,deltat=0.25)

###mut
myplot(rvsdup[,"t"]-28.5,rvsdup[,"x"]-xrvsdup,rvsdup[,"t.err"],rvsdup[,"x.err"],line.col=cols_rdpu[4],hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(delsh3dup[,"t"]-15,delsh3dup[,"x"]-xdelsh3dup,delsh3dup[,"t.err"],delsh3dup[,"x.err"],line.col=cols_rdpu[8],hold_on=TRUE,line.lwd=3,deltat=0.25)

#myplot(tsla823_inpdel-5.5,sla823_inpdel[,"x"]-xsla1_823_inpdel,sla823_inpdel[,"t.err"],sla823_inpdel[,"x.err"],line.col=cols_rdpu[7],hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(delsh3[,"t"]-26.5,delsh3[,"x"]-xdelsh3,delsh3[,"t.err"],delsh3[,"x.err"],line.col= cols_rdpu[6],hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(sla141_rvsdel[,"t"]-34,sla141_rvsdel[,"x"]-xsla141_rvsdel,sla141_rvsdel[,"t.err"],sla141_rvsdel[,"x.err"],line.col=cols_rdpu[5],hold_on=TRUE,line.lwd=3,deltat=0.25)
title(main="sla1-GFP", sub="time aligned to movement")
legend("topleft",c("sla1 823","delsh3 dup","delsh3", "rvsdel"),lty=1,col=c("#023858", cols_rdpu[8], cols_rdpu[6], cols_rdpu[5]),bty='n', cex=0.75)




##rvs movement
myplot(rvs_dup[,"t"],rvs_dup[,"x"]-x_rvs_dup,rvs_dup[,"t.err"],rvs_dup[,"x.err"],line.col="#00FFFF", xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-10,10),ylim=c(-25,200))
#myplot(t_rvs551x529_d-1.9,rvs551x529_d[,"x"]-x_rvs551x529_d,rvs551x529_d[,"t.err"],rvs551x529_d[,"x.err"],line.col="#660033", hold_on=TRUE, line.lwd=3,deltat=0.25)

myplot(rvs_wt[,"t"],rvs_wt[,"x"]-x_3131,rvs_wt[,"t.err"],rvs_wt[,"x.err"],line.col="#669900", hold_on=TRUE, line.lwd=3,deltat=0.25)
myplot(delsh3_dup[,"t"],delsh3_dup[,"x"]-x_delsh3_sorted,delsh3_dup[,"t.err"],delsh3_dup[,"x.err"],line.col="#FF6600", hold_on=TRUE, line.lwd=3,deltat=0.25)
myplot(delsh3_g[,"t"],delsh3_g[,"x"]-x_delsh3_g,delsh3_g[,"t.err"],delsh3_g[,"x.err"],line.col="#996600", hold_on=TRUE, line.lwd=3,deltat=0.25)
title(main="Rvs167-GFP", sub="time aligned to rvs max")
legend("topleft",c("rvs dup","rvs wt","delsh3 dup","delsh3"),lty=1,col=c("#00FFFF", "#669900", "#FF6600", "#996600"),bty='n', cex=0.75)


#rvs intensity
myplot(rvs_dup[,"t"],rvs_dup[,"n"],rvs_dup[,"t.err"],rvs_dup[,"n.err"],line.col="#000000",xlab="time(s)",ylab="# molecules",xlim=c(-20,20), ylim=c(0,200))
myplot(rvs_wt[,"t"],rvs_wt[,"n"],rvs_wt[,"t.err"],rvs_wt[,"n.err"],line.col="#669900",hold_on=TRUE)
myplot(delsh3_dup[,"t"],delsh3_dup[,"n"],delsh3_dup[,"t.err"],delsh3_dup[,"n.err"],line.col="#FF6600",hold_on=TRUE)
myplot(delsh3_g[,"t"],delsh3_g[,"n"],delsh3_g[,"t.err"],delsh3_g[,"n.err"],line.col="#996600",hold_on=TRUE)

title(main="Rvs167-GFP", sub="time aligned to rvs max ")
legend("topleft",c("rvs dup","rvs wt","delsh3 dup","delsh3"),lty=1,col=c("#000000", "#669900", "#FF6600", "#996600" ),bty='n', cex=0.75)

#abp intensity .W2
myplot(abp_sla1_2xBAR_w2[,"t"],abp_sla1_2xBAR_w2[,"n"],abp_sla1_2xBAR_w2[,"t.err"],abp_sla1_2xBAR_w2[,"n.err"],line.col="#660099",xlab="time(s)",ylab="# molecules",xlim=c(-20,20), ylim=c(0,500))
myplot(abp_sla1_1xBAR_w2[,"t"],abp_sla1_1xBAR_w2[,"n"],abp_sla1_1xBAR_w2[,"t.err"],abp_sla1_1xBAR_w2[,"n.err"],line.col="#66cc99",hold_on=TRUE,line.lwd=3,deltat=0.45)
myplot(abp_sla1_2x_w2[,"t"],abp_sla1_2x_w2[,"n"],abp_sla1_2x_w2[,"t.err"],abp_sla1_2x_w2[,"n.err"],line.col="#CC0066",hold_on=TRUE,line.lwd=3,deltat=0.45)
myplot(abp_sla1_1x_w2[,"t"],abp_sla1_1x_w2[,"n"],abp_sla1_1x_w2[,"t.err"],abp_sla1_1x_w2[,"n.err"],line.col="#CC0099",hold_on=TRUE,line.lwd=3,deltat=0.45)

legend("topleft",c("abp1_sla1 2xRvs","abp1_sla1 2xBAR", "abp1_sla1 1xBAR"),lty=1,col=c("#CC0066", "#660099", "#66cc99"),bty='n', cex=0.75)
title(main="abp sla1 w2 data")

##################################################################################################################################
#abp_mch intensity sla1 co-tag
myplot(abpmch_2x[,"t"],abpmch_2x[,"n"],abpmch_2x[,"t.err"],abpmch_2x[,"n.err"],line.col="#CC0066",xlab="time(s)",ylab="# molecules",xlim=c(-17,17), ylim=c(0,600))
myplot(abpmch_1x[,"t"],abpmch_1x[,"n"],abpmch_1x[,"t.err"],abpmch_1x[,"n.err"],line.col="#000000",hold_on=TRUE,line.lwd=3,deltat=0.45)
myplot(abpmch_1xBAR[,"t"],abpmch_1xBAR[,"n"],abpmch_1xBAR[,"t.err"],abpmch_1xBAR[,"n.err"],line.col="#66cc99",hold_on=TRUE,line.lwd=3,deltat=0.45)
myplot(abpmch_2xBAR[,"t"],abpmch_2xBAR[,"n"],abpmch_2xBAR[,"t.err"],abpmch_2xBAR[,"n.err"],line.col="#660099",hold_on=TRUE,line.lwd=3,deltat=0.45)
myplot(abpmch_rvsdel[,"t"],abpmch_rvsdel[,"n"],abpmch_rvsdel[,"t.err"],abpmch_rvsdel[,"n.err"],line.col="#ccddee",hold_on=TRUE,line.lwd=3,deltat=0.45)
legend("topleft",c("abp1mch 1xRvs", "abp1mch 2xRvs","abp1mch 2xBAR", "abp1mch 1xBAR", "abp1mch rvsdel"),lty=1,col=c("#000000", "#CC0066", "#660099","#66cc99","#ccddee"),bty='n', cex=0.75)
title(main="abp mch sla1 co-tag")

##abp1 movement
myplot(abpmch_2x[,"t"],abpmch_2x[,"x"]-x_abpmch2x,abpmch_2x[,"t.err"],abpmch_2x[,"x.err"],line.col="#CC0066", xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-17,17),ylim=c(-25,300))
myplot(abpmch_1x[,"t"],abpmch_1x[,"x"]-x_abpmch1x,abpmch_1x[,"t.err"],abpmch_1x[,"x.err"],line.col="#000000", hold_on=TRUE, line.lwd=3,deltat=0.25)
myplot(abpmch_1xBAR[,"t"],abpmch_1xBAR[,"x"]-x_abpmch1xBar,abpmch_1xBAR[,"t.err"],abpmch_1xBAR[,"x.err"],line.col="#66cc99", hold_on=TRUE, line.lwd=3,deltat=0.25)
myplot(abpmch_2xBAR[,"t"],abpmch_2xBAR[,"x"]-x_abpmch2xBar,abpmch_2xBAR[,"t.err"],abpmch_2xBAR[,"x.err"],line.col="#660099", hold_on=TRUE, line.lwd=3,deltat=0.25)
myplot(abpmch_rvsdel[,"t"],abpmch_rvsdel[,"x"]-x_abpmchrvsdel,abpmch_rvsdel[,"t.err"],abpmch_rvsdel[,"x.err"],line.col="#ccddee", hold_on=TRUE, line.lwd=3,deltat=0.25)
title(main="Abp1-mch sla1 co-tag", sub="time aligned to abp1 max")
legend("topleft",c("abp1mch 1xRvs", "abp1mch 2xRvs","abp1mch 2xBAR", "abp1mch 1xBAR", "abpmch rvsdel"),lty=1,col=c("#000000", "#CC0066", "#660099","#66cc99","#ccddee"),bty='n', cex=0.75)

######################################################################################################################
#abp_mch intensity rvs co-tag
myplot(abpmch_2x_rvs[,"t"],abpmch_2x_rvs[,"n"],abpmch_2x_rvs[,"t.err"],abpmch_2x_rvs[,"n.err"],line.col="#CC0066",xlab="time(s)",ylab="# molecules",xlim=c(-10,10), ylim=c(0,500))
myplot(abpmch_1x_rvs[,"t"],abpmch_1x_rvs[,"n"],abpmch_1x_rvs[,"t.err"],abpmch_1x_rvs[,"n.err"],line.col="#000000",hold_on=TRUE,line.lwd=3,deltat=0.45)
myplot(abpmch_1xBAR_rvs[,"t"],abpmch_1xBAR_rvs[,"n"],abpmch_1xBAR_rvs[,"t.err"],abpmch_1xBAR_rvs[,"n.err"],line.col="#66cc99",hold_on=TRUE,line.lwd=3,deltat=0.45)
myplot(abpmch_2xBAR_rvs[,"t"],abpmch_2xBAR_rvs[,"n"],abpmch_2xBAR_rvs[,"t.err"],abpmch_2xBAR_rvs[,"n.err"],line.col="#660099",hold_on=TRUE,line.lwd=3,deltat=0.45)
legend("topleft",c("abp1mch 1xRvs", "abp1mch 2xRvs","abp1mch 2xBAR", "abp1mch 1xBAR"),lty=1,col=c("#000000", "#CC0066", "#660099","#66cc99"),bty='n', cex=0.75)
title(main="abp mch rvs co-tag")

##abp1 movement rvs co-tag 
myplot(abpmch_2x_rvs[,"t"],abpmch_2x_rvs[,"x"]-x_abpmch2x_rvs,abpmch_2x_rvs[,"t.err"],abpmch_2x_rvs[,"x.err"],line.col="#CC0066", xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-17,17),ylim=c(-25,300))
myplot(abpmch_1x_rvs[,"t"],abpmch_1x_rvs[,"x"]-x_abpmch1x_rvs,abpmch_1x_rvs[,"t.err"],abpmch_1x_rvs[,"x.err"],line.col="#000000", hold_on=TRUE, line.lwd=3,deltat=0.25)
myplot(abpmch_1xBAR_rvs[,"t"],abpmch_1xBAR_rvs[,"x"]-x_abpmch1xBar_rvs,abpmch_1xBAR_rvs[,"t.err"],abpmch_1xBAR_rvs[,"x.err"],line.col="#66cc99", hold_on=TRUE, line.lwd=3,deltat=0.25)
myplot(abpmch_2xBAR_rvs[,"t"],abpmch_2xBAR_rvs[,"x"]-x_abpmch2xBar_rvs,abpmch_2xBAR_rvs[,"t.err"],abpmch_2xBAR_rvs[,"x.err"],line.col="#660099", hold_on=TRUE, line.lwd=3,deltat=0.25)
title(main="Abp1-mch rvs co-tag", sub="time aligned to abp1 max")
legend("topleft",c("abp1mch 1xRvs", "abp1mch 2xRvs","abp1mch 2xBAR", "abp1mch 1xBAR"),lty=1,col=c("#000000", "#CC0066", "#660099","#66cc99"),bty='n', cex=0.75)

#abpmch intensity sla1 co-tag
myplot(abpmch_1x_sla1_no[,"t"],abpmch_1x_sla1_no[,"n"],abpmch_1x_sla1_no[,"t.err"],abpmch_1x_sla1_no[,"n.err"],line.col="#CC0066",xlab="time(s)",ylab="# molecules",xlim=c(-17,17), ylim=c(0,600))
myplot(abpmch_2x_sla1_no[,"t"],abpmch_2x_sla1_no[,"n"],abpmch_2x_sla1_no[,"t.err"],abpmch_2x_sla1_no[,"n.err"],line.col="#000000",hold_on=TRUE,line.lwd=3,deltat=0.45)
myplot(abpmch_1xBAR_sla1_no[,"t"],abpmch_1xBAR_sla1_no[,"n"],abpmch_1xBAR_sla1_no[,"t.err"],abpmch_1xBAR_sla1_no[,"n.err"],line.col="#66cc99",hold_on=TRUE,line.lwd=3,deltat=0.45)
myplot(abpmch_2xBAR_sla1_no[,"t"],abpmch_2xBAR_sla1_no[,"n"],abpmch_2xBAR_sla1_no[,"t.err"],abpmch_2xBAR_sla1_no[,"n.err"],line.col="#660099",hold_on=TRUE,line.lwd=3,deltat=0.45)
legend("topleft",c("abp1mch 1xRvs", "abp1mch 2xRvs","abp1mch 2xBAR", "abp1mch 1xBAR"),lty=1,col=c("#000000", "#CC0066", "#660099","#66cc99"),bty='n', cex=0.75)
title(main="abp mch sla1 co-tag profile, numbers")



##################################################################################################################################
#abp_GFP
myplot(abpgfp_delrvs[,"t"],abpgfp_delrvs[,"n"],abpgfp_delrvs[,"t.err"],abpgfp_delrvs[,"n.err"],line.col="#CC0066",xlab="time(s)",ylab="# molecules",xlim=c(-17,17), ylim=c(0,500))
myplot(abpgfp_delsh3[,"t"],abpgfp_delsh3[,"n"],abpgfp_delsh3[,"t.err"],abpgfp_delsh3[,"n.err"],line.col="#000000",hold_on=TRUE,line.lwd=3,deltat=0.45)
myplot(abpgfp_wt[,"t"],abpgfp_wt[,"n"],abpgfp_wt[,"t.err"],abpgfp_wt[,"n.err"],line.col="#66cc99",hold_on=TRUE,line.lwd=3,deltat=0.45)
legend("topleft",c("abp1gfp delsh3", "abp1gfp delrvs","abp1gfp wt"),lty=1,col=c("#000000", "#CC0066","#66cc99"),bty='n', cex=0.75)
title(main="Abp1-gfp", sub="time aligned to abp1 max")

##abp1 movement rvs co-tag
myplot(abpgfp_delrvs[,"t"],abpgfp_delrvs[,"x"]-x_abpgfp_delrvs,abpgfp_delrvs[,"t.err"],abpgfp_delrvs[,"x.err"],line.col="#CC0066", xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-17,17),ylim=c(-25,300))
myplot(abpgfp_delsh3[,"t"],abpgfp_delsh3[,"x"]-x_abpgfp_delsh3,abpgfp_delsh3[,"t.err"],abpgfp_delsh3[,"x.err"],line.col="#000000", hold_on=TRUE, line.lwd=3,deltat=0.25)
myplot(abpgfp_wt[,"t"],abpgfp_wt[,"x"]-x_abpgfp_wt,abpgfp_wt[,"t.err"],abpgfp_wt[,"x.err"],line.col="#66cc99", hold_on=TRUE, line.lwd=3,deltat=0.25)
title(main="Abp1-gfp", sub="time aligned to abp1 max")
legend("topleft",c("abp1gfp delsh3", "abp1gfp delrvs","abp1gfp wt"),lty=1,col=c("#000000", "#CC0066","#66cc99"),bty='n', cex=0.75)



dev.off()

