#plot the data generated by the alignment
library(RColorBrewer)
source("/Users/deepikaa/Desktop/data_desktop/Doc/align_tracks.R")
mnorm<-function(x) return((x-min(x,na.rm=T))/(max(x,na.rm=T)-min(x,na.rm=T)))
##########haploid

#####load data
#SLA1
#upto g -> get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/WT/sla1egfp/2017_06_12_823/tracks.Rdata"))->wtsla12017
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/WT/sla1egfp/2017_06_12_823/test_tracks.Rdata"))->wtsla12017
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Rvsduplication/Sla1/2017_06_12_161d100_167d100_823_5a/tracks.Rdata"))->rvsdup_sla1
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Rvsduplication/Rvs_delsh3/2017_12_29/sh3dup_823_5a/tracks.Rdata"))->delsh3dup_sla1
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/rvs_delsh3/rvs167_delsh3_sla1_egfp/2015_04_02/tracks.Rdata"))->delsh3_sla1
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/delrvs167/2020_02_29/1802/percentile_1_5/fimax_true/tracks.Rdata"))->delrvs_sla1_new
##--> sla1 2020_01_19 (ie 2021)
#abp mcherry from mcherry_sla1co-tag
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_07_31/823_mch/tracks.Rdata"))->abpmch_notrans_1xRvs
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_02_18/823/tracks.Rdata"))->abpmch_notrans_1xRvs_sla1
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_07_26/2xRVS823_3706/tracks.Rdata"))->abpmch_notrans_2xRvs_sla1
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_07_27/1xbar_823_3292/tracks.Rdata"))->abpmch_notrans_1xBar_sla1
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_07_27/2xbar_823_3826/tracks.Rdata"))->abpmch_notrans_2xBar_sla1
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_02_06/1801/tracks.Rdata"))->abpmch_notrans_rvsdel_sla1
#trasnformations for sla1
#upto g -> get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments/abpmch_Sla1823_mytrasf.Rdata"))->sla1823_transf
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments/abpmch_Sla1823_11_mytrasf.Rdata"))->sla1823_transf
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments_haploid/rvsdup_sla1_3706_mytrasf.Rdata"))->sla13706_transf
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments_haploid/rvsdelsh3_sla1_3292_mytrasf.Rdata"))->sla13292_transf
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments_haploid/rvsdelsh3_sla1_3826_tracks2_e_mytrasf.Rdata"))->sla13826_transf
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments/fimax_false_1801/abpmch_delrvs1801_mytrasf.Rdata"))->sla1801_transf
#abp1mCh times from sla1 co-tag
time(abpmch_notrans_1xRvs_sla1$ts)[which(abpmch_notrans_1xRvs_sla1$ts[,"mean_sFI"]==max(abpmch_notrans_1xRvs_sla1$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abpmch_1xRvs_sla1
time(abpmch_notrans_2xRvs_sla1$ts)[which(abpmch_notrans_2xRvs_sla1$ts[,"mean_sFI"]==max(abpmch_notrans_2xRvs_sla1$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abpmch_2xRvs_sla1
time(abpmch_notrans_1xBar_sla1$ts)[which(abpmch_notrans_1xBar_sla1$ts[,"mean_sFI"]==max(abpmch_notrans_1xBar_sla1$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abpmch_1xBar_sla1
time(abpmch_notrans_2xBar_sla1$ts)[which(abpmch_notrans_2xBar_sla1$ts[,"mean_sFI"]==max(abpmch_notrans_2xBar_sla1$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abpmch_2xBar_sla1
time(abpmch_notrans_rvsdel_sla1$ts)[which(abpmch_notrans_rvsdel_sla1$ts[,"mean_sFI"]==max(abpmch_notrans_rvsdel_sla1$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abpmch_rvsdel_sla1
print("time abpmch ok")



##RVS
#####load data

get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/WT/Rvs167/2017_03_29_3131/tracks.Rdata"))->WTrvs3131_notrans
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/rvs_delsh3/rvs167egfp_delsh3/2016_06_02_3154_delsh3_gfp_geneva/analysis2woFlalign/tracks.Rdata"))->delsh3_g_woflalign
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Rvsduplication/Rvs167/2017_06_19/161_d100_167d3131_5b/tracks.Rdata")) -> rvs161d_167d
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Rvsduplication/Rvs_delsh3/2017_07_21/delsh3dup/tracks.Rdata")) ->delsh3_dup_sorted
#i ->get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Rvsduplication/Rvs_delsh3/2017_07_21/delsh3dup/motile_wt/motile_wt.Rdata")) ->delsh3_dup_sorted

#abp mcherry from rvs_co-tag
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_02_06/3132/test_tracks.Rdata"))->abpmch_notrans_1xRvs_rvs
#upto g, then o onwards --> tracks.Rdata, not test_tracks.
#p --> tracks2021_05_18
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_02_06/3132/tracks2021_05_18.Rdata"))->abpmch_notrans_1xRvs_rvs
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_08_11/3710/tracks.Rdata"))->abpmch_notrans_2xRvs_rvs
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_08_11/3286/tracks.Rdata"))->abpmch_notrans_1xBar_rvs
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_08_11/3714/tracks.Rdata"))->abpmch_notrans_2xBar_rvs
#trasnformations for Rvs
#upto g -> get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments/abpmch_Sla1823_mytrasf.Rdata"))->sla1823_transf
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments/abpmch_Rvs3132_e_mytrasf.Rdata"))->rvs3132_transf---> "o"
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments/abpmch_Rvs3132_d_mytrasf.Rdata"))->rvs3132_transf 
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments/abpmch_Rvs3132_f_mytrasf.Rdata"))->rvs3132_transf 
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments_haploid/rvsdup_3710_mytrasf.Rdata"))->rvs3710_transf
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments_haploid/rvsdelsh3_3714_c_mytrasf.Rdata"))->rvs3714_transf
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments_haploid/rvsdelsh3_3286_mytrasf.Rdata"))->rvs3286_transf
#abp1mch times from rvs co-tag
time(abpmch_notrans_1xRvs_rvs$ts)[which(abpmch_notrans_1xRvs_rvs$ts[,"mean_sFI"]==max(abpmch_notrans_1xRvs_rvs$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abpmch_1xRvs_rvs
time(abpmch_notrans_2xRvs_rvs$ts)[which(abpmch_notrans_2xRvs_rvs$ts[,"mean_sFI"]==max(abpmch_notrans_2xRvs_rvs$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abpmch_2xRvs_rvs
time(abpmch_notrans_1xBar_rvs$ts)[which(abpmch_notrans_1xBar_rvs$ts[,"mean_sFI"]==max(abpmch_notrans_1xBar_rvs$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abpmch_1xBar_rvs
time(abpmch_notrans_2xBar_rvs$ts)[which(abpmch_notrans_2xBar_rvs$ts[,"mean_sFI"]==max(abpmch_notrans_2xBar_rvs$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abpmch_2xBar_rvs


#generate a template transformation matrix to fool gen.data
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/DC/wt/Rvs167/110824_mytrasf.Rdata"))->transformation_template
transformation_template<-0*transformation_template


##################################################sla1 with transformation
#sla1_wt<-gen.data(WTsla1,sla1_transf, NA, NA, t0=my_t0, zero=0)
#sla1
sla823<-gen.data(wtsla12017,sla1823_transf,n=NA,sn=NA,t0=t0_abpmch_1xRvs_sla1)
rvsdup<-gen.data(rvsdup_sla1,sla13706_transf,n=NA,sn=NA,t0=t0_abpmch_2xRvs_sla1)
delsh3dup<-gen.data(delsh3dup_sla1,sla13826_transf,n=NA,sn=NA,t0=t0_abpmch_2xBar_sla1)
delsh3<-gen.data(delsh3_sla1,sla13292_transf,n=NA,sn=NA,t0=t0_abpmch_1xBar_sla1)
sla1_rvsdel<-gen.data(delrvs_sla1_new,sla1801_transf,n=NA,sn=NA,t0=t0_abpmch_rvsdel_sla1)
#abp1 mch SC tracking from sla1 co-tagged strains
#numbers from sla1 co-tag set2 2
#numbers from yellow coloured cells, data_desktop/nuf2/excel/numbers_nuf2_2018_11_c, all on the same day except rvsdel
abpmch_1x_sla1_no2<-gen.data(abpmch_notrans_1xRvs_sla1,transformation_template,n=344.8,sn=27.8,rescale.n=1, t0=t0_abpmch_1xRvs_sla1)
abpmch_2x_sla1_no2<-gen.data(abpmch_notrans_2xRvs_sla1,transformation_template,n=318.8 ,sn=28.1,rescale.n=1, t0=t0_abpmch_2xRvs_sla1)
abpmch_1xBAR_sla1_no2<-gen.data(abpmch_notrans_1xBar_sla1,transformation_template,n=243.5,sn=24.6,rescale.n=1,t0=t0_abpmch_1xBar_sla1)
abpmch_2xBAR_sla1_no2<-gen.data(abpmch_notrans_2xBar_sla1,transformation_template,n=296.2,sn=25,rescale.n=1,t0=t0_abpmch_2xBar_sla1)
#abpmch_rvsdel<-gen.data(abpmch_notrans_rvsdel,transformation_template,n=384.5,sn=35.9,rescale.n=1,t0=t0_abpmch_rvsdel) mky3297
abpmch_rvsdel2_sla1<-gen.data(abpmch_notrans_rvsdel_sla1,transformation_template,n=362.64,sn=39.36,rescale.n=1,t0=t0_abpmch_rvsdel_sla1)
#rvs delnumbers an average of 5 numbers, 2x data sets 1802, 1801, 4394, 3297

################################################################################rvs with transformation

rvs3132<-gen.data(WTrvs3131_notrans,rvs3132_transf,n=NA,sn=NA,t0=t0_abpmch_1xRvs_rvs)
rvsdup3710<-gen.data(rvs161d_167d,rvs3710_transf,n=NA,sn=NA,t0=t0_abpmch_2xRvs_rvs)
delsh3dup3714<-gen.data(delsh3_dup_sorted,rvs3714_transf,n=NA,sn=NA,t0=t0_abpmch_2xBar_rvs)
rvsdelsh3<-gen.data(delsh3_g_woflalign,rvs3286_transf,n=NA,sn=NA,t0=t0_abpmch_1xBar_rvs)
################################################################################
#numbers from rvs co-tag, profiles from rvs co-tag
abpmch_1x_rvs<-gen.data(abpmch_notrans_1xRvs_rvs,transformation_template,n=285.2,sn=27.1,rescale.n=1, t0=t0_abpmch_1xRvs_rvs)
abpmch_2x_rvs<-gen.data(abpmch_notrans_2xRvs_rvs,transformation_template,n=265.8 ,sn=19.9,rescale.n=1, t0=t0_abpmch_2xRvs_rvs)
abpmch_1xBAR_rvs<-gen.data(abpmch_notrans_1xBar_rvs,transformation_template,n=223.6,sn=19.2,rescale.n=1,t0=t0_abpmch_1xBar_rvs)
abpmch_2xBAR_rvs<-gen.data(abpmch_notrans_2xBar_rvs,transformation_template,n=245.8,sn=18.4,rescale.n=1,t0=t0_abpmch_2xBar_rvs)
abpmch_rvsdel<-gen.data(abpmch_notrans_rvsdel_sla1,transformation_template,n=362.64,sn=39.36,rescale.n=1,t0=t0_abpmch_rvsdel_sla1)

#abpmch_rvsdel<-gen.data(abpmch_notrans_rvsdel,transformation_template,n=384.5,sn=35.9,rescale.n=1,t0=t0_abpmch_rvsdel) mky3297

#sla1
xsla823<-mean(sla823[1:125,"x"])
xrvsdup<-mean(rvsdup[1:125,"x"])
xdelsh3dup<-mean(delsh3dup[1:125,"x"])
xdelsh3<-mean(delsh3[1:185,"x"])
#xsla823_inpdel<-mean(sla823_inpdel[1:25,"x"])
xsla1_rvsdel<-mean(sla1_rvsdel[1:165,"x"])
#rvs
x_rvs_dup<-mean(rvsdup3710[1:25,"x"])
x_3131<-mean(rvs3132[1:25,"x"])
x_delsh3_sorted<-mean(delsh3dup3714[1:10,"x"])
x_delsh3_g<-mean(delsh3[1:25,"x"])

#abp1 mCH
#x_abpmch<-mean(rabpmch_1x[1:25,"x"])
x_abpmch1x<-mean(abpmch_1x_sla1_no2[1:25,"x"])
x_abpmch2x<-mean(abpmch_2x_sla1_no2[1:25,"x"])
x_abpmch1xBar<-mean(abpmch_1xBAR_sla1_no2[1:10,"x"])
x_abpmch2xBar<-mean(abpmch_2xBAR_sla1_no2[1:25,"x"])
x_abpmchrvsdel<-mean(abpmch_rvsdel[1:25,"x"])

x_abpmch1x_rvs<-mean(abpmch_1x_rvs[1:25,"x"])
x_abpmch2x_rvs<-mean(abpmch_2x_rvs[1:25,"x"])
x_abpmch1xBar_rvs<-mean(abpmch_1xBAR_rvs[1:10,"x"])
x_abpmch2xBar_rvs<-mean(abpmch_2xBAR_rvs[1:25,"x"])

cols_blue<-brewer.pal(n=9, name="Blues")
cols_rdpu<-brewer.pal(n=9, name="RdPu")

##with delsh3-duplicated
pdf("all_haploid_2021_p.pdf")

#b, with transformation matrix that includes all dc tracks for delsh3dup_sla1
#a, with 04, 25, 27,28, 30 removed
#apparently no difference??
#c with new delsh3dup abp1mch SC tracks.Rdata after cleanup, and redoing the DC alignment with this new tracks.Rdata
#d with abp1 nombers from 2020_01_19_haploid, set2
#e with new tracks.data from abpmch 2xBAR after removing tracks 11,14,28,31 from the tracks folder
#f with new 2xBAR abpmch, and also redone DC alignment
#g with newly analysed 1xBAR abpmch
#h with abp_mch rvsco-tag
#i with 2xbar transformation new
#j w/ 2xbar "tracks.Rdata" instead of motile/tracks.Rdata
#k w/ 2xbar DC sorted
#l w/ 2xbar DC sorted again
myplot(sla823[,"t"],sla823[,"x"]-xsla823,sla823[,"t.err"],sla823[,"x.err"],line.col="#023858", xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-30,30),ylim=c(-25,200))
myplot(rvsdup[,"t"],rvsdup[,"x"]-xrvsdup,rvsdup[,"t.err"],rvsdup[,"x.err"],line.col=cols_rdpu[4],hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(delsh3dup[,"t"],delsh3dup[,"x"]-xdelsh3dup,delsh3dup[,"t.err"],delsh3dup[,"x.err"],line.col=cols_rdpu[8],hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(delsh3[,"t"],delsh3[,"x"]-xdelsh3,delsh3[,"t.err"],delsh3[,"x.err"],line.col= cols_rdpu[6],hold_on=TRUE,line.lwd=3,deltat=0.25)
#myplot(sla1_rvsdel[,"t"],sla1_rvsdel[,"x"]-xsla1_rvsdel,sla1_rvsdel[,"t.err"],sla1_rvsdel[,"x.err"],line.col=cols_rdpu[5],hold_on=TRUE,line.lwd=3,deltat=0.25)/
title("sla1 movement")


myplot(abpmch_1x_sla1_no2[,"t"],abpmch_1x_sla1_no2[,"n"],abpmch_1x_sla1_no2[,"t.err"],abpmch_1x_sla1_no2[,"n.err"],line.col="#000000",line.lwd=3,deltat=0.25,xlim=c(-15,15),ylim=c(-25,650))
myplot(abpmch_2x_sla1_no2[,"t"],abpmch_2x_sla1_no2[,"n"],abpmch_2x_sla1_no2[,"t.err"],abpmch_2x_sla1_no2[,"n.err"],line.col="#CC0066",hold_on=TRUE,line.lwd=3,deltat=0.45)
myplot(abpmch_2xBAR_sla1_no2[,"t"],abpmch_2xBAR_sla1_no2[,"n"],abpmch_2xBAR_sla1_no2[,"t.err"],abpmch_2xBAR_sla1_no2[,"n.err"],line.col="#660099",hold_on=TRUE,line.lwd=3,deltat=0.45)
myplot(abpmch_1xBAR_sla1_no2[,"t"],abpmch_1xBAR_sla1_no2[,"n"],abpmch_1xBAR_sla1_no2[,"t.err"],abpmch_1xBAR_sla1_no2[,"n.err"],line.col="#66cc99",hold_on=TRUE,line.lwd=3,deltat=0.45)
myplot(abpmch_rvsdel[,"t"],abpmch_rvsdel[,"n"],abpmch_rvsdel[,"t.err"],abpmch_rvsdel[,"n.err"],line.col="#ccddee",hold_on=TRUE,line.lwd=3,deltat=0.45)
legend("topleft",c("abp1mch 1xRvs", "abp1mch 2xRvs","abp1mch 2xBAR", "abp1mch 1xBAR", "abp1mch rvsdel"),lty=1,col=c("#000000", "#CC0066", "#660099","#66cc99","#ccddee"),bty='n', cex=0.75)
title(main="abp mch sla1 co-tag set2")

#######rvs
myplot(rvs3132[,"t"],rvs3132[,"x"]-x_3131,rvs3132[,"t.err"],rvs3132[,"x.err"],line.col="#023858", xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-10,10),ylim=c(-25,200))
myplot(rvsdup3710[,"t"],rvsdup3710[,"x"]-x_rvs_dup,rvsdup3710[,"t.err"],rvsdup3710[,"x.err"],line.col=cols_rdpu[4],hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(delsh3dup3714[,"t"],delsh3dup3714[,"x"]-x_delsh3_sorted,delsh3dup3714[,"t.err"],delsh3dup3714[,"x.err"],line.col=cols_rdpu[8],hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(rvsdelsh3[,"t"],rvsdelsh3[,"x"]-x_delsh3_g,rvsdelsh3[,"t.err"],rvsdelsh3[,"x.err"],line.col= cols_rdpu[6],hold_on=TRUE,line.lwd=3,deltat=0.25)
#myplot(sla1_rvsdel[,"t"],sla1_rvsdel[,"x"]-xsla1_rvsdel,sla1_rvsdel[,"t.err"],sla1_rvsdel[,"x.err"],line.col=cols_rdpu[5],hold_on=TRUE,line.lwd=3,deltat=0.25)/
title("rvs movement")


#abp_mch intensity rvs co-tag
myplot(abpmch_2x_rvs[,"t"],abpmch_2x_rvs[,"n"],abpmch_2x_rvs[,"t.err"],abpmch_2x_rvs[,"n.err"],line.col="#CC0066",xlab="time(s)",ylab="# molecules",xlim=c(-15,15), ylim=c(0,500))
myplot(abpmch_1x_rvs[,"t"],abpmch_1x_rvs[,"n"],abpmch_1x_rvs[,"t.err"],abpmch_1x_rvs[,"n.err"],line.col="#000000",hold_on=TRUE,line.lwd=3,deltat=0.45)
myplot(abpmch_1xBAR_rvs[,"t"],abpmch_1xBAR_rvs[,"n"],abpmch_1xBAR_rvs[,"t.err"],abpmch_1xBAR_rvs[,"n.err"],line.col="#66cc99",hold_on=TRUE,line.lwd=3,deltat=0.45)
myplot(abpmch_2xBAR_rvs[,"t"],abpmch_2xBAR_rvs[,"n"],abpmch_2xBAR_rvs[,"t.err"],abpmch_2xBAR_rvs[,"n.err"],line.col="#660099",hold_on=TRUE,line.lwd=3,deltat=0.45)
legend("topleft",c("abp1mch 1xRvs", "abp1mch 2xRvs","abp1mch 2xBAR", "abp1mch 1xBAR"),lty=1,col=c("#000000", "#CC0066", "#660099","#66cc99"),bty='n', cex=0.75)
title(main="abp mch rvs co-tag")

##sla1 intensity
myplot(rvsdup[,"t"],mnorm(rvsdup[,"fi"]),rvsdup[,"t.err"],rvsdup[,"fi.err"],line.col="#CC0066",line.lwd=3,deltat=0.25,xlim=c(-30,30),ylim=c(-0.1,1))
myplot(delsh3dup[,"t"],mnorm(delsh3dup[,"fi"]),delsh3dup[,"t.err"],delsh3dup[,"fi.err"],line.col="#660099",hold_on=TRUE,line.lwd=3,deltat=0.45)
myplot(sla823[,"t"],mnorm(sla823[,"fi"]),sla823[,"t.err"],sla823[,"fi.err"],line.col="#000000",hold_on=TRUE,line.lwd=3,deltat=0.45)
title("sla1 fl.int")

#comparing abp for abp and rvs co-tag
myplot(abpmch_1x_rvs[,"t"],mnorm(abpmch_1x_rvs[,"fi"]),abpmch_1x_rvs[,"t.err"],abpmch_1x_rvs[,"fi.err"],line.col="#CC0066",xlab="time(s)",ylab="# molecules",xlim=c(-15,15), ylim=c(0,1))
myplot(rvs3132[,"t"],mnorm(rvs3132[,"fi"]),rvs3132[,"t.err"],rvs3132[,"fi.err"],line.col="#CC00ee",hold_on=TRUE,line.lwd=3,deltat=0.45)
title("1xrvs")

myplot(abpmch_2x_rvs[,"t"],mnorm(abpmch_2x_rvs[,"fi"]),abpmch_2x_rvs[,"t.err"],abpmch_2x_rvs[,"fi.err"],line.col="#CC0066",xlab="time(s)",ylab="# molecules",xlim=c(-15,15), ylim=c(0,1))
myplot(rvsdup3710[,"t"],mnorm(rvsdup3710[,"fi"]),rvsdup3710[,"t.err"],rvsdup3710[,"fi.err"],line.col="#CC00ee",hold_on=TRUE,line.lwd=3,deltat=0.45)
title("2xrvs")

myplot(abpmch_2xBAR_rvs[,"t"],mnorm(abpmch_2xBAR_rvs[,"fi"]),abpmch_2xBAR_rvs[,"t.err"],abpmch_2xBAR_rvs[,"fi.err"],line.col="#660099",xlab="time(s)",ylab="# molecules",xlim=c(-15,15), ylim=c(0,1))
myplot(delsh3dup3714[,"t"],mnorm(delsh3dup3714[,"fi"]),delsh3dup3714[,"t.err"],delsh3dup3714[,"fi.err"],line.col="#6600ee",hold_on=TRUE,line.lwd=3,deltat=0.45)
title("2xBAR")

myplot(abpmch_2xBAR_sla1_no2[,"t"],mnorm(abpmch_2xBAR_sla1_no2[,"fi"]),abpmch_2xBAR_sla1_no2[,"t.err"],abpmch_2xBAR_sla1_no2[,"fi.err"],line.col="#660099",xlab="time(s)",ylab="# molecules",xlim=c(-15,15), ylim=c(0,1))
myplot(delsh3dup[,"t"],mnorm(delsh3dup[,"fi"]),delsh3dup[,"t.err"],delsh3dup[,"fi.err"],line.col="#6600ee",hold_on=TRUE,line.lwd=3,deltat=0.45)
title("2xBAR")

#myplot(abpmch_1x_rvs[,"t"],abpmch_1x_rvs[,"n"],abpmch_1x_rvs[,"t.err"],abpmch_1x_rvs[,"n.err"],line.col="#000000",hold_on=TRUE,line.lwd=3,deltat=0.45)
#myplot(abpmch_1xBAR_rvs[,"t"],abpmch_1xBAR_rvs[,"n"],abpmch_1xBAR_rvs[,"t.err"],abpmch_1xBAR_rvs[,"n.err"],line.col="#66cc99",hold_on=TRUE,line.lwd=3,deltat=0.45)
#myplot(abpmch_2xBAR_rvs[,"t"],abpmch_2xBAR_rvs[,"n"],abpmch_2xBAR_rvs[,"t.err"],abpmch_2xBAR_rvs[,"n.err"],line.col="#660099",hold_on=TRUE,line.lwd=3,deltat=0.45)
#myplot(abpmch_1x_sla1_no2[,"t"],abpmch_1x_sla1_no2[,"n"],abpmch_1x_sla1_no2[,"t.err"],abpmch_1x_sla1_no2[,"n.err"],line.col="#000000",hold_on=TRUE,line.lwd=3,deltat=0.45)
#myplot(abpmch_2x_sla1_no2[,"t"],abpmch_2x_sla1_no2[,"n"],abpmch_2x_sla1_no2[,"t.err"],abpmch_2x_sla1_no2[,"n.err"],line.col="#CC0066",hold_on=TRUE,line.lwd=3,deltat=0.45)
#myplot(abpmch_2xBAR_sla1_no2[,"t"],abpmch_2xBAR_sla1_no2[,"n"],abpmch_2xBAR_sla1_no2[,"t.err"],abpmch_2xBAR_sla1_no2[,"n.err"],line.col="#660099",hold_on=TRUE,line.lwd=3,deltat=0.45)
#myplot(abpmch_1xBAR_sla1_no2[,"t"],abpmch_1xBAR_sla1_no2[,"n"],abpmch_1xBAR_sla1_no2[,"t.err"],abpmch_1xBAR_sla1_no2[,"n.err"],line.col="#66cc99",hold_on=TRUE,line.lwd=3,deltat=0.45)
#myplot(abpmch_rvsdel[,"t"],abpmch_rvsdel[,"n"],abpmch_rvsdel[,"t.err"],abpmch_rvsdel[,"n.err"],line.col="#ccddee",hold_on=TRUE,line.lwd=3,deltat=0.45)


dev.off()
