#plot the data generated by the alignment
library(RColorBrewer)
source("/Users/deepikaa/Desktop/data_desktop/Doc/align_tracks.R")
mnorm<-function(x) return((x-min(x,na.rm=T))/(max(x,na.rm=T)-min(x,na.rm=T)))
##########haploid

#####load data
#SLA1
#upto g -> get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/WT/sla1egfp/2017_06_12_823/ta"))->wtsla12017
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/WT/sla1egfp/2017_06_12_823/test_tracks.Rdata"))->wtsla12017 --> upto "l"
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/WT/sla1egfp/2017_06_12_823/test_tracks.Rdata"))->wtsla12017
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Rvsduplication/Sla1/2017_06_12_161d100_167d100_823_5a/tracks.Rdata"))->rvsdup_sla1 --> upto abp0
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Rvsduplication/Sla1/2017_06_12_161d100_167d100_823_5a/tracks2.Rdata"))->rvsdup_sla1
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Rvsduplication/Rvs_delsh3/2017_12_29/sh3dup_823_5a/tracks.Rdata"))->delsh3dup_sla1
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/rvs_delsh3/rvs167_delsh3_sla1_egfp/2015_04_02/tracks.Rdata"))->delsh3_sla1
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/delrvs167/2020_02_29/1802/percentile_1_5/tracks5.Rdata"))->delrvs_sla1_1801_notrans
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/delrvs167/2020_02_29/1802/percentile_1_5/yoyo2.Rdata"))->delrvs_sla1_1801_yoyo_notrans
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/delrvs167/delrvs_sla1_0531/wo_treatment/analysis_1_2p/tracks.Rdata"))->delrvs_sla1_new #upto12
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/delrvs167/delrvs_sla1_0531/wo_treatment/analysis_1_2p/tracks3.Rdata"))->delrvs_sla1_new 
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/delrvs167/delrvs_sla1_0531/wo_treatment/analysis_1_2p/tracks5.Rdata"))->delrvs_sla1_new #upto 23
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/delrvs167/2021_06_16/4394_rvsdel823/combined_motile.Rdata"))->delrvs_sla1_new
#delrvs
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/delrvs167/2021_06_16/4394_rvsdel823/combined_motile2.Rdata"))->sla1_delrvs_notrans
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/delrvs167/2021_06_16/4394_rvsdel823/combined_yoyo.Rdata"))->sla1_delrvsyoyo_notrans

##--> sla1 2020_01_19 (ie 2021)
#abp mcherry from mcherry_sla1co-tag
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_07_31/823_mch/tracks.Rdata"))->abpmch_notrans_1xRvs
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_02_18/823/tracks.Rdata"))->abpmch_notrans_1xRvs_sla1 upto "l"
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_02_18/823/tracks3.Rdata"))->abpmch_notrans_1xRvs_sla1

get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_07_26/2xRVS823_3706/tracks.Rdata"))->abpmch_notrans_2xRvs_sla1
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_07_27/1xbar_823_3292/tracks2.Rdata"))->abpmch_notrans_1xBar_sla1
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_07_27/1xbar_823_3292/tracks.Rdata"))->abpmch_notrans_1xBar_sla1 --> up 12
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_07_27/2xbar_823_3826/tracks.Rdata"))->abpmch_notrans_2xBar_sla1 --> upto abp0_4
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_07_27/2xbar_823_3826/tracks3.Rdata"))->abpmch_notrans_2xBar_sla1

get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_02_06/1801/tracks.Rdata"))->abpmch_notrans_rvsdel_sla1
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_02_06/1801/tracks2.Rdata"))->abp1SC_delrvs1801_notrans
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_02_06/1801/yoyo.Rdata"))->abp1SC_delrvs1801_yoyo_notrans
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2021_06_16/4393_rvsdel823_mch/tracks3.Rdata"))->abp1SC_delrvs4394_notrans

#trasnformations for sla1
#upto g -> get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments/abpmch_Sla1823_mytrasf.Rdata"))->sla1823_transf
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments/abpmch_Sla1823_11_mytrasf.Rdata"))->sla1823_transf --> upto "l"
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments/abpmch_Sla1823_12_mytrasf.Rdata"))->sla1823_transf

#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments_haploid/rvsdup_sla1_3706_mytrasf.Rdata"))->sla13706_transf --> upto abp0
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments_haploid/rvsdup_sla1_3706_b_mytrasf.Rdata"))->sla13706_transf

get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments_haploid/rvsdelsh3_sla1_3292_c_mytrasf.Rdata"))->sla13292_transf
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments_haploid/rvsdelsh3_sla1_3292_mytrasf.Rdata"))->sla13292_transf --> upto 12
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments_haploid/rvsdelsh3_sla1_3826_tracks2_e_mytrasf.Rdata"))->sla13826_transf #2xbar --> upto abp0_4
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments_haploid/rvsdelsh3_sla1_3826_tracks2_g_mytrasf.Rdata"))->sla13826_transf #2xbar
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments/fimax_false_1801/abpmch_delrvs1801_mytrasf.Rdata"))->sla1801_transf
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments/abpmch_delrvs1801_1801_2021_g_mytrasf.Rdata"))->sla1801_transf
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments/abpmch_delrvs1801_1801_2021_yoyo_mytrasf.Rdata"))->sla1801_yoyo_transf
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/delrvs167/delrvs_sla1_0531/wo_treatment/analysis_1_2p/abpmch_delrvs531_b_mytrasf.Rdata"))->sla531_transf
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments/abpmch_delrvs4394_i_mytrasf.Rdata"))->sla4394_transf
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments/abpmch_delrvs4394_yoyo_b_mytrasf.Rdata"))->sla4394_yoyo_transf

#abp1mCh times from sla1 co-tag
time(abpmch_notrans_1xRvs_sla1$ts)[which(abpmch_notrans_1xRvs_sla1$ts[,"mean_sFI"]==max(abpmch_notrans_1xRvs_sla1$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abpmch_1xRvs_sla1
time(abpmch_notrans_2xRvs_sla1$ts)[which(abpmch_notrans_2xRvs_sla1$ts[,"mean_sFI"]==max(abpmch_notrans_2xRvs_sla1$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abpmch_2xRvs_sla1
time(abpmch_notrans_1xBar_sla1$ts)[which(abpmch_notrans_1xBar_sla1$ts[,"mean_sFI"]==max(abpmch_notrans_1xBar_sla1$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abpmch_1xBar_sla1
time(abpmch_notrans_2xBar_sla1$ts)[which(abpmch_notrans_2xBar_sla1$ts[,"mean_sFI"]==max(abpmch_notrans_2xBar_sla1$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abpmch_2xBar_sla1
time(abpmch_notrans_rvsdel_sla1$ts)[which(abpmch_notrans_rvsdel_sla1$ts[,"mean_sFI"]==max(abpmch_notrans_rvsdel_sla1$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abpmch_rvsdel_sla1
#time(abpmch_notrans_rvsdel$ts)[which(abpmch_notrans_rvsdel$ts[,"mean_sFI"]==max(abpmch_notrans_rvsdel$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abpmch_rvsdel
time(abp1SC_delrvs1801_notrans$ts)[which(abp1SC_delrvs1801_notrans$ts[,"mean_sFI"]==max(abp1SC_delrvs1801_notrans$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abp_delrvs1801
time(abp1SC_delrvs1801_yoyo_notrans$ts)[which(abp1SC_delrvs1801_yoyo_notrans$ts[,"mean_sFI"]==max(abp1SC_delrvs1801_yoyo_notrans$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abp_delrvs1801_yoyo
time(abp1SC_delrvs4394_notrans$ts)[which(abp1SC_delrvs4394_notrans$ts[,"mean_sFI"]==max(abp1SC_delrvs4394_notrans$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abp_delrvs4394

print("time abpmch ok")



##RVS
#####load data

get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/WT/Rvs167/2017_03_29_3131/tracks.Rdata"))->WTrvs3131_notrans
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/rvs_delsh3/rvs167egfp_delsh3/2016_06_02_3154_delsh3_gfp_geneva/analysis2woFlalign/tracks.Rdata"))->delsh3_g_woflalign upto16
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/rvs_delsh3/rvs167egfp_delsh3/2014_07_14_rvs167egfp_delsh3_highmag/se2/first_analysis/tracks.Rdata"))->delsh3_g_woflalign

#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Rvsduplication/Rvs167/2017_06_19/161_d100_167d3131_5b/tracks.Rdata")) -> rvs161d_167d --> upto abp0_3
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Rvsduplication/Rvs167/2017_06_19/161_d100_167d3131_5b/tracks2.Rdata")) -> rvs161d_167d

get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Rvsduplication/Rvs_delsh3/2017_07_21/delsh3dup/tracks.Rdata")) ->delsh3_dup_sorted
#i ->get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Rvsduplication/Rvs_delsh3/2017_07_21/delsh3dup/motile_wt/motile_wt.Rdata")) ->delsh3_dup_sorted

#abp mcherry from rvs_co-tag
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_02_06/3132/test_tracks.Rdata"))->abpmch_notrans_1xRvs_rvs
#upto g, then o onwards --> tracks.Rdata, not test_tracks.
#p --> tracks2021_05_18
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_02_06/3132/tracks2021_05_18.Rdata"))->abpmch_notrans_1xRvs_rvs
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_08_11/3710/tracks.Rdata"))->abpmch_notrans_2xRvs_rvs 

#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_08_11/3286/tracks.Rdata"))->abpmch_notrans_1xBar_rvs upto 9
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_07_27/1xbar_823_3292/tracks.Rdata"))->abpmch_notrans_1xBar_rvs upto11
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_07_27/1xbar_823_3292/tracks2.Rdata"))->abpmch_notrans_1xBar_rvs
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_08_11/3286/tracks.Rdata"))->abpmch_notrans_1xBar_rvs_orig

#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_08_11/3714/tracks.Rdata"))->abpmch_notrans_2xBar_rvs --> upto 7
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_08_11/3714/tracks2.Rdata"))->abpmch_notrans_2xBar_rvs#upto8
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_07_27/2xbar_823_3826/tracks3.Rdata"))->abpmch_notrans_2xBar_rvs
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/2020_08_11/3714/tracks.Rdata"))->abpmch_notrans_2xBar_rvs_orig

#trasnformations for Rvs
#upto g -> get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments/abpmch_Sla1823_mytrasf.Rdata"))->sla1823_transf
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments/abpmch_Rvs3132_e_mytrasf.Rdata"))->rvs3132_transf---> "o"
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments/abpmch_Rvs3132_d_mytrasf.Rdata"))->rvs3132_transf 
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments/abpmch_Rvs3132_f_mytrasf.Rdata"))->rvs3132_transf  --> 'L"
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments/abpmch_Rvs3132_g_mytrasf.Rdata"))->rvs3132_transf 

#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments_haploid/rvsdup_3710_mytrasf.Rdata"))->rvs3710_transf --> upto abp0_3
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments_haploid/rvsdup_3710_b_mytrasf.Rdata"))->rvs3710_transf

#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments_haploid/rvsdelsh3_3714_c_mytrasf.Rdata"))->rvs3714_transf --> upto 8
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments_haploid/rvsdelsh3_3714_alltracks_h_mytrasf.Rdata"))->rvs3714_transf 
#get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments_haploid/rvsdelsh3_3286_mytrasf.Rdata"))->rvs3286_transf --> upto9
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/SC/Abp1-mCH/alignments_haploid/rvsdelsh3_3286_e_mytrasf.Rdata"))->rvs3286_transf

#abp1mch times from rvs co-tag
time(abpmch_notrans_1xRvs_rvs$ts)[which(abpmch_notrans_1xRvs_rvs$ts[,"mean_sFI"]==max(abpmch_notrans_1xRvs_rvs$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abpmch_1xRvs_rvs
time(abpmch_notrans_2xRvs_rvs$ts)[which(abpmch_notrans_2xRvs_rvs$ts[,"mean_sFI"]==max(abpmch_notrans_2xRvs_rvs$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abpmch_2xRvs_rvs
time(abpmch_notrans_1xBar_rvs$ts)[which(abpmch_notrans_1xBar_rvs$ts[,"mean_sFI"]==max(abpmch_notrans_1xBar_rvs$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abpmch_1xBar_rvs
time(abpmch_notrans_2xBar_rvs$ts)[which(abpmch_notrans_2xBar_rvs$ts[,"mean_sFI"]==max(abpmch_notrans_2xBar_rvs$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abpmch_2xBar_rvs

time(abpmch_notrans_1xBar_rvs_orig$ts)[which(abpmch_notrans_1xBar_rvs_orig$ts[,"mean_sFI"]==max(abpmch_notrans_1xBar_rvs_orig$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abpmch_1xBar_rvs_orig
time(abpmch_notrans_2xBar_rvs_orig$ts)[which(abpmch_notrans_2xBar_rvs_orig$ts[,"mean_sFI"]==max(abpmch_notrans_2xBar_rvs_orig$ts[,"mean_sFI"],na.rm=TRUE))]->t0_abpmch_2xBar_rvs_orig

#generate a template transformation matrix to fool gen.data
get(load("/Users/deepikaa/Desktop/data_desktop/Tracking/DC/wt/Rvs167/110824_mytrasf.Rdata"))->transformation_template
transformation_template<-0*transformation_template


##################################################sla1 with transformation
#sla1_wt<-gen.data(WTsla1,sla1_transf, NA, NA, t0=my_t0, zero=0)
#sla1
sla823<-gen.data(wtsla12017,sla1823_transf,n=NA,sn=NA,t0=t0_abpmch_1xRvs_sla1)
rvsdup<-gen.data(rvsdup_sla1,sla13706_transf,n=NA,sn=NA,t0=t0_abpmch_2xRvs_sla1)
delsh3dup<-gen.data(delsh3dup_sla1,sla13826_transf,n=NA,sn=NA,t0=t0_abpmch_2xBar_sla1)
delsh3<-gen.data(delsh3_sla1,sla13292_transf,n=NA,sn=NA,t0=t0_abpmch_1xBar_sla1)
#sla1_rvsdel<-gen.data(delrvs_sla1_new,sla1801_transf,n=NA,sn=NA,t0=t0_abpmch_rvsdel_sla1)
#sla141_rvsdel<-gen.data(delrvs_sla1,transformation_template,n=NA,sn=NA)
#sla1_rvsdel531<-gen.data(delrvs_531_notrans,sla531_transf,n=NA,sn=NA,t0=t0_abp_delrvs1801)

sla1_rvsdel1801<-gen.data(delrvs_sla1_1801_notrans,sla1801_transf,n=NA,sn=NA,t0=t0_abp_delrvs1801)
sla1_1801delrvsyoyo<-gen.data(delrvs_sla1_1801_yoyo_notrans,sla1801_yoyo_transf,n=NA,sn=NA, zero=0, t0=t0_abp_delrvs1801_yoyo)
abp_delrvsw1801yoyo<-gen.data(abp1SC_delrvs1801_yoyo_notrans,transformation_template, n=384.5,sn=35.9,rescale.n=1, t0=t0_abp_delrvs1801_yoyo)
abp_delrvs1801<-gen.data(abp1SC_delrvs1801_notrans,transformation_template, n=384.5,sn=35.9,rescale.n=1,t0=t0_abp_delrvs1801)
sla1_4394<-gen.data(delrvs_sla1_4394,sla4394_transf,n=NA,sn=NA,t0=t0_delrvs_531)
sla1_4394_yoyo<-gen.data(delrvs_sla1_4394_yoyo,sla4394_yoyo_transf,n=NA,sn=NA,t0=t0_delrvs_531)

#abp1 mch SC tracking from sla1 co-tagged strains
#numbers from sla1 co-tag set2 2
#numbers from yellow coloured cells, data_desktop/nuf2/excel/numbers_nuf2_2018_11_c, all on the same day except rvsdel
abpmch_1x_sla1_no2<-gen.data(abpmch_notrans_1xRvs_sla1,transformation_template,n=344.8,sn=27.8,rescale.n=1, t0=t0_abpmch_1xRvs_sla1)
abpmch_2x_sla1_no2<-gen.data(abpmch_notrans_2xRvs_sla1,transformation_template,n=318.8 ,sn=28.1,rescale.n=1, t0=t0_abpmch_2xRvs_sla1)
abpmch_1xBAR_sla1_no2<-gen.data(abpmch_notrans_1xBar_sla1,transformation_template,n=243.5,sn=24.6,rescale.n=1,t0=t0_abpmch_1xBar_sla1)
abpmch_2xBAR_sla1_no2<-gen.data(abpmch_notrans_2xBar_sla1,transformation_template,n=296.2,sn=25,rescale.n=1,t0=t0_abpmch_2xBar_sla1)
#abpmch_rvsdel<-gen.data(abpmch_notrans_rvsdel_sla1,transformation_template,n=384.5,sn=35.9,rescale.n=1,t0=t0_abpmch_rvsdel_sla1) #mky3297
abpmch_rvsdel2_sla1<-gen.data(abpmch_notrans_rvsdel_sla1,transformation_template,n=362.64,sn=39.36,rescale.n=1,t0=t0_abpmch_rvsdel_sla1)
abp_delrvsw1801yoyo<-gen.data(abp1SC_delrvs1801_yoyo_notrans,transformation_template, n=362.64,sn=39.36,rescale.n=1, t0=t0_abp_delrvs1801_yoyo)
abp_delrvs1801<-gen.data(abp1SC_delrvs1801_notrans,transformation_template, n=362.64,sn=39.36,rescale.n=1,t0=t0_abp_delrvs1801)

#rvs delnumbers an average of 5 numbers, 2x data sets 1802, 1801, 4394, 3297

################################################################################rvs with transformation

rvs3132<-gen.data(WTrvs3131_notrans,rvs3132_transf,n=53.2,sn=5.2,t0=t0_abpmch_1xRvs_rvs)
rvsdup3710<-gen.data(rvs161d_167d,rvs3710_transf,n=82.7,sn=7.5,t0=t0_abpmch_2xRvs_rvs)
delsh3dup3714<-gen.data(delsh3_dup_sorted,rvs3714_transf,n=43.6,sn=9.6,t0=t0_abpmch_2xBar_rvs)
rvsdelsh3<-gen.data(delsh3_g_woflalign,rvs3286_transf,n=30.1,sn=9.9,t0=t0_abpmch_1xBar_rvs)

################################################################################
#numbers from rvs co-tag, profiles from rvs co-tag
abpmch_1x_rvs<-gen.data(abpmch_notrans_1xRvs_rvs,transformation_template,n=285.2,sn=27.1,rescale.n=1, t0=t0_abpmch_1xRvs_rvs)
abpmch_2x_rvs<-gen.data(abpmch_notrans_2xRvs_rvs,transformation_template,n=265.8 ,sn=19.9,rescale.n=1, t0=t0_abpmch_2xRvs_rvs)
abpmch_1xBAR_rvs<-gen.data(abpmch_notrans_1xBar_rvs,transformation_template,n=223.6,sn=19.2,rescale.n=1,t0=t0_abpmch_1xBar_rvs)
abpmch_2xBAR_rvs<-gen.data(abpmch_notrans_2xBar_rvs,transformation_template,n=245.8,sn=18.4,rescale.n=1,t0=t0_abpmch_2xBar_rvs)
abpmch_rvsdel<-gen.data(abpmch_notrans_rvsdel_sla1,transformation_template,n=362.64,sn=39.36,rescale.n=1,t0=t0_abpmch_rvsdel_sla1)
abpmch_1xBAR_rvs_orig<-gen.data(abpmch_notrans_1xBar_rvs_orig,transformation_template,n=223.6,sn=19.2,rescale.n=1,t0=t0_abpmch_1xBar_rvs_orig)
abpmch_2xBAR_rvs_orig<-gen.data(abpmch_notrans_2xBar_rvs_orig,transformation_template,n=245.8,sn=18.4,rescale.n=1,t0=t0_abpmch_2xBar_rvs_orig)

#abpmch_rvsdel<-gen.data(abpmch_notrans_rvsdel,transformation_template,n=384.5,sn=35.9,rescale.n=1,t0=t0_abpmch_rvsdel) mky3297

#sla1
xsla823<-mean(sla823[1:25,"x"])
xrvsdup<-mean(rvsdup[1:125,"x"])
xdelsh3dup<-mean(delsh3dup[1:125,"x"])
xdelsh3<-mean(delsh3[1:185,"x"])
#xsla823_inpdel<-mean(sla823_inpdel[1:25,"x"])
#xsla1_rvsdel<-mean(sla1_rvsdel[1:165,"x"])
xsladelrvs<-mean(sla1_rvsdel1801[1:200,"x"])
xsladelrvsyoyo<-mean(sla1_1801delrvsyoyo[1:150,"x"])
#xsla141_rvsdel<-mean(sla141_rvsdel[1:165,"x"])
#x_sla1_rvsdel531<-mean(sla1_rvsdel531[1:150,"x"])
xsladelrvs_4394<-mean(sla1_4394[1:200,"x"])
xsladelrvsyoyo_4394<-mean(sla1_4394_yoyo[1:250,"x"])

#rvs
x_rvs_dup<-mean(rvsdup3710[1:25,"x"])
x_3131<-mean(rvs3132[1:25,"x"])
x_delsh3_sorted<-mean(delsh3dup3714[1:10,"x"])
x_delsh3_g<-mean(delsh3[1:20,"x"])

#abp1 mCH
#x_abpmch<-mean(rabpmch_1x[1:25,"x"])
x_abpmch1x<-mean(abpmch_1x_sla1_no2[1:25,"x"])
x_abpmch2x<-mean(abpmch_2x_sla1_no2[1:25,"x"])
x_abpmch1xBar<-mean(abpmch_1xBAR_sla1_no2[1:10,"x"])
x_abpmch2xBar<-mean(abpmch_2xBAR_sla1_no2[1:25,"x"])
#x_abpmchrvsdel<-mean(abpmch_rvsdel[1:25,"x"])


x_abpmch1x_rvs<-mean(abpmch_1x_rvs[1:25,"x"])
x_abpmch2x_rvs<-mean(abpmch_2x_rvs[1:25,"x"])
x_abpmch1xBar_rvs<-mean(abpmch_1xBAR_rvs[1:10,"x"])
x_abpmch2xBar_rvs<-mean(abpmch_2xBAR_rvs[1:25,"x"])

cols_blue<-brewer.pal(n=9, name="Blues")
cols_rdpu<-brewer.pal(n=9, name="RdPu")


t_abpmch1x=abpmch_1x_sla1_no2[,"t"][1]
t_abpmch2x=abpmch_2x_sla1_no2[,"t"][1]
t_abpmch1xBar=abpmch_1xBAR_sla1_no2[,"t"][1]
t_abpmch2xBar=abpmch_2xBAR_sla1_no2[,"t"][1]
#t_abpmchrvsdel=abpmch_rvsdel[,"t"][1]
t_abpmchrvsdel=abp_delrvs1801[,"t"][1]
t_abpmchrvsdel_yoyo=abp_delrvsw1801yoyo[,"t"][1]

t_abpmch1x_rvs=abpmch_1x_rvs[,"t"][1]
t_abpmch2x_rvs=abpmch_2x_rvs[,"t"][1]
t_abpmch1xBar_rvs=abpmch_1xBAR_rvs[,"t"][1]
t_abpmch2xBar_rvs=abpmch_2xBAR_rvs[,"t"][1]
t_abpmch1xBar_rvs_orig=abpmch_1xBAR_rvs_orig[,"t"][1]
t_abpmch2xBar_rvs_orig=abpmch_2xBAR_rvs_orig[,"t"][1]



#t_rvs1x=abpmch_1x_sla1_no2[,"t"][1]
#t_abpmch2x=abpmch_2x_sla1_no2[,"t"][1]
#t_abpmch1xBar=abpmch_1xBAR_sla1_no2[,"t"][1]
#t_abpmch2xBar=abpmch_2xBAR_sla1_no2[,"t"][1]
#t_abpmchrvsdel=abpmch_rvsdel[,"t"][1]


#t0 as rvs max
rvs3132[,"t"][which(rvs3132[,"n"]==max(rvs3132[,"n"], na.rm=TRUE))] ->t0rvs3132
rvsdup3710[,"t"][which(rvsdup3710[,"n"]==max(rvsdup3710[,"n"], na.rm=TRUE))] ->t0rvs3710
delsh3dup3714[,"t"][which(delsh3dup3714[,"n"]==max(delsh3dup3714[,"n"], na.rm=TRUE))] ->t0delsh3dup3714
rvsdelsh3[,"t"][which(rvsdelsh3[,"n"]==max(rvsdelsh3[,"n"], na.rm=TRUE))] ->t0rvsdelsh3


##with delsh3-duplicated
pdf("all_haploid_2021_abp0_25.pdf")

#b, with transformation matrix that includes all dc tracks for delsh3dup_sla1
#a, with 04, 25, 27,28, 30 removed
#apparently no difference??
#c with new delsh3dup abp1mch SC tracks.Rdata after cleanup, and redoing the DC alignment with this new tracks.Rdata
#d with abp1 nombers from 2020_01_19_haploid, set2
#e with new tracks.data from abpmch 2xBAR after removing tracks 11,14,28,31 from the tracks folder
#f with new 2xBAR abpmch, and also redone DC alignment
#g with newly analysed 1xBAR abpmch
#h with abp_mch rvsco-tag
#i with 2xbar transformation new
#j w/ 2xbar "tracks.Rdata" instead of motile/tracks.Rdata
#k w/ 2xbar DC sorted
#l w/ 2xbar DC sorted again
#all_haploid_2021_abp0_1.pdf  rvsdup_sla1_3706_b
#2 rvsdup_sla1_3706_c
#3: rvsdup_sla1_3706_b, w/ cleanup sc 823 tracks
#4: new rvsdup_3132 rvsdup_3710_b_myransf
#5: new 2xBAR sla1 transf rvsdelsh3_sla1_3826_tracks2_e_mytrasf 
#6: rvsdelsh3_sla1_3826_tracks2_f_mytrasf 
#7: rvsdelsh3_sla1_3826_tracks2_g_mytrasf 
#8: rvsdelsh3_sla1_3826_tracks2_f_mytrasf , new delbardup_rvs rvsdelsh3_3714_alltracks_g
#9: rvsdelsh3_3714_alltracks_h_mytransf !!redoing 2xBAR alignment w/ sla1 abp
#10:rvsdelsh3_3286_b_mytrasf.Rdata !! reoding 1xBAR alignment w/ sla1 abp
#13: rvsdelsh3_3286_c
#14: rvsdelsh3_sla1_3292_b"
#15: rvsdelsh3_sla1_3292_c
#16: rvsdelsh3_3286_e
#17: incl rvs del
#18: checkd rvsdel 2 cold
#19: transf_g for 1801
#22: tracks3.Rdata for 1801
#23: tracks5.Rdata for 1801
#25: newlystarted july

myplot(sla823[,"t"]-t_abpmch1x,sla823[,"x"]-xsla823,sla823[,"t.err"],sla823[,"x.err"],line.col="#023858", xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-15,25),ylim=c(-25,200))
myplot(rvsdup[,"t"]-t_abpmch2x,rvsdup[,"x"]-xrvsdup,rvsdup[,"t.err"],rvsdup[,"x.err"],line.col=cols_rdpu[4],hold_on=TRUE,line.lwd=3,deltat=0.25)
#myplot(rvsdup[,"t"]-t0rvs3710,rvsdup[,"x"]-xrvsdup,rvsdup[,"t.err"],rvsdup[,"x.err"],line.col=cols_rdpu[4],hold_on=TRUE,line.lwd=3,deltat=0.25)

myplot(delsh3dup[,"t"]-t_abpmch2xBar,delsh3dup[,"x"]-xdelsh3dup,delsh3dup[,"t.err"],delsh3dup[,"x.err"],line.col=cols_rdpu[8],hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(delsh3[,"t"]-t_abpmch1xBar,delsh3[,"x"]-xdelsh3,delsh3[,"t.err"],delsh3[,"x.err"],line.col= cols_rdpu[6],hold_on=TRUE,line.lwd=3,deltat=0.25)
#myplot(sla1_rvsdel[,"t"]-t_abpmchrvsdel-8.5,sla1_rvsdel[,"x"]-xsla1_rvsdel,sla1_rvsdel[,"t.err"],sla1_rvsdel[,"x.err"],line.col=cols_rdpu[5],hold_on=TRUE,line.lwd=3,deltat=0.25)
#myplot(sla141_rvsdel[,"t"]-t_abpmchrvsdel-39.5,sla141_rvsdel[,"x"]-xsla141_rvsdel,sla141_rvsdel[,"t.err"],sla141_rvsdel[,"x.err"],line.col=cols_rdpu[7],hold_on=TRUE,line.lwd=3,deltat=0.25)
#myplot(sla1_rvsdel1801[,"t"]-t_abpmchrvsdel+1.5,(sla1_rvsdel1801[,"x"]-xsladelrvs),sla1_rvsdel1801[,"t.err"],sla1_rvsdel1801[,"x.err"],line.col="#002789",hold_on=TRUE,line.lwd=3,deltat=0.25)
#myplot(sla1_delrvsyoyo[,"t"]+13.5,-(sla1_delrvsyoyo[,"x"]-xsladelrvsyoyo-14),sla1_delrvsyoyo[,"t.err"],sla1_delrvsyoyo[,"x.err"],line.col="#710189",hold_on=TRUE,line.lwd=3,deltat=0.25)
#myplot(sla1_1801delrvsyoyo[,"t"]-t_abpmchrvsdel_yoyo,-(sla1_1801delrvsyoyo[,"x"]-xsladelrvsyoyo),sla1_1801delrvsyoyo[,"t.err"],sla1_1801delrvsyoyo[,"x.err"],line.col="#710189",hold_on=TRUE,line.lwd=3,deltat=0.25)
#myplot(sla1_rvsdel531[,"t"]-t_abpmchrvsdel+3,sla1_rvsdel531[,"x"]-x_sla1_rvsdel531,sla1_rvsdel531[,"t.err"],sla1_rvsdel531[,"x.err"],line.col=cols_rdpu[5],hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(sla1_4394[,"t"]-t_abp122,(sla1_4394[,"x"]-xsladelrvs_4394),sla1_4394[,"t.err"],sla1_4394[,"x.err"],line.col="#ff2789",hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(sla1_4394_yoyo[,"t"]-t_abp122,(sla1_4394_yoyo[,"x"]-xsladelrvsyoyo_4394),sla1_4394_yoyo[,"t.err"],sla1_4394_yoyo[,"x.err"],line.col="#710189",hold_on=TRUE,line.lwd=3,deltat=0.25)

title("sla1 movement, t=abp start")

myplot(sla823[,"t"]-t0rvs3132,sla823[,"x"]-xsla823,sla823[,"t.err"],sla823[,"x.err"],line.col="#023858", xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-15,25),ylim=c(-25,200))
myplot(rvsdup[,"t"]-t0rvs3710,rvsdup[,"x"]-xrvsdup,rvsdup[,"t.err"],rvsdup[,"x.err"],line.col=cols_rdpu[4],hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(delsh3dup[,"t"]-t0delsh3dup3714,delsh3dup[,"x"]-xdelsh3dup,delsh3dup[,"t.err"],delsh3dup[,"x.err"],line.col=cols_rdpu[8],hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(delsh3[,"t"]-t0rvsdelsh3,delsh3[,"x"]-xdelsh3,delsh3[,"t.err"],delsh3[,"x.err"],line.col= cols_rdpu[6],hold_on=TRUE,line.lwd=3,deltat=0.25)
#myplot(sla1_rvsdel[,"t"]-t_abpmchrvsdel+30,sla1_rvsdel[,"x"]-xsla1_rvsdel,sla1_rvsdel[,"t.err"],sla1_rvsdel[,"x.err"],line.col=cols_rdpu[5],hold_on=TRUE,line.lwd=3,deltat=0.25)
title("sla1 movement, t0=rvs max")

myplot(delsh3dup[,"t"]-t_abpmch2xBar,delsh3dup[,"x"]-xdelsh3dup,delsh3dup[,"t.err"],delsh3dup[,"x.err"],line.col=cols_rdpu[8],hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(delsh3[,"t"]-t_abpmch1xBar,delsh3[,"x"]-xdelsh3,delsh3[,"t.err"],delsh3[,"x.err"],line.col= cols_rdpu[6],hold_on=TRUE,line.lwd=3,deltat=0.25)
#myplot(sla1_rvsdel[,"t"]-t_abpmchrvsdel-8.5,sla1_rvsdel[,"x"]-xsla1_rvsdel,sla1_rvsdel[,"t.err"],sla1_rvsdel[,"x.err"],line.col=cols_rdpu[5],hold_on=TRUE,line.lwd=3,deltat=0.25)
#myplot(sla141_rvsdel[,"t"]-t_abpmchrvsdel-39.5,sla141_rvsdel[,"x"]-xsla141_rvsdel,sla141_rvsdel[,"t.err"],sla141_rvsdel[,"x.err"],line.col=cols_rdpu[7],hold_on=TRUE,line.lwd=3,deltat=0.25)
#myplot(sla1_rvsdel1801[,"t"]-t_abpmchrvsdel+1.5,(sla1_rvsdel1801[,"x"]-xsladelrvs),sla1_rvsdel1801[,"t.err"],sla1_rvsdel1801[,"x.err"],line.col="#002789",hold_on=TRUE,line.lwd=3,deltat=0.25)
#myplot(sla1_delrvsyoyo[,"t"]+13.5,-(sla1_delrvsyoyo[,"x"]-xsladelrvsyoyo-14),sla1_delrvsyoyo[,"t.err"],sla1_delrvsyoyo[,"x.err"],line.col="#710189",hold_on=TRUE,line.lwd=3,deltat=0.25)
#myplot(sla1_1801delrvsyoyo[,"t"]-t_abpmchrvsdel_yoyo,-(sla1_1801delrvsyoyo[,"x"]-xsladelrvsyoyo),sla1_1801delrvsyoyo[,"t.err"],sla1_1801delrvsyoyo[,"x.err"],line.col="#710189",hold_on=TRUE,line.lwd=3,deltat=0.25)
#myplot(sla1_rvsdel531[,"t"]-t_abpmchrvsdel+3,sla1_rvsdel531[,"x"]-x_sla1_rvsdel531,sla1_rvsdel531[,"t.err"],sla1_rvsdel531[,"x.err"],line.col=cols_rdpu[5],hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(sla1_4394[,"t"]-t_abp122,(sla1_4394[,"x"]-xsladelrvs_4394),sla1_4394[,"t.err"],sla1_4394[,"x.err"],line.col="#ff2789",hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(sla1_4394_yoyo[,"t"]-t_abp122,(sla1_4394_yoyo[,"x"]-xsladelrvsyoyo_4394),sla1_4394_yoyo[,"t.err"],sla1_4394_yoyo[,"x.err"],line.col="#710189",hold_on=TRUE,line.lwd=3,deltat=0.25)

title("sla1 movement, t=abp start")

myplot(sla823[,"t"]-t0rvs3132,sla823[,"x"]-xsla823,sla823[,"t.err"],sla823[,"x.err"],line.col="#023858", xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-15,25),ylim=c(-25,200))
myplot(rvsdup[,"t"]-t0rvs3710,rvsdup[,"x"]-xrvsdup,rvsdup[,"t.err"],rvsdup[,"x.err"],line.col=cols_rdpu[4],hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(delsh3dup[,"t"]-t0delsh3dup3714,delsh3dup[,"x"]-xdelsh3dup,delsh3dup[,"t.err"],delsh3dup[,"x.err"],line.col=cols_rdpu[8],hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(delsh3[,"t"]-t0rvsdelsh3,delsh3[,"x"]-xdelsh3,delsh3[,"t.err"],delsh3[,"x.err"],line.col= cols_rdpu[6],hold_on=TRUE,line.lwd=3,deltat=0.25)
#myplot(sla1_rvsdel[,"t"]-t_abpmchrvsdel+30,sla1_rvsdel[,"x"]-xsla1_rvsdel,sla1_rvsdel[,"t.err"],sla1_rvsdel[,"x.err"],line.col=cols_rdpu[5],hold_on=TRUE,line.lwd=3,deltat=0.25)
title("sla1 movement, t0=rvs max")

myplot(abpmch_1x_sla1_no2[,"t"]-t_abpmch1x,abpmch_1x_sla1_no2[,"n"],abpmch_1x_sla1_no2[,"t.err"],abpmch_1x_sla1_no2[,"n.err"],line.col="#000000",line.lwd=3,deltat=0.25,xlim=c(-15,25),ylim=c(-25,650))
myplot(abpmch_2x_sla1_no2[,"t"]-t_abpmch2x,abpmch_2x_sla1_no2[,"n"],abpmch_2x_sla1_no2[,"t.err"],abpmch_2x_sla1_no2[,"n.err"],line.col="#CC0066",hold_on=TRUE,line.lwd=3,deltat=0.45)
myplot(abpmch_2xBAR_sla1_no2[,"t"]-t_abpmch2xBar,abpmch_2xBAR_sla1_no2[,"n"],abpmch_2xBAR_sla1_no2[,"t.err"],abpmch_2xBAR_sla1_no2[,"n.err"],line.col="#660099",hold_on=TRUE,line.lwd=3,deltat=0.45)
myplot(abpmch_1xBAR_sla1_no2[,"t"]-t_abpmch1xBar,abpmch_1xBAR_sla1_no2[,"n"],abpmch_1xBAR_sla1_no2[,"t.err"],abpmch_1xBAR_sla1_no2[,"n.err"],line.col="#66cc99",hold_on=TRUE,line.lwd=3,deltat=0.45)
#myplot(abpmch_rvsdel[,"t"]-t_abpmchrvsdel,abpmch_rvsdel[,"n"],abpmch_rvsdel[,"t.err"],abpmch_rvsdel[,"n.err"],line.col="#ccddee",hold_on=TRUE,line.lwd=3,deltat=0.45)
legend("topleft",c("abp1mch 1xRvs", "abp1mch 2xRvs","abp1mch 2xBAR", "abp1mch 1xBAR", "abp1mch rvsdel"),lty=1,col=c("#000000", "#CC0066", "#660099","#66cc99","#ccddee"),bty='n', cex=0.75)
title(main="abp mch sla1 co-tag set2")

#######rvs
myplot(rvs3132[,"t"]-t_abpmch1x_rvs,rvs3132[,"x"]-x_3131,rvs3132[,"t.err"],rvs3132[,"x.err"],line.col="#023858", xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-15,25),ylim=c(-25,200))
myplot(rvsdup3710[,"t"]-t_abpmch2x_rvs,rvsdup3710[,"x"]-x_rvs_dup,rvsdup3710[,"t.err"],rvsdup3710[,"x.err"],line.col=cols_rdpu[4],hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(delsh3dup3714[,"t"]-t_abpmch2xBar,delsh3dup3714[,"x"]-x_delsh3_sorted,delsh3dup3714[,"t.err"],delsh3dup3714[,"x.err"],line.col=cols_rdpu[8],hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(rvsdelsh3[,"t"]-t_abpmch1xBar,rvsdelsh3[,"x"]-x_delsh3_g-15.5,rvsdelsh3[,"t.err"],rvsdelsh3[,"x.err"],line.col= cols_rdpu[6],hold_on=TRUE,line.lwd=3,deltat=0.25)
#myplot(sla1_rvsdel[,"t"],sla1_rvsdel[,"x"]-xsla1_rvsdel,sla1_rvsdel[,"t.err"],sla1_rvsdel[,"x.err"],line.col=cols_rdpu[5],hold_on=TRUE,line.lwd=3,deltat=0.25)/
title("rvs movement")


#abp_mch intensity rvs co-tag
myplot(abpmch_2x_rvs[,"t"]-t_abpmch2x_rvs,abpmch_2x_rvs[,"n"],abpmch_2x_rvs[,"t.err"],abpmch_2x_rvs[,"n.err"],line.col="#CC0066",xlab="time(s)",ylab="# molecules",xlim=c(-15,15), ylim=c(0,500))
myplot(abpmch_1x_rvs[,"t"]-t_abpmch1x_rvs,abpmch_1x_rvs[,"n"],abpmch_1x_rvs[,"t.err"],abpmch_1x_rvs[,"n.err"],line.col="#000000",hold_on=TRUE,line.lwd=3,deltat=0.45)
myplot(abpmch_1xBAR_rvs[,"t"]-t_abpmch1xBar_rvs,abpmch_1xBAR_rvs[,"n"],abpmch_1xBAR_rvs[,"t.err"],abpmch_1xBAR_rvs[,"n.err"],line.col="#66cc99",hold_on=TRUE,line.lwd=3,deltat=0.45)
myplot(abpmch_2xBAR_rvs[,"t"]-t_abpmch2xBar_rvs,abpmch_2xBAR_rvs[,"n"],abpmch_2xBAR_rvs[,"t.err"],abpmch_2xBAR_rvs[,"n.err"],line.col="#660099",hold_on=TRUE,line.lwd=3,deltat=0.45)
legend("topleft",c("abp1mch 1xRvs", "abp1mch 2xRvs","abp1mch 2xBAR", "abp1mch 1xBAR"),lty=1,col=c("#000000", "#CC0066", "#660099","#66cc99"),bty='n', cex=0.75)
title(main="abp mch rvs co-tag")

#abp_mch intensity rvs co-tag
myplot(abpmch_2x_rvs[,"t"]-t_abpmch2x_rvs,abpmch_2x_rvs[,"n"],abpmch_2x_rvs[,"t.err"],abpmch_2x_rvs[,"n.err"],line.col="#CC0066",xlab="time(s)",ylab="# molecules",xlim=c(-15,15), ylim=c(0,500))
myplot(abpmch_1x_rvs[,"t"]-t_abpmch1x_rvs,abpmch_1x_rvs[,"n"],abpmch_1x_rvs[,"t.err"],abpmch_1x_rvs[,"n.err"],line.col="#000000",hold_on=TRUE,line.lwd=3,deltat=0.45)
myplot(abpmch_1xBAR_rvs_orig[,"t"]-t_abpmch1xBar_rvs_orig,abpmch_1xBAR_rvs_orig[,"n"],abpmch_1xBAR_rvs_orig[,"t.err"],abpmch_1xBAR_rvs_orig[,"n.err"],line.col="#66cc99",hold_on=TRUE,line.lwd=3,deltat=0.45)
myplot(abpmch_2xBAR_rvs_orig[,"t"]-t_abpmch2xBar_rvs_orig,abpmch_2xBAR_rvs_orig[,"n"],abpmch_2xBAR_rvs_orig[,"t.err"],abpmch_2xBAR_rvs_orig[,"n.err"],line.col="#660099",hold_on=TRUE,line.lwd=3,deltat=0.45)
legend("topleft",c("abp1mch 1xRvs", "abp1mch 2xRvs","abp1mch 2xBAR", "abp1mch 1xBAR"),lty=1,col=c("#000000", "#CC0066", "#660099","#66cc99"),bty='n', cex=0.75)
title(main="abp mch orig rvs co-tag")

##sla1 intensity
myplot(rvsdup[,"t"]-t_abpmch2x,mnorm(rvsdup[,"fi"]),rvsdup[,"t.err"],rvsdup[,"fi.err"],line.col="#CC0066",line.lwd=3,deltat=0.25,xlim=c(-30,30),ylim=c(-0.1,1))
myplot(delsh3dup[,"t"]-t_abpmch2xBar,mnorm(delsh3dup[,"fi"]),delsh3dup[,"t.err"],delsh3dup[,"fi.err"],line.col="#660099",hold_on=TRUE,line.lwd=3,deltat=0.45)
myplot(sla823[,"t"]-t_abpmch1x_rvs,mnorm(sla823[,"fi"]),sla823[,"t.err"],sla823[,"fi.err"],line.col="#000000",hold_on=TRUE,line.lwd=3,deltat=0.45)
title("sla1 fl.int")

#rvs intensity
myplot(rvs3132[,"t"]-t_abpmch1x_rvs,rvs3132[,"n"],rvs3132[,"t.err"],rvs3132[,"n.err"],line.col="#993858", xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-15,25),ylim=c(-25,200))
myplot(rvsdup3710[,"t"]-t_abpmch2x_rvs,rvsdup3710[,"n"],rvsdup3710[,"t.err"],rvsdup3710[,"n.err"],line.col=cols_rdpu[7],hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(delsh3dup3714[,"t"]-t_abpmch2xBar_rvs,delsh3dup3714[,"n"],delsh3dup3714[,"t.err"],delsh3dup3714[,"n.err"],line.col="#6600ee",hold_on=TRUE,line.lwd=3,deltat=0.45)
myplot(rvsdelsh3[,"t"]-t_abpmch1xBar_rvs,rvsdelsh3[,"n"],rvsdelsh3[,"t.err"],rvsdelsh3[,"n.err"],line.col=cols_rdpu[6],hold_on=TRUE,line.lwd=3,deltat=0.45)

##abp_rvsco-tag
##comparing abp for abp and rvs co-tag
#myplot(abpmch_1x_rvs[,"t"],mnorm(abpmch_1x_rvs[,"fi"]),abpmch_1x_rvs[,"t.err"],abpmch_1x_rvs[,"fi.err"],line.col="#CC0066",xlab="time(s)",ylab="# molecules",xlim=c(-15,15), ylim=c(0,1))
#myplot(rvs3132[,"t"],mnorm(rvs3132[,"fi"]),rvs3132[,"t.err"],rvs3132[,"fi.err"],line.col="#CC00ee",hold_on=TRUE,line.lwd=3,deltat=0.45)
#title("1xrvs")

#myplot(abpmch_2x_rvs[,"t"],mnorm(abpmch_2x_rvs[,"fi"]),abpmch_2x_rvs[,"t.err"],abpmch_2x_rvs[,"fi.err"],line.col="#CC0066",xlab="time(s)",ylab="# molecules",xlim=c(-15,15), ylim=c(0,1))
#myplot(rvsdup3710[,"t"],mnorm(rvsdup3710[,"fi"]),rvsdup3710[,"t.err"],rvsdup3710[,"fi.err"],line.col="#CC00ee",hold_on=TRUE,line.lwd=3,deltat=0.45)
#title("2xrvs")
myplot(sla823[,"t"]-t_abpmch1x,sla823[,"x"]-xsla823,sla823[,"t.err"],sla823[,"x.err"],line.col="#023858", xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-15,25),ylim=c(-25,200))
myplot(abpmch_1x_sla1_no2[,"t"]-t_abpmch1x,mnorm(abpmch_1x_sla1_no2[,"fi"])*200,abpmch_1x_sla1_no2[,"t.err"],abpmch_1x_sla1_no2[,"fi.err"],line.col="#000000",hold_on=TRUE,line.lwd=3,deltat=0.45)
myplot(abpmch_1x_rvs[,"t"]-t_abpmch1x_rvs,mnorm(abpmch_1x_rvs[,"fi"])*200,abpmch_1x_rvs[,"t.err"],abpmch_1x_rvs[,"fi.err"],line.col="#0000ee",hold_on=TRUE,line.lwd=3,deltat=0.45)
myplot(rvs3132[,"t"]-t_abpmch1x_rvs,rvs3132[,"x"]-x_3131,rvs3132[,"t.err"],rvs3132[,"x.err"],line.col="#023858", hold_on=TRUE,line.lwd=3,deltat=0.45)
myplot(rvs3132[,"t"]-t_abpmch1x_rvs,mnorm(rvs3132[,"fi"])*200,rvs3132[,"t.err"],rvs3132[,"fi.err"],line.col="#993858", hold_on=TRUE,line.lwd=3,deltat=0.45)
title("WT")

myplot(rvsdup[,"t"]-t_abpmch2x,rvsdup[,"x"]-xrvsdup,rvsdup[,"t.err"],rvsdup[,"x.err"],line.col=cols_rdpu[4],xlab="Time (s)",ylab="Inward movement (nm)",line.lwd=3,deltat=0.25,xlim=c(-15,25),ylim=c(-25,200))
myplot(abpmch_2x_sla1_no2[,"t"]-t_abpmch2x,mnorm(abpmch_2x_sla1_no2[,"fi"])*200,abpmch_2x_sla1_no2[,"t.err"],abpmch_2x_sla1_no2[,"fi.err"],line.col="#CC00dd",hold_on=TRUE,line.lwd=3,deltat=0.45)
myplot(rvsdup3710[,"t"]-t_abpmch2x_rvs,mnorm(rvsdup3710[,"fi"])*200,rvsdup3710[,"t.err"],rvsdup3710[,"fi.err"],line.col=cols_rdpu[7],hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(rvsdup3710[,"t"]-t_abpmch2x_rvs,rvsdup3710[,"x"]-x_rvs_dup,rvsdup3710[,"t.err"],rvsdup3710[,"x.err"],line.col=cols_rdpu[4],hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(abpmch_2x_rvs[,"t"]-t_abpmch2x_rvs,mnorm(abpmch_2x_rvs[,"fi"])*200,abpmch_2x_rvs[,"t.err"],abpmch_2x_rvs[,"n.err"],line.col="#CCeeee",hold_on=TRUE,line.lwd=3,deltat=0.45)
title("2xRVS")

myplot(abpmch_2xBAR_rvs[,"t"]-t_abpmch2xBar_rvs,mnorm(abpmch_2xBAR_rvs[,"fi"])*200,abpmch_2xBAR_rvs[,"t.err"],abpmch_2xBAR_rvs[,"fi.err"],line.col="#66ee99",xlab="time(s)",ylab="# molecules",xlim=c(-15,25), ylim=c(-25,200))
myplot(delsh3dup3714[,"t"]-t_abpmch2xBar_rvs,mnorm(delsh3dup3714[,"fi"])*200,delsh3dup3714[,"t.err"],delsh3dup3714[,"fi.err"],line.col="#6600ee",hold_on=TRUE,line.lwd=3,deltat=0.45)
myplot(delsh3dup[,"t"]-t_abpmch2xBar,delsh3dup[,"x"]-xdelsh3dup,delsh3dup[,"t.err"],delsh3dup[,"x.err"],line.col=cols_rdpu[8],hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(abpmch_2xBAR_sla1_no2[,"t"]-t_abpmch2xBar,mnorm(abpmch_2xBAR_sla1_no2[,"fi"])*200,abpmch_2xBAR_sla1_no2[,"t.err"],abpmch_2xBAR_sla1_no2[,"fi.err"],line.col="#ff00ff",hold_on=TRUE,line.lwd=3,deltat=0.45)
myplot(delsh3dup3714[,"t"]-t_abpmch2xBar_rvs,delsh3dup3714[,"x"]-x_delsh3_sorted,delsh3dup3714[,"t.err"],delsh3dup3714[,"x.err"],line.col=cols_rdpu[8],hold_on=TRUE,line.lwd=3,deltat=0.25)
title("2xBAR")


myplot(abpmch_1xBAR_rvs[,"t"]-t_abpmch1xBar_rvs,mnorm(abpmch_1xBAR_rvs[,"fi"])*200,abpmch_1xBAR_rvs[,"t.err"],abpmch_1xBAR_rvs[,"fi.err"],line.col="#000000",xlab="time(s)",ylab="# molecules",xlim=c(-15,25), ylim=c(-25,200))
myplot(delsh3[,"t"]-t_abpmch1xBar,delsh3[,"x"]-xdelsh3,delsh3[,"t.err"],delsh3[,"x.err"],line.col= cols_rdpu[6],hold_on=TRUE,line.lwd=3,deltat=0.25)
myplot(rvsdelsh3[,"t"]-t_abpmch1xBar_rvs,mnorm(rvsdelsh3[,"fi"])*200,rvsdelsh3[,"t.err"],rvsdelsh3[,"fi.err"],line.col=cols_rdpu[6],hold_on=TRUE,line.lwd=3,deltat=0.45)
myplot(abpmch_1xBAR_sla1_no2[,"t"]-t_abpmch1xBar,mnorm(abpmch_1xBAR_sla1_no2[,"fi"])*200,abpmch_1xBAR_sla1_no2[,"t.err"],abpmch_1xBAR_sla1_no2[,"fi.err"],line.col="#66ccee",hold_on=TRUE,line.lwd=3,deltat=0.45)
myplot(rvsdelsh3[,"t"]-t_abpmch1xBar_rvs,rvsdelsh3[,"x"]-x_delsh3_g-15.5,rvsdelsh3[,"t.err"],rvsdelsh3[,"x.err"],line.col= cols_rdpu[6],hold_on=TRUE,line.lwd=3,deltat=0.25)
title("1xBAR")

#myplot(abpmch_2xBAR_sla1_no2[,"t"],mnorm(abpmch_2xBAR_sla1_no2[,"fi"]),abpmch_2xBAR_sla1_no2[,"t.err"],abpmch_2xBAR_sla1_no2[,"fi.err"],line.col="#660099",xlab="time(s)",ylab="# molecules",xlim=c(-15,15), ylim=c(0,1))
#myplot(delsh3dup[,"t"],mnorm(delsh3dup[,"fi"]),delsh3dup[,"t.err"],delsh3dup[,"fi.err"],line.col="#6600ee",hold_on=TRUE,line.lwd=3,deltat=0.45)
#title("2xBAR")

#myplot(abpmch_1x_rvs[,"t"],abpmch_1x_rvs[,"n"],abpmch_1x_rvs[,"t.err"],abpmch_1x_rvs[,"n.err"],line.col="#000000",hold_on=TRUE,line.lwd=3,deltat=0.45)
#myplot(abpmch_1xBAR_rvs[,"t"],abpmch_1xBAR_rvs[,"n"],abpmch_1xBAR_rvs[,"t.err"],abpmch_1xBAR_rvs[,"n.err"],line.col="#66cc99",hold_on=TRUE,line.lwd=3,deltat=0.45)
#myplot(abpmch_2xBAR_rvs[,"t"],abpmch_2xBAR_rvs[,"n"],abpmch_2xBAR_rvs[,"t.err"],abpmch_2xBAR_rvs[,"n.err"],line.col="#660099",hold_on=TRUE,line.lwd=3,deltat=0.45)
#myplot(abpmch_1x_sla1_no2[,"t"],abpmch_1x_sla1_no2[,"n"],abpmch_1x_sla1_no2[,"t.err"],abpmch_1x_sla1_no2[,"n.err"],line.col="#000000",hold_on=TRUE,line.lwd=3,deltat=0.45)
#myplot(abpmch_2x_sla1_no2[,"t"],abpmch_2x_sla1_no2[,"n"],abpmch_2x_sla1_no2[,"t.err"],abpmch_2x_sla1_no2[,"n.err"],line.col="#CC0066",hold_on=TRUE,line.lwd=3,deltat=0.45)
#myplot(abpmch_2xBAR_sla1_no2[,"t"],abpmch_2xBAR_sla1_no2[,"n"],abpmch_2xBAR_sla1_no2[,"t.err"],abpmch_2xBAR_sla1_no2[,"n.err"],line.col="#660099",hold_on=TRUE,line.lwd=3,deltat=0.45)
#myplot(abpmch_1xBAR_sla1_no2[,"t"],abpmch_1xBAR_sla1_no2[,"n"],abpmch_1xBAR_sla1_no2[,"t.err"],abpmch_1xBAR_sla1_no2[,"n.err"],line.col="#66cc99",hold_on=TRUE,line.lwd=3,deltat=0.45)
#myplot(abpmch_rvsdel[,"t"],abpmch_rvsdel[,"n"],abpmch_rvsdel[,"t.err"],abpmch_rvsdel[,"n.err"],line.col="#ccddee",hold_on=TRUE,line.lwd=3,deltat=0.45)


dev.off()
